### ISSUE TITLE
reset config on windows machine

### ISSUE THREAD

**Issue by nonspacial** [git-ftp/git-ftp#116]
Hi wicked little plugin u have here only prob i have now is i set the syncroot thinking it was for the remote server not the local one and now i want to delete it but leaving it blank doesn't reset it if i try to save over it. sudo obv does't work in git-bash but someone will know how i to convert these 2 codes:

sudo apt-get purge git-ftp 

&

sudo apt-get purge --auto-remove git-ftp

while i'm at it these 2 would be hlepful too:

sudo apt-get remove --auto-remove git-ftp

&

sudo apt-get remove git-ftp

this stuff really should be in the documentation though.

Thanks Robbie

**Comment by DerTanzschuh** [comment]
If you set up the config for syncroot with `git config` like this
```
git config git-ftp.syncroot
```
you can use the same git mechanism to remove it:
```
git config --unset git-ftp.syncroot
```

Since the configs are stored inside your repository, removing git-ftp would not help.
