### ISSUE TITLE
Can't remove folder

### ISSUE THREAD

**Issue by desmondliang** [git-ftp/git-ftp#145]
I notice that when I remove a entire folder from the repo and push the change to the server, the app deletes all files in the folder but fails to delete the containing folder.

The error message reads "Could not delete [path to folder], continuing...".

I use SFTP to log on to the remote server trying to remove a folder that was created by myself. I have full permission to that folder, but the app seems to fail on deleting the folder after killing all the files inside.

**Comment by mkllnk** [comment]
@resmo had to remove that functionality completely, because some servers would delete non-empty directories. This needs a re-implementation. Then, we still need to know which delete commands work for which servers.

(Sorry for closing.)

**Comment by lin-123** [comment]
ftp can not remove  folder. scene same to "I notice that when I remove a entire folder from the repo and push the change to the server, the app deletes all files in the folder but fails to delete the containing folder."
