### ISSUE TITLE
Idea: Create a human friendly file with current hash and date on push

### ISSUE THREAD

**Issue by adbre** [git-ftp/git-ftp#158]
Currently it's possible to use .git-ftp.log, but a 40-char hash is quite nonsense for a non-technical person. And especially if you do not have access to the Git repository (or the know-how).

Another way is to create this file manually, commit and push (creating an extra commit on each release/deployment).

So, instead, I'd like git-ftp to be able to this for me after a successful deployment.

Example:
    $ git commit -m "foo"
    $ git ftp push
    $ curl http://my-site.example.org/.git-ftp.currentversion.txt
    v0.8-beta-233-deadbee 2015-01-03 13:20 +02:00

**Comment by mkllnk** [comment]
Interesting. Let's look at these two ideas separately.

 1. Write the date into `.git-ftp.log`
That's quite easy to implement. But do you think that `c696398809fb289b892857ff8ea9159985cb4220 2015-01-03 13:20 +02:00` is more clear for a non-technical person?

 2. Your example of an additional `.git-ftp.currentversion.txt`
You can use a [Git after-commit hook](http://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) to generate such a file and `.git-ftp-include` to always upload that file. Would solve that your issue?

**Comment by resmo** [comment]
>Currently it's possible to use .git-ftp.log, but a 40-char hash is quite nonsense for a non-technical person

`.git-ftp.log` was never designed to be meaningful for humans at all.

> Another way is to create this file manually, commit and push (creating an extra commit on each release/deployment).

 _this_ is nonsense...

As @mkllnk  pointed out, there are ways to accomplish your requirement and for the reason to keep git-ftp small, we won't implement anything in this direction.
