### ISSUE TITLE
[Question] Option to change filename of .git-ftp.log file?

### ISSUE THREAD

**Issue by JustMaier** [git-ftp/git-ftp#160]
The server I am using automatically deletes any `.log` files (annoying!). Is there a way to make the tool look for a different filename like `git-ftp.txt`?

I saw the option for `deployedsha1file` but setting that to `git-ftp.txt` still doesn't seem to do the trick.

**Comment by mkllnk** [comment]
Good one. You used the right option but it seems to be broken. I'll try to fix it in the next weeks. As short-term hack you could edit the git-ftp script. Just search and replace `.git-ftp.log`.

**Comment by JustMaier** [comment]
Thanks @mkllnk the search and replace worked as a temporary work around.

**Comment by mkllnk** [comment]
Okay, the problem was that the option was only considered in combination with scopes. I just pushed a fix.

**Comment by JustMaier** [comment]
Thanks for taking the time to fix that.
