### ISSUE TITLE
Add option to push even if the repository is dirty

### ISSUE THREAD

**Issue by halilim** [git-ftp/git-ftp#162]
Sometimes we need to push a more emergent fix in between developing a larger feature, or we just want to push some part of the actual thing before deploying it fully. E.g.: a feature that makes changes to db/cache fields. This would end in fatal error if pushed in a single commit. So we generally split it into multiple parts: 1) Push migration/cache name changes 2) Run migrations/refresh caches 3) Push the actual thing.

Right now, the only option I know of is

1. Commit partial
2. `git stash save` remaining
3. Push
4. `git stash apply`

It would be very useful if we had an option to push regardless of the dirty status. It would be even better if this could be set globally or if the script asked for confirmation instead of just exiting.

**Comment by resmo** [comment]
I see your point, but git-ftp was not designed to push a dirty workspace. To support this, it would need major changes and I have no plans to make these changes.

**Comment by halilim** [comment]
Actually I don't want to push the dirty workspace, only the last commit. I thought putting `HEAD` after `"$DEPLOYED_SHA1"` at [L570](https://github.com/git-ftp/git-ftp/blob/150a86678eeb61436b6ace791a26b00c1e6476a5/git-ftp#L570) would fix it by checking against the HEAD, which is generally the last commit, but I kind of see the problem now: if there is a change in a file both in the last commit and in the workspace, the copy of the file from the workspace will be uploaded anyway, which would result in a half-uploaded (and possibly broken) workspace.

**Comment by mpathy** [comment]
I also would like to have some option to git-ftp who allows this..
We use git-ftp in our Jenkins Workflow, but its obviously a problem to have optimisations like uglify and minify and image compression already in the the repo, so it would be done in the Jenkins Pipeline.
But now of course this error is shown. I know it is wrong but if there is a possibility...

**Comment by mkllnk** [comment]
@mpathy Can you list the newly created files in `.gitignore`? You could also have a separate ignore file just on Jenkins. See https://help.github.com/articles/ignoring-files/#create-a-global-gitignore.

**Comment by camlafit** [comment]
Hello

Could be nice to have an option '-stash'. Purpose should be to act a stash and stash pop between push action.
It's a be ugly to do git stash; git ftp push -s remote; git stash pop
One use case is to have a local dev and remote test. In this case local dev is mainly dirty with work in progress.

Thanks
