### ISSUE TITLE
Pushing Delete of .DS_STORE deletes directory

### ISSUE THREAD

**Issue by JustMaier** [git-ftp/git-ftp#168]
I just ran into this bug. Here's what I did. I inherited code. I setup git. I removed the .DS_STORE files in the project and pushed the commit with GIT-FTP. It reported that it deleted the .DS_STORE successfully, however after checking via FTP manually I realized that It indeed deleted the file but then went on to delete the entire directory...

**So Steps to Reproduce:**
1. Create a git project with a few folders and one of them with a .DS_STORE in it
2. Commit the project and Push the project via GIT-FTP
3. Remove the .DS_STORE files
4. Commit the change and Push the project via GIT-FTP
5. Check the project via FTP and see the directory is missing

**Comment by resmo** [comment]
There were no other files in this dir right?

**Comment by JustMaier** [comment]
@resmo actually the directories were still full of images. I can record a video of it happening if that would help.

**Comment by resmo** [comment]
Oh okay, not good. Vidoe is noot necessary. Thanks.

**Comment by JustMaier** [comment]
Thanks for the quick fix.

**Comment by resmo** [comment]
what was the protocol used? FTP? or SFTP?

**Comment by JustMaier** [comment]
FTP. I'm testing the commit now. I'll let you know how it goes.

**Comment by JustMaier** [comment]
Ok, I just tested this using exactly what caused it the first time and it no longer deletes the entire directory. The fix was successful.

**Comment by resmo** [comment]
release 1.0.2 queued, thanks for testing!
