### ISSUE TITLE
mktemp: command not found on Windows 7

### ISSUE THREAD

**Issue by ingro** [git-ftp/git-ftp#172]
Hello! I recently updated git-ftp to 1.0 and now I receive this warning in console:
`C:\Program Files\git-ftp\git-ftp: line 28: mktemp: command not found`

At first I didn't think this was a big issue since the upload went smooth as usual, but then when I ran `git ftp push` on another repository a strange thing happened, I get many curl errors like this:
```
curl: Can't open './app/config/local/cache.php'!
curl: try 'curl --help' or 'curl --manual' for more information
```

The problem is that the file `app/config/local/cache.php` was a file that should be (and was) uploaded on the first repository, but for some reason it was trying to upload for the second one too, so I guess the earlier operation is not cleaned properly after success, or something like that, if mktemp is not present :(

It seems that's related with #164, can you point me to a working commit before that was merged so I can keep using git ftp before it gets fixed?

Thank you.

**Comment by mkllnk** [comment]
Thanks for this report. It is related to recent changes starting with commit d216979.

We create a bunch of temporary files to store the file lists. In the past, they were just written to the repository working tree which isn't ideal. Now, the files are stored in the system's temporary directory and `mktemp` is used to create a unique directory there.

I think we should use the directory `.git/git-ftp-tmp/` in case `mktemp` is not available.

**Comment by ingro** [comment]
Thanks for pointing that out, I reverted to a previous commit and now it's working again!

**Comment by resmo** [comment]
@ingro you are using Cygwin right? Can you verify if there is a `mkstemp` binary?

**Comment by ingro** [comment]
@resmo Actually no, I've installed the official Git for Windows which include a lot of binaries in its `bin` directory, like `curl`, `ls`, `ssh` and so on.

**Comment by resmo** [comment]
but no `mkstemp` ?

**Comment by ingro** [comment]
Nope, at least in the version i'm using (1.9.5), which is the last I think.

**Comment by resmo** [comment]
Ok, thanks for your report. I'll will implement a fix without need of mktemp.

**Comment by Wardevour** [comment]
I tried installing mktemp from: http://gnuwin32.sourceforge.net/packages/mktemp.htm and I get:
C:\Program Files (x86)\Git\bin\mktemp.exe: cannot make temp dir C:/Users/Owner/A
ppData/Local/Temp/git-ftp-4520: Invalid argument

**Comment by BrettLefty** [comment]
I'm seeing the same issue. Had git-ftp working before on this machine, but now it won't. It's a been a while, so I'm not sure what I have changed. I do have MinGW installed, and I get a "STATUS_ACCESS_VIOLATION" when trying to run mktemp.

Strangely, mktemp works from powershell and the regular windows command line, but not git bash.

**Comment by huiralb** [comment]
i have same issue.  i use git bash  and msysGit for simple run 'git ftp init'

**Comment by abeldantas** [comment]
I'm having the same problem
You mean version 0.9 of git for windows?
And it works out for you?
where is the download for that version? Do I need to clone with some option to specify the version, could you tell me what that is?

**Comment by silvermoon1710** [comment]
hi @abeldantas , no it not about git. it about git-ftp. you should use this version. https://github.com/git-ftp/git-ftp/releases/tag/0.9.0. it work for me. same installing process

**Comment by abeldantas** [comment]
awesome, I had already finished a python script to sync the remote and
local directories :p
I will still use git-ftp because it's faster, thanks silvermoon1710

**Comment by danieldevine** [comment]
Assuming that you've already installed the latest version using the steps in INSTALL.md and its not working in Windows 8.1 with msysgit, and you want to revert to the last working commit which was [c064ed2](https://github.com/git-ftp/git-ftp/commit/c064ed2a78d712c126b6db6420edcb8a85349d38)

<code>$ cd ~/git-ftp</code>
<code>$ git reset --hard c064ed2a78d712c126b6db6420edcb8a85349d38</code>

Go to C:\Users\YourName\AppData\Local\VirtualStore\Program Files (x86)\Git and delete the bin directory, then:

<code>$ cd ~/git-ftp</code>
<code>$ cd git-ftp && chmod +x git-ftp</code>
<code>$ cd /bin</code>
<code>$ ln -s ~/git-ftp/git-ftp</code>

and you'll be working again.

**Comment by resmo** [comment]
Hi all

IMHO we are mixing things here. First `mktemp` is not in the 1.0.x release. So if you are using the release version and not the master branch, everything should be fine.

If you have other issues with Windows 8.1. please report separately. 

** Always ** report the version you are using, if you use a unreleased version add commit as well.

Can anyone report, version 1.0.2 is working as expected?

**Comment by BrettLefty** [comment]
The latest version fixes this issue, or at least it did for me.

Windows 7 64-bit with Git for Windows
