### ISSUE TITLE
large number of files. 

### ISSUE THREAD

**Issue by anandarajpandey** [git-ftp/git-ftp#174]
Trying to upload 15000 files and getting out of memory issue. 
can we limit buffer?

**Comment by mkllnk** [comment]
Which version of `git-ftp` are you using?

    git-ftp --version

**Comment by anandarajpandey** [comment]
git-ftp version 1.1.0-UNRELEASED

**Comment by anandarajpandey** [comment]
I am using windows, and old version worked great but this version giving me problems. Even files are seems like not uploading at all, it just says uploading but nothing happens.

**Comment by mkllnk** [comment]
Is there just no output or do you get an error message 'out of memory'?

What happens if you add the option `-v` for verbose mode?

**Comment by anandarajpandey** [comment]
i just get message out of memory, it was buffering for almost 12 hours, so
i think do to large number of files ( 5 GB in size and 15000 + files)
buffer ran out of memory.

**Comment by resmo** [comment]
closing it, due no further info given... no debug log, etc
