### ISSUE TITLE
Shell glob not working as described in man page

### ISSUE THREAD

**Issue by hahnjo** [git-ftp/git-ftp#177]
When ignoring all .txt files, I have to write `.*.txt`. Man page mentions `*.txt`.
(I'm using ArchLinux, bash version is 4.3.33(1))

**Comment by mkllnk** [comment]
Are you using the most recent develop version of git-ftp? That behaviour was changed recently and the new syntax `*.txt` is not released yet.

**Comment by hahnjo** [comment]
Sorry, confused myself because HEAD isn't the latest released but the latest development version.

Does this mean that current .git-ftp-ignore files will be incompatible with newer versions that use shell globs?

**Comment by mkllnk** [comment]
Yes, if you used regular expressions in your .git-ftp-ignore file. They will not work anymore. So `.*.txt` will not match all txt files anymore.
