### ISSUE TITLE
Pandoc depencency at installation of man pages

### ISSUE THREAD

**Issue by sudaraka** [git-ftp/git-ftp#179]
This more of a question than a issue, in my system (Archlinux) I don't have pandoc installed by default and it is not in official repositories either. Installing pandoc pulls in over 1Gb of haskel dependencies and I think it overkill to just convert the .md into man page format.

Is there other reason for choosing pandoc?

I changed the Makefile to use ronn instead which have a low dependency foot print compared to pandoc. It's available here https://github.com/sudaraka/git-ftp, If interested I can generate a pull request.

**Comment by resmo** [comment]
Definitely interested. Please make a pull request.

**Comment by mkllnk** [comment]
Merged.

**Comment by jmurowaniecki** [comment]
This issue deserves a :+1: like button.
