### ISSUE TITLE
is it possible with git-ftp version controlling database also?

### ISSUE THREAD

**Issue by nonchiedercilaparola** [git-ftp/git-ftp#181]
I'm trying a solution to version controlling wp files and db on shared hosting without ssh and git.

Regards

Luigi

**Comment by mkllnk** [comment]
Do you mean the files WordPress generates? Or do you mean the (MySQL) database?

If you want to download stuff from the FTP server and record a new version in your git repo, this new branch could be what you are looking for: https://github.com/git-ftp/git-ftp/tree/pull

It requires `lftp` .

If you want to version control an SQL database, you can only store dump files and version control them. Does that answer your question?

**Comment by nonchiedercilaparola** [comment]
i wuold like to have also database into version controlling but you confrim me that it's only possible to versione controlling dump files.

thanks

**Comment by mkllnk** [comment]
It depends on the database. For example, SQLite let's you store the data where ever you like. If you store an SQLite database within your working tree, you can version control that easily. The disadvantage is a drop in performance and a lack of some more advanced features.

But if you use MySQL or PostgreSQL, you have to create dump files to version control them.
