### ISSUE TITLE
Uploading to subfolder

### ISSUE THREAD

**Issue by Fluik** [git-ftp/git-ftp#183]
Hi, we're using work server, where we have folders with name of webpages. 
I'm trying to use git-ftp to upload files to one of those folders, but files are also uploaded to root.

I have URL set to server.cz/folder, I even try using remote-root.

**Comment by mkllnk** [comment]
That should work. Can you give more information about your setup?

 - git-ftp version
 - transfer protocol (ftp, sftp)
 - verbose output of git-ftp (parameter -vv), WARNING: obfuscate your password if it's in there

**Comment by Fluik** [comment]
Thanks for reply. Today I reinstall git and git-ftp and it's working fine now. Probably problem on my end, since I'm new to whole git and command line stuff.
