### ISSUE TITLE
Is git-ftp can use remote profile like normal git ?

### ISSUE THREAD

**Issue by silvermoon1710** [git-ftp/git-ftp#185]
Hi, currently i'm buliding 1 internal product for my company. I have just been provided FTP accounts to 2 server (1 for testing and 1 for production) . i really like the way that remote in git work. I wonder is git-ftp can work with remote same normal git ?

**Comment by mkllnk** [comment]
`git-ftp` can be used to deploy to multiple servers (testing and production). But it does not use remotes for that. It uses scopes. For example, you can have the testing account your default and add a scope for the production account. Pushing to testing works as usual:

    git ftp push

For pushing to production you need to select the according scope:

    git ftp push -s production

**Comment by silvermoon1710** [comment]
thank @mkllnk . that's a good tip ^^

**Comment by resmo** [comment]
btw if you just do `git-ftp push -s` it will use the current branch name as scope.
