### ISSUE TITLE
Upload fails on filenames starting with #

### ISSUE THREAD

**Issue by djvj1** [git-ftp/git-ftp#186]
When uploading a file starting with #, for example "#a.png", it fails with this error:

curl: (3) Uploading to a URL without a file name!
Fri Apr  3 21:53:04 PDT 2015: fatal: Could not upload files., exiting...

**Comment by resmo** [comment]
which version are you using?

**Comment by djvj1** [comment]
Hi, at the time, it was the latest. I made my own solution though and
because of that bug, no longer use git-ftp. So I can't really be of
assistance anymore, but the bug does still exist if it hasn't been fixed
already.

**Comment by mkllnk** [comment]
I thought that I could reproduce the problem. But I used a very old version of git-ftp by accident. I got the exact same error message.

I can't reproduce it with the current version though.
