### ISSUE TITLE
Force push to untracked files

### ISSUE THREAD

**Issue by qmachard** [git-ftp/git-ftp#187]
I would like to know if it was possible to force to push files untracked ? Because there are many things to compile (scss, sprites, etc.) and I would like to push them automatically... Tank you, and good job !!

**Comment by mkllnk** [comment]
Yes, there is: https://github.com/git-ftp/git-ftp/blob/develop/man/git-ftp.1.md#syncing-untracked-files
The documentation could be improved though.
Thank you. :-)

**Comment by qmachard** [comment]
Thank you ;-)
