### ISSUE TITLE
Compiled Files aren't registering as being changed and aren't uploading

### ISSUE THREAD

**Issue by johnheiner** [git-ftp/git-ftp#188]
I am compiling my source files with Gulp, committing them, and then pushing them, but git ftp responds with 'No changed files for [my git-ftp.url]. Everything up-to-date.'

All compiled files live inside the /dist folder, but we are marking them as binary in order to ignore file conflicts on commit. Following parts 1 and 2 [here](http://blog.andrewray.me/dealing-with-compiled-files-in-git/)

Here are my git files.

###### .gitattributes
```
dist/**/* -diff
dist/**/* merge=ours
```
###### .git/config
```
[git-ftp "test"]
	user = XXXXX
	url = XXXXX
	password = XXXXX
[merge "ours"]
    name = "Keep ours merge"
    driver = true
```

When I commit, it registers that my compiled files have changed, but when I go to ftp push, it says everything is up-to-date. Does this way of tracking but ignoring changes to files in git break how git ftp registers changed files? Curious why it thinks it's up-to-date.

Great work on this by the way. Thanks for any help/guidance!

**Comment by mkllnk** [comment]
Interesting. Do these files appear in `git diff`?

`git-ftp` retrieves the list of changed files simply from:
```
git diff --name-status --no-renames "$DEPLOYED_SHA1"
```

Do you know a better way of getting that file list?

Thanks for that report.

**Comment by mkllnk** [comment]
Hi again,

I tried to reproduce the issue you are having without success. `git diff --name-status` still outputs the changed "binary" files and they get uploaded in my case. Do you have some rule in `.git-ftp-ignore` that might be the cause?

**Comment by mkllnk** [comment]
I'm closing this issue since I haven't heard back from you. Feel free to give more information on this case.

**Comment by shooftie** [comment]
I'm also having this issue. I'm sure it's not a bug but config in nature.

My project structure is:
- repo/
    - src/
        - scss/
        - app/
        - img/
        - index.html
    - dist/
        - css/
        - js/
        - img/
        - index.html

`dist/` is being ignored in my `.gitignore`.

My .git-ftp-include is:

    dist/css/*:src/scss/*.scss
    dist/js/*:src/app/**/*
    dist/img/*:src/img/*

My git-ftp config is:

    [git-ftp "staging"]
      user = username
      url = ftpes://ftp.my.domain:21
      password = password
      syncroot = dist

I think I am missing something fundamental because no matter what I do:

    Last deployed SHA1 for ftp.my.domain:21/ is ...
    No changed files, but different commit ID. Changed files ignored or commit amended.
    No files to sync. All changed files ignored.
    There are no files to sync.
    Uploading commit log to ftp://...:21/.git-ftp.log.
    Last deployment changed to ...

**Comment by mkllnk** [comment]
Looks like a misunderstanding of the include syntax. Currently, it doesn't support wildcards. You would need to do something like this:
```
dist/css/a.css:src/scss/a.scss
dist/css/b.css:src/scss/b.scss
```

This was also requested in #325.

**Comment by shooftie** [comment]
Great, that'll explain a lot.
