### ISSUE TITLE
Document meaning of `!` in `.git-ftp-include`

### ISSUE THREAD

**Issue by neojski** [git-ftp/git-ftp#195]
I didn't know about this, very useful, thing. I only learned about it from [.git-ftp-include wildcards](https://github.com/git-ftp/git-ftp/issues/72#issuecomment-73480989) issue. Certainly worth documenting in the [syncing untracked files](https://github.com/git-ftp/git-ftp/blob/d7a7ff94b5e1045215f626bb4ad71b6fa3e008b2/man/git-ftp.1.md#syncing-untracked-files) section.

**Comment by mkllnk** [comment]
Good point. I updated the documentation: https://github.com/git-ftp/git-ftp/blob/develop/man/git-ftp.1.md#syncing-untracked-files

Is it alright?

Feel free to change stuff and open a pull request.

**Comment by neojski** [comment]
Looks good, thanks!
