### ISSUE TITLE
Push files that are in .gitignore

### ISSUE THREAD

**Issue by adriandmitroca** [git-ftp/git-ftp#197]
Hey,

Is it possible to push or force it somehow to upload specific files that are generally in .gitignore - for example `/vendor` directory (because who would want to store dependencies in repo)?

Because typical FTP server doesn't provide CLI of any kind it's kinda must-have feature - without dependencies uploaded none of real projects would work.

**Comment by mkllnk** [comment]
Yes, git-ftp does that. You need a file `.git-ftp-include`. If you want to upload vendor every time, put this line in there:

    !vendor/

If you want to upload vendor only if composer.lock changes:

    vendor/:composer.lock

But git-ftp can't know which files in vendor/ are already synced and which are not. So it uploads all files in vendor/.

This behaviour was recently documented in the man page:
https://github.com/git-ftp/git-ftp/blob/develop/man/git-ftp.1.md#syncing-untracked-files

**Comment by adriandmitroca** [comment]
Thanks! That is awesome to hear!

**Comment by adriandmitroca** [comment]
Sadly - first method (without watching for changes in any file) so in this case:
`!public/build/

Gives:
`[8 of 8] Buffered for upload 'public/build/'.`

and all files in this folder are not sent during the push (unlike vendor/ when composer.lock changes).

Any idea?

**Comment by mkllnk** [comment]
Are you sure that `public/build/` is a directory and not a symlink?

Can you post the result of the following commands executed in you repository?
```bash
    TARGET='public/build/'
    [ -d "$TARGET" ]; echo $?
```

Oh, and which version of git-ftp are you using?

**Comment by adriandmitroca** [comment]
Yes - I am sure. This is a directory.

`Adrian:repo adrian$ git ftp --version //
git-ftp version 1.0.2`

`Adrian:repo adrian$ TARGET='public/build/' [ -d "$TARGET" ]; echo $? //
0`

I am working on OS X.

**Comment by mkllnk** [comment]
Ok, good to know. Version 1.0.2 doesn't support the upload of directories with the !-syntax yet. We implemented that in the latest developer build, but it seems that it doesn't work on OSX either (#205). Probably, you shouldn't update git-ftp until this is solved. I'll close this issue in favor of #205.

**Comment by netfox01** [comment]
is it possible somehow that git ftp can track the changes in vendor folder by adding it to the index int he background and upload only changed files, without affecting the project?

for instance, you can initialize another git instance inside the vendor folder, and while vendor folder is in .gitignore file, that won't affect the main project, but git-ftp can access that vendor folder if it's in .git-ftp-include and track the files inside.

**Comment by mkllnk** [comment]
I imagine that your vendor folder is your .gitignore file, right? So it is not part of your git repository. You can just go in that directory and track it with git:
```sh
cd vendor
git init
git add .
git commit -m "Initial set of vendor packages"
git ftp init example.com/project/vendor
```

When ever you push your changes from your main repository, you can also do:
```sh
cd vendor
git ftp push
```

If you are not the only person to push the vendor folder to the server, you need to share that Git repository with the other people as well.

**Comment by Webman2000** [comment]
> Yes, git-ftp does that. You need a file .git-ftp-include.

very interesting, mean that we can ignore only for pull but authorize for push

**Comment by pereiradiogo** [comment]
> I imagine that your vendor folder is your .gitignore file, right? So it is not part of your git repository. You can just go in that directory and track it with git:
> 
> ```shell
> cd vendor
> git init
> git add .
> git commit -m "Initial set of vendor packages"
> git ftp init example.com/project/vendor
> ```
> 
> When ever you push your changes from your main repository, you can also do:
> 
> ```shell
> cd vendor
> git ftp push
> ```
> 
> If you are not the only person to push the vendor folder to the server, you need to share that Git repository with the other people as well.

This only works in the first usage.
