### ISSUE TITLE
git ftp init/push can't upload submodules. uploads an empty file instead of whole submodule

### ISSUE THREAD

**Issue by tuffz** [git-ftp/git-ftp#198]
This affects all versions over 0.9.0.

output in verbode mode where the submodules should upload:
curl: (18) Uploaded unaligned file size (0 out of 611 bytes)
curl: (18) Uploaded unaligned file size (0 out of 611 bytes)
curl: (18) Uploaded unaligned file size (0 out of 611 bytes)
curl: (18) Uploaded unaligned file size (0 out of 611 bytes)
curl: (18) Uploaded unaligned file size (0 out of 611 bytes)

**Comment by tfroehlich** [comment]
:+1:

**Comment by nubek** [comment]
:+1:

**Comment by dariusj18** [comment]
Bump, I bet this is somehow related to the name of the submodule's folder, for instance, my folder's name has bracket "[foldername]"

**Comment by tuffz** [comment]
My submodule paths named as following:

- app/Plugin/Marketplace
- app/Plugin/Migrations
- app/Plugin/Search
- app/Plugin/Users
- app/Plugin/Utils

**Comment by mabhub** [comment]
:+1:

A bisect run show that this bug was introduce by 9863c9356d157742775d5398c236b7e336f87459

I'll look a bit further to find out if i'm able to fix that..

**Comment by Thomas-Lebeau** [comment]
:+1:

**Comment by mkllnk** [comment]
@tuffz Not sure if you are still following the conversation. A fix got merged. If that isn't fixing your problem, please re-open this issue.

**Comment by tuffz** [comment]
Thanks a lot :+1:

**Comment by lingo** [comment]
I'm seeing this behavior, with the curl warning too, in version 1.2.0-rc.1

**Comment by JefferyHus** [comment]
```php
[1 of 119] Buffered for upload 'Controllers/CaptchaController.php'.
[2 of 119] Buffered for upload 'Core/Crawler/Crawlers.php'.
[3 of 119] Buffered for upload 'Core/Crawler/Exclusions.php'.
[4 of 119] Buffered for upload 'modules/index.php'.
[5 of 119] Buffered for upload 'modules/php/edna'.
Uploading ...
curl: Can't open './modules/php/edna'!
curl: try 'curl --help' or 'curl --manual' for more information
fatal: Could not upload files., exiting...
```

I am still getting this error from curl

**Comment by mkllnk** [comment]
Can you outline your directory structure? Do you have read permissions on that file?

**Comment by JefferyHus** [comment]
About permissions all files were 777, and the structure is like so:
- modules
  -- php
     --- edna
          ---- .... files

**Comment by mkllnk** [comment]
@JefferyHus Can you open a new issue?

It would be good to know which version of Git-ftp you use, which operating system and which shell. From your posts I take that `modules/php/edna` is a directory containing a Git submodule. Somehow Git-ftp thinks that it is a file. Do you use the syncroot option? Can you point me to a public Git repository that shows this bug?
