### ISSUE TITLE
Hangs on uploading

### ISSUE THREAD

**Issue by paddelboot** [git-ftp/git-ftp#200]
Sometimes the upload process seems to take forever, it hangs on "uploading..." and then I notice in my system panel that there is no upstream anymore.

I hope this can be fixed, because I love this tool.

Ubuntu 14.04
git version 1.9.1
git-ftp version 1.0.2

**Comment by resmo** [comment]
hi @paddelboot first I would try to use it `--vv` if you see anything suspicious. 

We often see hosting providers blocking uploads after several ftp connections within a short period of time. git-ftp tries to open as less sessions as possible but sometimes even this is to much for hosting providers. Were it a lot of files? how much "uploading..." did you see before it happened?

**Comment by paddelboot** [comment]
It was more than 1000 files (bower packages).

I tried the -A parameter the the upload finished. Will try --vv next time. Thanks again.

**Comment by resmo** [comment]
as a workaround you can use a different FTP client and use `git-ftp cachtup`
