### ISSUE TITLE
'git ftp init ...' fails when there is a space in the syncroot path

### ISSUE THREAD

**Issue by shooftie** [git-ftp/git-ftp#201]
```git ftp init -u [user] -p [password] sftp://domain/dir/ --syncroot "www/sub dir"```

This results in a .git-ftp.log file are being written to ```domain/dir/```, however, nothing else is uploaded.

It claims that there is just one file to upload which appears to be the log file.

I've tried ```+``` and ```%20``` instead of spaces but no luck. This does work when ```www/sub dir``` is changed to ```www/subDir``` but this is not possible in my case.

**Comment by mkllnk** [comment]
Can you run it with the `-vv` option again and post the output (without your password)? Which OS are you using?

**Comment by shooftie** [comment]
Give a couple of days... I've moved on with the project that I was on when I ran into this and now am snowed under... Thanks for getting back to me though.

**Comment by shooftie** [comment]
Typically I cannot recreate this bug... Sorry for the bother
