### ISSUE TITLE
Error - fatal: /: '/' is outside repository

### ISSUE THREAD

**Issue by tarsislima** [git-ftp/git-ftp#202]
This is returned when I run 'git ftp push'

```git ftp push
Unknown SHA1 object, make sure you are deploying the right branch and it is up-to-date.
Do you want to ignore and upload all files again? [y/N]: y```
**fatal: /: '/' is outside repository**
```There are no files to sync.
Last deployment changed to 372966b15e8df65b0c6a540eb97ce63870f43aa7.```

**Comment by resmo** [comment]
what version (if development branch, give commit id)? what os?

**Comment by json-uk** [comment]
I have this issue as well. I'm using the latest 1.1.0.rc.1.

**Comment by mkllnk** [comment]
Thanks @json-uk. Do you use Windows, Mac or Linux? Can you give the output of running git-ftp with `-vv`? That would be great help.

**Comment by mkllnk** [comment]
There was no update on this issue for a long time. It could be that the syncroot was set to `/` or that the `.git-ftp-include` file contained `/`. I can't tell without further information. I'm closing this for now.
