### ISSUE TITLE
.git-ftp-include is being ignored

### ISSUE THREAD

**Issue by NadavSyon** [git-ftp/git-ftp#203]
Hi,

I'm using git-ftp on my Win7 machine with msysgit. Everything is working fine except `.git-ftp-include`. It is just being ignored completely.

At first I used git-ftp in an existing project, so I decided to create a fresh git repo to test this out, but everything which is in `.git-ignore` won't upload no matter what I put inside the include file.

in my `.git-ignore` I have
```
vendor/
```
and in `.git-ftp-include`
```
vendor/:composer.lock
```
I have tried `!vendor/` as well.

I've tried this with simple files in the root dir as well, but just nothing works.

**Comment by resmo** [comment]
git-ftp version?

**Comment by mkllnk** [comment]
@NadavSyon Can you try the newest release 1.1.0? That problem should be solved. Including whole directories was added very recently and version 1.1.0 is the first release supporting that.

**Comment by andypillip** [comment]
Hei hei.

I got the same issue on linux with version 1.1.0.

I'm using compass and my .git-ftp-include is

   !_theme/css
