### ISSUE TITLE
authetication error

### ISSUE THREAD

**Issue by davicho** [git-ftp/git-ftp#208]
Hi,

Long story short.... we switched from regular ftp to sftp (two diff machines). I am having trouble with simple commands like "git ftp push" on the sftp box (it worked fine on the ftp box). Tried to push, then init then sync/catchup or do any command. Here is an example since "push" or init was working. Oddly enough this works (puts the log file on the remote):
```
git ftp init -u user -p 'xxxxx' -vv sftp://clientname.com:8888/var/www/html/website/
```

but when doing the "regular" command it doesn't:

```
$ git ftp catchup -vv
Tue Aug  4 22:41:53 EDT 2015: Host is 'clientname.com:8888'.
Tue Aug  4 22:41:53 EDT 2015: User is 'user'.
Tue Aug  4 22:41:53 EDT 2015: Password is set.
Tue Aug  4 22:41:54 EDT 2015: Path is 'var/www/html/website/'.
Tue Aug  4 22:41:54 EDT 2015: Syncroot is ''.
Tue Aug  4 22:41:54 EDT 2015: The remote sha1 is saved in file '.git-ftp.log'.
Tue Aug  4 22:41:54 EDT 2015: CACert is ''.
Tue Aug  4 22:41:54 EDT 2015: Insecure is ''.
Tue Aug  4 22:41:54 EDT 2015: Check if sftp://clientname.com:8888/var/www/html/website/ is accessible.
*   Trying xxx.xx.xxx.xxx...
* Connected to clientname.com (xxx.xx.xxx.xxx) port 8888 (#0)
* SSH MD5 fingerprint: xxxxxxxxxxxxxxxxxxxxx
* SSH authentication methods available: publickey,gssapi-with-mic,password
* Using SSH public key file '(nil)'
* Using SSH private key file '/Users/me/.ssh/id_rsa'
* SSH public key authentication failed: Unable to extract public key from private key file: Wrong passphrase or invalid/unrecognized private key file format
* No identity would match
* Authentication failure
* Closing connection 0

curl: (67) Authentication failure
Tue Aug  4 22:41:57 EDT 2015: fatal: Can't access remote 'sftp://clientname.com:8888/var/www/html/website/'., exiting...
Tue Aug  4 22:41:57 EDT 2015: fatal: Could not upload., exiting...
```

Any ideas? I have exhausted all internet leads. Thanks in advance.

**Comment by mkllnk** [comment]
Can you try to access your sftp server with curl?
```
curl sftp://clientname.com:8888/var/www/html/website/
```

Does that work?

Is it right that you use public/private key authentication?

And do you use a passphrase or your private key or not?

**Comment by mkllnk** [comment]
This issue is quite old. Feel free to open it again with some more information about your case.

**Comment by peter279k** [comment]
I had the same problems and error output, too.
After tracing the log, I found my password is incorrect.
After I set the correct password, the ```git-ftp``` worked fine.
