### ISSUE TITLE
Fails on some files (and not finishes upload?)

### ISSUE THREAD

**Issue by iamvitali** [git-ftp/git-ftp#212]
Hi,
I've noticed curl is failing on some of the files and the whole upload does not finish completely.

The curl.exe process disappears from the task manager eventually and the uploading is not finished. Though it doesn't look like the command line execution fails completely (it would otherwise end the execution which doesn't look like is happening).
edit: btw it looks like curl.exe appeared again, we'll see if it finishes the work.

P.S. Is it possible to turn on the complete log, to see which files are being uploaded?

Log:
... long list blah blah...
[3196 of 3197] Buffered for upload 'trade.reset.php'.
[3197 of 3197] Buffered for upload 'trade.work.survey.php'.
Uploading ...
curl: Can't open './file/Expert Advice 303242302200302223 How to keep the burgla
rs out (1).pdf'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/Expert Advice 303242302200302223 How to keep the burgla
rs out.pdf'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/What locks do I have 303242302200302223 PVCu Doors.pdf'
!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/What locks do I have 303242302200302223 Timber Doors.pd
f'!
curl: try 'curl --help' or 'curl --manual' for more information

**Comment by iamvitali** [comment]
So it actually eventually finished uploading but it didn't create the git-ftp file on the server, so I cannot do a git-ftp push and instead will need to do init again.

Log:
[3196 of 3197] Buffered for upload 'trade.reset.php'.
[3197 of 3197] Buffered for upload 'trade.work.survey.php'.
Uploading ...
curl: Can't open './file/Expert Advice 303242302200302223 How to keep the burgla
rs out (1).pdf'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/Expert Advice 303242302200302223 How to keep the burgla
rs out.pdf'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/What locks do I have 303242302200302223 PVCu Doors.pdf'
!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/What locks do I have 303242302200302223 Timber Doors.pd
f'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/Expert Advice 303242302200302223 How to keep the burgla
rs out (1).pdf'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/Expert Advice 303242302200302223 How to keep the burgla
rs out.pdf'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/What locks do I have 303242302200302223 PVCu Doors.pdf'
!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/What locks do I have 303242302200302223 Timber Doors.pd
f'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/Expert Advice 303242302200302223 How to keep the burgla
rs out (1).pdf'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/Expert Advice 303242302200302223 How to keep the burgla
rs out.pdf'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/What locks do I have 303242302200302223 PVCu Doors.pdf'
!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open './file/What locks do I have 303242302200302223 Timber Doors.pd
f'!
curl: try 'curl --help' or 'curl --manual' for more information
Last deployment changed to 056e88f98aa8452ce3cae95b666f1a6c131baf04.

C:\inetpub\wwwroot\_repos\%WEBSITE_NAME_REMOVED%>

**Comment by iamvitali** [comment]
The files above had a special character in the name I believe:
Expert Advice â How to keep the burglars out (1).pdf
Expert Advice â How to keep the burglars out.pdf
What locks do I have â PVCu Doors.pdf
What locks do I have â Timber Doors.pdf

**Comment by mkllnk** [comment]
Okay, it looks like the special character is encoded in some way and that encoding is lost somewhere. GitHub doesn't display the special character either. Can you describe it somehow? Do you know if it is a UTF-8 character and which number it has?

**Comment by mkllnk** [comment]
Can you run `git ls-files` and see how the file names are displayed there?

**Comment by pinchukd** [comment]
i think this bug is like https://github.com/git-ftp/git-ftp/issues/209

**Comment by mkllnk** [comment]
Closing this in favour of #209.
