### ISSUE TITLE
Pushing to multiple servers

### ISSUE THREAD

**Issue by Alghamdi** [git-ftp/git-ftp#213]
Is it possible to push to multiple ftp accounts? I mean like setting up multiple ftp account at `config` and then when `git ftp push` goes and upload to my accounts one by one.

**Comment by mkllnk** [comment]
No, that's not possible at the moment. You can configure multiple ftp servers in separate scopes. You still have to call `git ftp push -s <scope>` for each server.

**Comment by Alghamdi** [comment]
Thanks @mkllnk for your prompt reply :)
