### ISSUE TITLE
git-ftp stopped working after git application upgrade

### ISSUE THREAD

**Issue by vikaskhunteta** [git-ftp/git-ftp#214]
Recently I upgraded git application from version 1.9.4-32 bit Windows to version 2.5.2.windows.2

After this when I run `git ftp push` command into my project repository I got this error message
git: 'ftp' is not a git command.

I also pulled latest commits into git-ftp repository thought that it will fix the problem but still `ftp` command not working.

How can I fix this problem?

**Comment by vikaskhunteta** [comment]
Applying these commands again fixed the issue

`$ cd git-ftp && chmod +x git-ftp`
`$ cd /bin`
`$ ln -s ~/git-ftp/git-ftp`

**Comment by mkllnk** [comment]
Thank you for creating **and** solving this issue!

**Comment by VitaliyAT** [comment]
what about windows users? we have not chmod

**Comment by vikaskhunteta** [comment]
The issue was on Windows platform. To know about `chmod` command, open **git bash** and write

`chmod --help`
