### ISSUE TITLE
git ftp pull

### ISSUE THREAD

**Issue by RyanHipkiss** [git-ftp/git-ftp#216]
This repo is great, it solves a lot of problems I'm having with needing quick uploads etc. 

What would be great though, is it would be perfect if it had a git ftp pull option, 
whereby it pulled down any remote changes and merged them into my repo. 

Is this a possibility? Cheers.

**Comment by mkllnk** [comment]
Yes, checkout the [pull branch](https://github.com/git-ftp/git-ftp/tree/pull). It is not merged into the main version yet, but I will start on that soon.
