### ISSUE TITLE
Pull Branch - Issue?

### ISSUE THREAD

**Issue by RyanHipkiss** [git-ftp/git-ftp#217]
As soon as I cloned down the pull branch, whenever I used push or init commands...

the ftp blocks me from using it for whatever reason. I get a 421 service unavailable error.

**Comment by mkllnk** [comment]
Cool, thank you for this report. It's really good to know about issues before merging that into the main branch. :-)

Can you gather some more information for us? That would be great.

* Which operating system do you use?
* Can you post a filtered version of the output running git-ftp with `-vv`? (filter your credentials)
* Does the *download* branch work for you?

**Comment by mkllnk** [comment]
It has been a while and I got no further complaints even though that branch got merged into the develop branch. So maybe you ran into an old bug while the pull branch wasn't merged. I'm closing this for now, but feel free to open it if the problem persists.
