### ISSUE TITLE
Delete folders

### ISSUE THREAD

**Issue by AmmarAbuQoura** [git-ftp/git-ftp#218]
Hello, 
when i delete a folder form the original project i notice that the it;s not deleted form the ftp server just all the files inside this folder is deleted 

also if you can plz provide me with small script that i can use as add hock to the sourcetree program to auto push the changes to the ftp after pushing them to the githup

**Comment by mkllnk** [comment]
Hi!

Unfortunately, we had to deactivate the deletion of empty directories, because some servers delete the directory even if there are other files in there.

And sorry, I'm not familiar with Sourcetree and can't provide a plugin.
