### ISSUE TITLE
Enhancement: Upload first, delete later on rename/move

### ISSUE THREAD

**Issue by karol-haltenberger** [git-ftp/git-ftp#222]
I've noticed, that pushing git renames causes the old files to be deleted first and then uploaded to the new location/name later.

I can imagine this creating issues if the push fails for some reason and the files don't get uploaded.
In case the push fails before deleting the old files and the duplicates cause an issue, it is still easier to delete them than to upload the missing ones.

edit: git-ftp version 0.9.0

**Comment by mkllnk** [comment]
Thank you for opening this issue. It will help others wondering about the same.

But fortunately, that has changed in more recent versions already. Now it's first uploading and then deleting.
