### ISSUE TITLE
Support Non-Paired Includes

### ISSUE THREAD

**Issue by jehoshua02** [git-ftp/git-ftp#224]
We would love to see support for non-paired includes.

Example `.git-ftp-include`:

```
./build/style.css
```

**Comment by bmounteer** [comment]
Also, even just having the ability to watch a tracked directory instead of a specific file. 

Example:
```
wp-content/themes/lendio-standards/stylesheets/styles.min.css:wp-content/themes/lendio-standards/scss/**/*.scss
```

**Comment by mkllnk** [comment]
Look at version 1.1.0. It supports unpaired inclusion of files:
```
!build/style.css
```

@bmounteer: True, that would be nice. Would you like to open a new issue for that? Pull requests are welcome as well. :-)

**Comment by jehoshua02** [comment]
@mkllnk We installed via brew:

```
brew install git-ftp
```

And looks like we are on an older version:

```
~
$ git ftp --version
git-ftp version 1.0.2
```

**Comment by jehoshua02** [comment]
I've got the latest version. Giving it a go. I'll report back when I'm done.

**Comment by jehoshua02** [comment]
It worked! Strange to prefix an include with `!` (negation character), but it works! Thanks.

**Comment by mkllnk** [comment]
> Strange to prefix an include with ! (negation character)

Yeah, that symbol is a bit overloaded. For example, in CSS you have the `!important` annotation.

The most clear way would be to omit the colon for pairing or have wildcards:
```
# This is not supported!
build/style.css:*
```

Maybe someone feels like having fun implementing that?
