### ISSUE TITLE
parsing error in add-scope causes "multiple colons" error

### ISSUE THREAD

**Issue by pnNRklgzBr** [git-ftp/git-ftp#226]
a parsing error in dissection of URL into protocol and credentials in add-scope function causes the following error:
> print_info "Warning, multiple ':' characters detected, only URL was set in scope."
> print_info "Use --user and --passwd options to set login and password respectively."

even when used with a valid URL like in 
$ git-ftp add-scope xyz  ftpes://user:password@ftp.example.com/xyz

**Comment by mkllnk** [comment]
Thanks for that. I added a unit test checking this issue to a new branch. Once the CI tests are passed, I will merge your pull request. Good work.
