### ISSUE TITLE
Possibile conflict when setting password that contains the '$' character

### ISSUE THREAD

**Issue by Civile** [git-ftp/git-ftp#228]
Hi, i'm facing a problem while setting a password that contains the dollar character $. 

When i set the password using the command git config git-ftp.password demo$password the string is cut at the character in question, the dollar. The same if i wrap the string in double quotes.

So, setting "demo$password", the result inside the config file is: "demo"

Is it possibile to fix it? Can i help you? 
Thanks

**Comment by TechCtrl** [comment]
Do you have your password in quotes?  Try double and single quotes.
Have you tried escaping the $ sign?
Let us know what you have tried.

**Comment by mkllnk** [comment]
Yes, you have two possibilities to set that password via `git config`:

```sh
git config git-ftp.password 'demo$password'
# - or -
git config git-ftp.password "demo\$password"
```

**Comment by tuffz** [comment]
+1
@mkllnk thanks ;)

**Comment by Civile** [comment]
I had tried: "demo$password" without escaping with the backslash.

@mkllnk  Yes it works, thanks

**Comment by sgtcoder** [comment]
> Yes, you have two possibilities to set that password via `git config`:
> 
> ```shell
> git config git-ftp.password 'demo$password'
> # - or -
> git config git-ftp.password "demo\$password"
> ```

Please put this in the documentation. Preferably the single quotes since that works best.
