### ISSUE TITLE
Reading what is currently set in the defaults

### ISSUE THREAD

**Issue by woodsy1** [git-ftp/git-ftp#229]
Hi,
I cannot seem to work out how to read what is set in the defaults.
I am particularly interested in how the branching works. It is set to some default and I am not sure what and how it was determined as I didnt set it.

**Comment by mkllnk** [comment]
If you want to list all options set by git config:

    git config -l

But I'm not sure what you mean by branching.

**Comment by woodsy1** [comment]
I mean that I didn't set which branch I want to push but it seems to just
push maybe master by default?

**Comment by mkllnk** [comment]
It is pushing the version you have currently checked out (`HEAD`). If you want to push master:
```sh
git checkout master
git ftp push
```

**Comment by woodsy1** [comment]
Yea OK. so what is the -branch even used for then? I think the idea situation would be to able to dev and code locally and commit etc but then it only pushes what has been merged back into the master branch (so you could have changes locally that arent pushed to the server!)

**Comment by mkllnk** [comment]
Oh, if you use the newest version of git-ftp, then there is the `--branch` option. That will do the checkout for you. But you have to provide the branch name on the command line or via git config.
```sh
git ftp push --branch master

# - or -
git config git-ftp.branch master
git ftp push
```

The commands above are equivalent to the following commands:
```sh
git checkout master
git ftp push
git checkout <previous_branch>
```

Does that work for you?
