### ISSUE TITLE
Has trouble with files with number signs in name.

### ISSUE THREAD

**Issue by donut** [git-ftp/git-ftp#23]
I used `git ftp push` to delete and add some files with number signs in their names over SFTP. The files that it tried to remove were not removed and the files uploaded with it changed their names.

For example, the file "#4253-Release Contest.md" was supposed to be removed but was not. And the file "v1.2.0 #8950 - Custom Partner Player.md" was uploaded as "v1.2.0".

git version 1.7.9.5
git-ftp version 0.8.4

**Comment by mkllnk** [comment]
Thanks a lot for reporting this. It should be fixed in the newest version.
