### ISSUE TITLE
Unnecessary new lines

### ISSUE THREAD

**Issue by vikaskhunteta** [git-ftp/git-ftp#233]
Thanks for this superb application.

I have one issue regarding files formatting. After successful upload if I download the file using FTP, the downloaded file has unnecessary new lines after each line with text.

For e.g. 
```
<?php

echo "Some text";
echo "Another text";
?>
```
becomes
```
<?php


echo "Some text";

echo "Another text";

?> 
```

Let me know if there is a solution already available, if not than please fix this. Because for large files it increase the size and also the formatting looks weird.

Regards

**Comment by mkllnk** [comment]
Hi Vikas,

Thanks for your feedback. Do you see the increased file size on the server or only when you download a file?

It might be that your FTP client is converting newlines during download. Try to change that setting in you FTP client.

Windows, Mac and Unix use different characters at the end of each line. And someone had the great idea to convert the line endings when transferring over FTP. Unfortunately, that goes wrong quite often and leads to the problem you have at the moment. Can you find out, if the files are changed during upload with git-ftp or during download with your FTP client? It might also be interesting which operating system you use and which operating system the FTP server uses.

But as far as my research went, `curl` does not change line endings. And git-ftp uses curl to upload files.

**Comment by vikaskhunteta** [comment]
Hello,

Thanks for prompt reply.

No, file size do not increase on the server. The problem is only when I download file using using FTP client.

When I upload the file using FTP client, the uploaded file is smaller in size but when I upload using git-ftp, file size is same.

for e.g.

I have one file whose size is 17,636 Bytes when I upload using FTP client the uploaded file size is 17,210 Bytes but with git-ftp file size is same.

According to me the problem occurs when I download the file using FTP client because with cPanel code editor there is no change in formatting, I mean no new lines added.

I am using FileZilla latest version on Windows 7 Ultimate 64 bit.

I don't know which setting needs to be changed in FileZilla. So Please help me to fix this problem.

Regards
Vikas

**Comment by mkllnk** [comment]
> In FileZilla 2.2.32, go Edit > Settings > File transfer settings > ASCII/Binary. Set it to always binary: that should do the trick.
> 
> In FileZilla 3.5.0 the setting is in Edit > Settings > Transfers > File Types > Default transfer type > Binary.

From: http://stackoverflow.com/a/555003/3377535

Does that work?

**Comment by vikaskhunteta** [comment]
Thanks,

It worked. I should have searched for this problem before creating an issue.

Once again thank you very much.

Regards
Vikas
