### ISSUE TITLE
File upload fails: no connection on port 21 ??

### ISSUE THREAD

**Issue by paddelboot** [git-ftp/git-ftp#235]
`curl: (7) Failed to connect to xxxx.de port 21: Verbindungsaufbau abgelehnt
Do 28. Jan 21:31:13 CET 2016: fatal: Could not upload file: 'wp-content/themes/enfold-child/.git-ftp.log'., exiting...
`

Is this a remote server issue and if so, is there a workaround?

Still an excellent script.

**Comment by mkllnk** [comment]
That looks like the server blocked your connection. It might be that you are limited to a certain number of connections per minute. Using the verbose options `-v` or `-vv` can give you more insights about the server response.

The file `.git-ftp.log` is the last file uploaded. It contains the commit id. If everything else is uploaded already, you can just upload that one file with `git ftp catchup`.
