### ISSUE TITLE
Update Ubuntu PPA ?

### ISSUE THREAD

**Issue by phenix-factory** [git-ftp/git-ftp#237]
Hello,
Version 1.1.0 is out since some month now but the ppa resmo/git-ftp doesn't provide it.
Could you update this PPA ? Or the official repository ?

Thank you !

**Comment by mkllnk** [comment]
That's still done by @resmo. Do you have time to do it?

**Comment by resmo** [comment]
No. no time sorry :(

**Comment by mkllnk** [comment]
I created a new PPA with the newest release:

    sudo add-apt-repository ppa:git-ftp/ppa
