### ISSUE TITLE
Buffering restarts/fails when thousands of files (or problem with a particular file?)

### ISSUE THREAD

**Issue by vatnoise** [git-ftp/git-ftp#242]
Hi,
Usually everything works smoothly but I have a website to upload that has ~40000 files. And it doesn't look like it finishes its buffering.

So this is what happens:

```
Fetching origin
HEAD is now at 83fea5b testing
Wed Feb 24 16:08:00 GMTST 2016: Host is 'ftpip:ftpport'.
Wed Feb 24 16:08:00 GMTST 2016: User is 'ftpuser'.
Wed Feb 24 16:08:00 GMTST 2016: Password is set.
Wed Feb 24 16:08:01 GMTST 2016: Path is 'httpdocs/'.
Wed Feb 24 16:08:01 GMTST 2016: Syncroot is ''.
Wed Feb 24 16:08:01 GMTST 2016: The remote sha1 is saved in file '.git-ftp.log'.
Wed Feb 24 16:08:01 GMTST 2016: CACert is ''.
Wed Feb 24 16:08:01 GMTST 2016: Insecure is ''.
Wed Feb 24 16:08:01 GMTST 2016: Retrieving last commit from ftp://ftplogin:ftppassword@ftpip:ftpport/httpdocs/.
Wed Feb 24 16:08:01 GMTST 2016: Last deployed SHA1 for ftpip:ftpport/httpdocs/ is b3c8275db7488f6a09381c8636fe92feba2b42a7.
Wed Feb 24 16:09:02 GMTST 2016: Having files to sync.
Wed Feb 24 16:09:02 GMTST 2016: There are 41700 files to sync:
Wed Feb 24 16:09:02 GMTST 2016: [1 of 41700] Buffered for upload '.git-ftp.log'.
Wed Feb 24 16:09:02 GMTST 2016: [2 of 41700] Buffered for upload '.htaccess'.
....
Wed Feb 24 17:16:40 GMTST 2016: [15952 of 41700] Buffered for upload 'wp-content/uploads/2015/03/Recy_0064_300x400N-580x282.jpg'.
Wed Feb 24 17:16:41 GMTST 2016: [15953 of 41700] Buffered for upload 'wp-content/uploads/2015/03/Recy_0064_300x400N-580x580.jpg'.
Wed Feb 24 17:16:41 GMTST 2016: [15954 of 41700] Buffered for upload 'wp-content/uploads/2015/03/Recy_0064_300x400N-580x773.jpg'.
: [15955 of 41700] Buffered for upload 'wp-content/uploads/2015/03/Recy_0064_300x400N-580x878.jpg'.
: [15956 of 41700] Buffered for upload 'wp-content/uploads/2015/03/Recy_0064_300x400N-768x1024.jpg'.
: [15957 of 41700] Buffered for upload ''.
Wed Feb 24 17:16:45 GMTST 2016: Host is 'ftpip:ftpport'.
Wed Feb 24 17:16:46 GMTST 2016: User is 'ftpuser'.
Wed Feb 24 17:16:46 GMTST 2016: Password is set.
Wed Feb 24 17:16:46 GMTST 2016: Path is 'httpdocs/'.
Wed Feb 24 17:16:46 GMTST 2016: Syncroot is ''.
Wed Feb 24 17:16:46 GMTST 2016: The remote sha1 is saved in file '.git-ftp.log'.
Wed Feb 24 17:16:46 GMTST 2016: CACert is ''.
Wed Feb 24 17:16:46 GMTST 2016: Insecure is ''.
Wed Feb 24 17:16:46 GMTST 2016: Check if ftp://ftpuser:ftppassword@ftpip:ftpport is accessible.
Wed Feb 24 17:16:47 GMTST 2016: Check if ftp://ftpuser:ftppassword@ftpip:ftpport/httpdocs/ is clean.
Wed Feb 24 17:16:47 GMTST 2016: fatal: Commit found, use 'git ftp push' to sync. Exiting...
```

P.S. Using 1.1.0-UNRELEASED
2P.S. Seems like buffering takes some time as well but this is probably expected?

**Comment by mkllnk** [comment]
Did you try `git ftp push` or `git ftp init -f`? Just because your error message says that a commit was found already.

The weird thing is that there is an empty file buffered:

     : [15957 of 41700] Buffered for upload ''.

Are there more of these? What does `git ls-files` tell you around line 15957?

Sorry to ask all these questions, but it's difficult to reproduce the error without the same data you have. Is it open source? Do you use Linux?

**Comment by vatnoise** [comment]
I have installed 1.2.0-UNRELEASED now.

Results slightly changed, now it shows the file name:

    Fri Feb 26 13:39:34 GMTST 2016: [15953 of 41700] Buffered for upload 'wp-content/uploads/2015/03/Recy_0064_300x400N-580x580.jpg'.
    Fri Feb 26 13:39:34 GMTST 2016: [15954 of 41700] Buffered for upload 'wp-content/uploads/2015/03/Recy_0064_300x400N-580x773.jpg'.
    : [15955 of 41700] Buffered for upload 'wp-content/uploads/2015/03/Recy_0064_300x400N-580x878.jpg'.
    : [15956 of 41700] Buffered for upload 'wp-content/uploads/2015/03/Recy_0064_300x400N-768x1024.jpg'.
    : [15957 of 41700] Buffered for upload 'wp-content/uploads/2015/03/Recy_0064_300x400N-800x200.jpg'.

> Did you try git ftp push or git ftp init -f? Just because your error message says that a commit was found already.

Whoops, shouldn't have put that here. In my script if **git ftp push** fails it does **git ftp init**, that's how it determines whether it's the first ftp push ... by trying. :)
So in this case it was doing buffering with git ftp push but for some reason that failed and so my script just run git ftp init straight after (and that obviously failed as well because this is not the first push).

> Are there more of these? What does git ls-files tell you around line 15957?

    ....
    wp-content/uploads/2015/03/Recy_0064_300x400N-540x720.jpg
    wp-content/uploads/2015/03/Recy_0064_300x400N-580x282.jpg
    wp-content/uploads/2015/03/Recy_0064_300x400N-580x580.jpg
    wp-content/uploads/2015/03/Recy_0064_300x400N-580x773.jpg
    wp-content/uploads/2015/03/Recy_0064_300x400N-580x878.jpg (stops showing date starting from this file)
    wp-content/uploads/2015/03/Recy_0064_300x400N-768x1024.jpg
    wp-content/uploads/2015/03/Recy_0064_300x400N-800x200.jpg (this is the last file to buffer from the log)
    wp-content/uploads/2015/03/Recy_0064_300x400N-800x400.jpg
    wp-content/uploads/2015/03/Recy_0064_300x400N-90x90.jpg
    wp-content/uploads/2015/03/Recy_0064_300x400N.jpg
    wp-content/uploads/2015/03/Recy_0064_600x200T-100x100.jpg
    wp-content/uploads/2015/03/Recy_0064_600x200T-100x33.jpg
    wp-content/uploads/2015/03/Recy_0064_600x200T-150x150.jpg
    wp-content/uploads/2015/03/Recy_0064_600x200T-158x158.jpg
    wp-content/uploads/2015/03/Recy_0064_600x200T-250x250.jpg
    ....

> Sorry to ask all these questions, but it's difficult to reproduce the error without the same data you have. 

That's understandable. :)

> Is it open source?

Unfortunately, it's closed-source project (although we use WordPress as a base).

> Do you use Linux?

Windows Server 2012 R2 Standard x64

**Comment by mkllnk** [comment]
This is a very weird behaviour. From that output I would guess that your shell runs out of memory or has some other limitations. It's just a loop printing file names with the same command. It prints the date with a sub-shell command: `$(date)`. Maybe there is a limit on the number of sub-shell commands that can be called from one script. Maybe it doesn't close the sub-shell properly leaving a memory leak. I don't know. But it doesn't look like an error within git ftp.

I will run more tests on the script, but my best guess is a limitation in msysgit.
