### ISSUE TITLE
First commit - do I have to upload all files?

### ISSUE THREAD

**Issue by etech0** [git-ftp/git-ftp#243]
I just downloaded my site to work on it locally, and am setting up git-ftp to upload changes.

However, it wants me to upload every single file, even though they were not changed. (I downloaded the whole site via FileZilla and didn't change anything yet.)

Is there a way to tell it that right now, the remote is the same as the local, so that I don't have to upload all files for the first push?

Thanks!

**Comment by mkllnk** [comment]
Yes. `git ftp catchup`

**Comment by etech0** [comment]
Thanks! I tried running it and it told me 
Fatal: dirty repository: having uncommited changes. Exiting.

I committed my changes and tried again, and got the same error. Any advice?

Thanks!

**Comment by mkllnk** [comment]
Do you have any untracked files in your project? Can you run the following commands and paste the output?

```sh
echo "'_$(git status -uno --porcelain | wc -l)_'"
git status -uno --porcelain
```

Thank you.

**Comment by etech0** [comment]
Thanks! I ran those lines (no clue what they did), and got this:
M js/customjqueryfunctions.js

Then I committed that file, and ran both lines again, and this time didn't
get any output. So I ran git ftp catchup, and it said "last deployment
changed to ......................"

Does that mean I'm good?

Thanks!

**Comment by mkllnk** [comment]
Yes, git-ftp know that all your files are on the server. If you change any and commit the changes again, you can run `git ftp push` to update those files on the server. You just need a clean working directory for that. `git status` should not list any files.
