### ISSUE TITLE
Unknown SHA1 object, could not determine changed files, taking all files.

### ISSUE THREAD

**Issue by hantc** [git-ftp/git-ftp#244]
$ git ftp push
Unknown SHA1 object, make sure you are deploying the right branch and it is up-to-date.

Why this problem occurs? What is the cause? I'm deploying master branch.

**Comment by mkllnk** [comment]
That means that the server has a version of your project that is not in your Git repository. Did you push to that server from another computer before? Or did you have another project at the same place on the server?

Another rare possibility would be that you changed your commit history via `git rebase`, `git commit --amend` or similar commands and that Git's garbage collection deleted the old commit from your repository.

What you can do now:

- `git ftp push --force` uploads all files again.
- `git ftp push --commit $SHA1` assumes that `$SHA1` is the commit on the server. But you need to know which commit you deployed last. You can try an older one as well. You can take the commit id (SHA1) from your Git history `git log`.

**Comment by gavrochelegnou** [comment]
Had this problem before too when a coworker did an "ftp push" but forgot to do a "push".
It would be nice to have an option to enforce a "git push" before an "ftp push" to avoid those unclean states, the same way git-ftp refuses to push if repository is unclean it could refuse to ftp if not pushed to origin ?

**Comment by mkllnk** [comment]
I think it would be too much to enforce a *git push* before *git ftp push*. For example, I have projects without a remote. I never do *git push* on these. And if there are multiple remotes, people may want to push to another one than origin or to multiple ones. What do you think about a `pre-ftp-push` hook? You could easily do a *git push* in there.

**Comment by gavrochelegnou** [comment]
Yes `pre-ftp-push` and `post-ftp-push` would be awesome.
I always end up wrapping git ftp push inside another script to handle those calls, but having them natively would be great !
