### ISSUE TITLE
curl: (25) Failed FTP upload: 550

### ISSUE THREAD

**Issue by vatnoise** [git-ftp/git-ftp#246]
Hi, I've been just trying FTPES and because of that updated my curl from curl 7.41.0 (i386-pc-win32) (because it was not working) to curl 7.47.1 (x86_64-pc-win32).

And the first commit after that update went like this:

    C:\path\website>"C:\Program Files (x86)\Git\bin\curl.exe" --version
    curl 7.47.1 (x86_64-pc-win32) libcurl/7.47.1 OpenSSL/1.0.2g nghttp2/1.8.0
    Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
    Features: AsynchDNS Largefile NTLM SSL HTTP2

    C:\path\website>git ftp push --user USERNAME --passwd "PASSWORD" ftpes://ADDRESS:21/ -v
    Tue Mar  8 17:17:19 GMTST 2016: Host is 'ADDRESS:21'.
    Tue Mar  8 17:17:19 GMTST 2016: User is 'USERNAME'.
    Tue Mar  8 17:17:19 GMTST 2016: Password is set.
    Tue Mar  8 17:17:20 GMTST 2016: Path is ''.
    Tue Mar  8 17:17:20 GMTST 2016: Syncroot is ''.
    Tue Mar  8 17:17:20 GMTST 2016: The remote sha1 is saved in file '.git-ftp.log'.

    Tue Mar  8 17:17:20 GMTST 2016: CACert is ''.
    Tue Mar  8 17:17:20 GMTST 2016: Insecure is ''.
    Tue Mar  8 17:17:20 GMTST 2016: Retrieving last commit from ftp://USERNAME:***@ADDRESS:21/.
    ######################################################################## 100.0%
    Tue Mar  8 17:17:22 GMTST 2016: Last deployed SHA1 for ADDRESS:21/ is 4f9263640367fbcc01c9aee80c39ca83368a2cb1.
    Tue Mar  8 17:17:23 GMTST 2016: Having files to sync.
    Tue Mar  8 17:17:23 GMTST 2016: 2 files to sync:
    Tue Mar  8 17:17:23 GMTST 2016: [1 of 2] Buffered for upload 'includes/twitter/twitter-feed.cache'.
    Tue Mar  8 17:17:23 GMTST 2016: [2 of 2] Buffered for upload 'test.php'.
    Tue Mar  8 17:17:23 GMTST 2016: Uploading ...

    curl: (25) Failed FTP upload: 550
    ######################################################################## 100.0%
    Tue Mar  8 17:17:25 GMTST 2016: Uploading commit log to ftp://USERNAME:***@ADDRESS:21/.git-ftp.log.
    ######################################################################## 100.0%
    Tue Mar  8 17:17:25 GMTST 2016: Last deployment changed to 85c9ad92cee9dd14fd409ecdfd3e7fa22dc35e77.

So it did not upload the files above and after I did the next commit it simply ignored the above files comepletely (as if that upload was successful), however, all the commits that I make now are successfully uploaded! So I guess my request would be to try and catch the curl 25 error, so that it won't think that the upload is successful? Sorry for all that.

Thanks.

**Comment by mkllnk** [comment]
Ah, yes, that's a known issue (#9) and a problem of curl. Curl returns with a successful exit status (0) even if some of the files failed to upload. A pull request parsing curls stderr is welcome.

**Comment by mkllnk** [comment]
But thank you for reporting. It's always good to know which problems happen to more than one person.

**Comment by maxlyaptsev** [comment]
curl: (25) Failed FTP upload: 550
#=#=#                                                                         
##O#- #                                                                       
##O=#  #                                                                      
#=#=-#  #                                                                     
-#O#- #   #                                                                   
-=#=#   #   #                                                                 
-=O#- #  #    #                                                               
curl: (25) Failed FTP upload: 550
Wed Jul 18 08:04:32 UTC 2018: fatal: Could not upload files., exiting...

**Comment by marcellojordan** [comment]
this is ACL permission on the destination folder. 
Check if the user or group has permission to modify in the physical path.
it worked for me
