### ISSUE TITLE
How about pull from ftp ?

### ISSUE THREAD

**Issue by NourdineMazali** [git-ftp/git-ftp#248]
I see in the documentation that pull request is not mentioned, is it available on git-ftp?
Thanks

**Comment by mkllnk** [comment]
Do you mean to pull down changes from the FTP server?

That has been merged into the develop branch, but there is no release with the pull feature yet.

**Comment by mkllnk** [comment]
Release 1.2.0 contains the pull feature. It is documented in the help text of the program, but not in the man page. I think the documentation needs some attention.

**Comment by mkllnk** [comment]
I updated the documentation. Further pull requests are welcome.
