### ISSUE TITLE
download and pull not work Ubuntu

### ISSUE THREAD

**Issue by renat2985** [git-ftp/git-ftp#250]
Hello. Please tell me what is a problem?
```
git ftp download              
fatal: Action unknown.
```

**Comment by mkllnk** [comment]
You are probably not using the newest version of git-ftp. You can find it out with:

    git ftp version

If it's older than 1.2.0, you need a newer version to use that feature. You will also need lftp. How did you install git-ftp?

**Comment by renat2985** [comment]
Yes i'm use old version on Ubuntu PPA.
```
> git ftp version
git-ftp version 1.0.1
```
lftp installed.
Please update version on ppa.

**Comment by mkllnk** [comment]
I created a new PPA with the newest release:

    sudo add-apt-repository ppa:git-ftp/ppa
