### ISSUE TITLE
ln: failed to create symbolic link './git-ftp': No such file or directory

### ISSUE THREAD

**Issue by nicolasjuarezn** [git-ftp/git-ftp#253]
Hi i need help please:
In the new console GIT MINGW64 have this problem, i follow the steps.
$ cd ~
$ git clone https://github.com/git-ftp/git-ftp
$ cd git-ftp && chmod +x git-ftp
$ cd /bin
$ ln -s ~/git-ftp/git-ftp

But in the last step 
ln: failed to create symbolic link './git-ftp': No such file or directory

**Comment by nicolasjuarezn** [comment]
I solved this.
The problem is te root folder. I copy the files manually to git folder and them 
$ln -s ../git-ftp/git-ftp 
Works fine.

**Comment by mkllnk** [comment]
Thank you for reporting. I simplified the installation instructions for Windows.

**Comment by TechCtrl** [comment]
I know this is late to the party, but... FYI I just experienced this issue today installing git-ftp for GIT 2.16.0 on a new Windows 10 system and the problem for me was fixed by running Git Bash as Administrator.  When I did that the below code ran without issue. 

`ln -s ~/git-ftp/git-ftp`
