### ISSUE TITLE
Clarification on Limitations

### ISSUE THREAD

**Issue by danielnieto** [git-ftp/git-ftp#254]
Can anyone clarify me what does this mean, it's in the README: 

> git-ftp as deployment tool: git-ftp was not designed as centralized deployment tool. While running git-ftp, you have to take care, no one pushes or touches this repo (e.g. no commits, no checkouts, no file modifications)!

Does this mean that while git-ftp repo is uploading files you have to make sure that all files inside the local repo remain intact? or does it means that once you've pushed the files to the server no one can touch the files on the ftp server (ie. add, modify, delete)? What happens if someone touches this repo? Can you give me an example of this limitation?

Thanks!

**Comment by mkllnk** [comment]
Hi, thanks for bringing this up.

It means, you can't keep on working and change files while git-ftp uploads to the server. Once the upload finished. You can do whatever you want.

For example, if you change a file while git-ftp is uploading, that changed file might be uploaded. If you checkout another version, the newly checked out files will be uploaded. You will end up with wrong versions of the files on the server.

Do you have an idea how to describe that better?

**Comment by danielnieto** [comment]
I see, now I get it... I think my wording would be:

> git-ftp as deployment tool: git-ftp was not designed as centralised deployment tool. While a commit is being pushed and uploaded to the FTP server, all files belonging to that revision must remain untouched until git-ftp has successfully finished the upload. Otherwise, the contents of the uploaded file will not match the contents of the file referenced in the commit.

this is a great tool by the way, thanks for letting us have this :)

**Comment by mkllnk** [comment]
Thanks, your version is much better. I changed the readme file.
