### ISSUE TITLE
Is rollback possible?

### ISSUE THREAD

**Issue by lithstud** [git-ftp/git-ftp#257]
Is there any way to do a rollback to previous commit? I know there is no option at the moment but is there a workaround? 

Thanks

**Comment by mkllnk** [comment]
Sure:

```sh
git checkout <previous version>
git ftp push
```

**Comment by ArmandArthur** [comment]
It doesn't work for me.
When i do 

git checkout id_commit, git ftp push (no change on the server)
And
git checkout id2_commit, git ftp push (id_commit is uploaded on the server)

Why? please

**Comment by mkllnk** [comment]
What does `git diff --status id_commit id2_commit` say? The listed files should get uploaded.
