### ISSUE TITLE
Impossible to upload files from directories which names starts with a "-"

### ISSUE THREAD

**Issue by zemax** [git-ftp/git-ftp#259]
I have a directory which name is "-"
In 1.2.0 the printf line 968 in libexec/git-ftp (encode_hash function) interprets "-..." as a parameter, and so fails, and all files are uploaded in the root directory.
I know it's an edge case, but with 1.1.0 and before I had no problem uploading theses files.

BTW : Great work on git ftp, it quickly became a mandatory tool for me, making deployment over ftp a breeze ! Thanks !

**Comment by mkllnk** [comment]
Thank you for the report. I removed the encode_hash function on the develop branch and now use much faster bash substitution. Would you like to try the newest version?

**Comment by zemax** [comment]
Thank you, I've just tested it and it worked as expected, the files are pushed without any warning or errors.
