### ISSUE TITLE
Auto detect scope, from current branch

### ISSUE THREAD

**Issue by felixdrud** [git-ftp/git-ftp#261]
I'm using scopes to push to my development server, when i'm on my development branch. It would be nice if `git ftp push` could auto detect the current branch, and use the associated scope, so i don't have to use `git ftp push -s development`, each time.

**Comment by mkllnk** [comment]
Did you see `git ftp push -s` in the man page? You still have to add `-s`, but it should take your current branch. You can use an alias if you use it all the time:

    alias gfpush='git ftp push -s'
