### ISSUE TITLE
Error create symbolic

### ISSUE THREAD

**Issue by atmanegara** [git-ftp/git-ftp#262]
How fix 

> failed to create symbolic link ‘./git-ftp’: File exists

**Comment by mkllnk** [comment]
What are you trying to do? What did you do to get this error?

**Comment by atmanegara** [comment]
git bash via command administrator not work , nothing error only message failed to create symbolic link ‘./git-ftp’: File exists

**Comment by mkllnk** [comment]
I don't know the command administrator. But it sounds like it tries to install git-ftp while git-ftp is already installed. You can try to remove the file. Open the git bash and enter into the command line prompt:

    mv /bin/git-ftp /bin/git-ftp-original

Then try again.

**Comment by atmanegara** [comment]
it's work, thanks
