### ISSUE TITLE
Folder name with # at start

### ISSUE THREAD

**Issue by petrikjosef** [git-ftp/git-ftp#264]
I have problem... 

every ftp push upload structure of my file position with duplicity to FTP with # at start of name...

For example... push comit with change at www/templates/something.txt as #www/templates/something.txt...

Some ideas? Thaanks

**Comment by mkllnk** [comment]
Yes, it is a bug in your version of mingw32. Updating mingw32 should solve the problem. So it did for #256 and #258.
