### ISSUE TITLE
Seems to forget path

### ISSUE THREAD

**Issue by unlikenesses** [git-ftp/git-ftp#265]
In my git config I have

`url = [address]/../`

This is because the Fasthosts FTP address points to `htdocs`, and I want the root to be one level above (this level is accessible in Filezilla). On running `git ftp init`, this correctly pushed my files to the folder above `htdocs`. 

But now whenever I run `git ftp push` it pushes them to `htdocs`, i.e. it seems to ignore the `/../` at the end of my `url` config setting. Any ideas?

**Comment by mkllnk** [comment]
Did you change versions of git-ftp? The only difference between init and push is the selection of local files to upload. The upload mechanism is the same.

**Comment by unlikenesses** [comment]
I didn't. I wondered if it's a bug to do with using `/../` in the `url` path.

**Comment by LukasFritzeDev** [comment]
Is this still relevant?
Have you tried setting your remote path as `remote-root` instead of a part of the URL?

**Comment by LukasFritzeDev** [comment]
Looks like you have solved the issue in the meantime. We closed this issue for now but please feel free to re-open it if you still have this problem with Git-ftp.
