### ISSUE TITLE
git ftp download works wrong

### ISSUE THREAD

**Issue by kremnik** [git-ftp/git-ftp#266]
We have 3 problems with git ftp download:

1. First, we have empty folder. After, we make `git init`. Then we do git ftp download and after we get all the files from ftp server. But the downloaded site shows 500 error (Internal Server Error). But if we move content of this folder to the new one, it works from the new folder. We do nothing, but copy.

2. I have a local folder with my project, and it is `git init`. And I pushed these files to my ftp server with `git ftp push`. All OK. But when I did some changes to any files in ftp server directly, and after I did `git ftp download`, It downloads ALL the files, but not only changed. 

3. I work with my team, so when I pushed changes to our ftp server, and my mates did` git ftp pull`, they got ALL files, but not only changed.

**Comment by mkllnk** [comment]
Hi!

Your first issue sounds like a permission problem. File permissions depend on the operating system and git-ftp can't guess what's right for you. It may also be that the FTP server is changing the permissions of uploaded files. In that case, we can't help you.

Your second problem is a natural limitation of FTP. Git-ftp can not know which files changed on the server. It uses lftp's mirror command which tries to ignore unchanged files, but in doubt, it has to download them all. This feature is not meant to replace Git's push and pull features. You can't efficiently use it to synchronise a team. You should use a proper Git repository for that.

That also explains your third issue. Git-ftp is not intended to be used like that. I know, it would be cool, but we can't do that.
