### ISSUE TITLE
ftp user contain '@' char

### ISSUE THREAD

**Issue by marouane-kech** [git-ftp/git-ftp#268]
Hello,
I have the error bellow if the ftp user contain '@' char (user: workshop_7aflat@loyaltyone.com):

fatal: Can't access remote 'ftp://workshop_7aflat%40loyaltyone.com:***@ftp.loyaltyone.com', exiting...

is their any solution if I can't change the ftp user name ?

Thanks.

**Comment by mkllnk** [comment]
What was your solution? Did you set the user name with `git config`?

**Comment by tuffz** [comment]
same question as @mkllnk

**Comment by marouane-kech** [comment]
in fact there is no problem with the user name, I found later that the ftp host was incorrect.
Sorry gays and Thank you.
