### ISSUE TITLE
when pushed, a hash character is added at the beginning of filenames

### ISSUE THREAD

**Issue by donomron** [git-ftp/git-ftp#269]
when I push my files to server, a '#' character is automatically added at the beginning of every filename. For example if there is an index.php file and I push it using git-ftp it appears as #index.php.
I've googled a bit and it seems nobody faced this issue before, kind of weird to me. I'm also a newbie so I may be doing something wrong. Any ideas?

**Comment by mkllnk** [comment]
Yes, it is a bug in your version of mingw32. Updating mingw32 should solve the problem. So it did for #256.

**Comment by donomron** [comment]
@mkllnk Yes, updating mingw fixed the bug. Thanks for your help
