### ISSUE TITLE
Configure branches to different folders/servers

### ISSUE THREAD

**Issue by ubiko** [git-ftp/git-ftp#270]
I'd be nice if, for example `Test` branch could upload to `test.server.com` while `Master` branch uploads to `www.server.com` 

Is it possible to see this feature? Or is it already possible?

Cheers

**Comment by mkllnk** [comment]
Yes. That is possible. Look at the manual for [scopes](https://github.com/git-ftp/git-ftp/blob/develop/man/git-ftp.1.md#scopes). Once, scopes are setup, you can then just do `git ftp push -s`.

**Comment by ubiko** [comment]
@mkllnk sorry for the delay, got that figured out now. Thanks a lot :) :+1:
