### ISSUE TITLE
Question: how can i git-ftp after i switched from gitlab to bitbucket?

### ISSUE THREAD

**Issue by ejlocop** [git-ftp/git-ftp#272]
it seems like i cannot push my changes to live server via git-ftp after switching from gitlab to bitbucket repo.. i already configured the config file, 
i tried git ftp push, git ftp init and event git ftp catchup,
please help. thanks!

**Comment by mkllnk** [comment]
Did your commit history change?

If you just copied your files into a new repository, you have a complete new repository with new commit ids. If your current version is the deployed one, you should be able to just do a `git ftp catchup`. Which error message do you get?

If you want to upload all files again, you can do `git ftp init --force`.

**Comment by ejlocop** [comment]
thanks,
i did a git ftp catchup just now, and i get ..
``fatal: Could not upload file: 'public_html/careparrotnew/.git-ftp.log'., exiting...``
``fatal: Could not upload., exiting...``

 although i managed to upload it yesterday by using 
``git ftp push --user <user> --passwd <password> ftp://example.com/public`` and not 
``git ftp push``
dont know why,,

**Comment by mkllnk** [comment]
This seems to be a permission problem. You can add the `-v` or `-vv` options to get more details of whats going on.

**Comment by ejlocop** [comment]
curl: (67) Access denied: 530
Fri Jul  8 12:40:37 CST 2016: fatal: Could not get last commit. Network down? Wrong URL? Use 'git ftp init' for the initial push., exiting...

![untitled](https://cloud.githubusercontent.com/assets/12082880/16677517/85c58a26-4509-11e6-8f82-1512d1cb85e9.jpg)

**Comment by mkllnk** [comment]
Are you sure that the directory name is right? Can you connect with another ftp client?

**Comment by ejlocop** [comment]
yes, it's still the same, same name, same location, also used filezilla client and i can still connect with the server..

**Comment by mkllnk** [comment]
I can't see any mistake. Did you update git-ftp? Something must be different. Maybe your FTP server changed some permissions. I don't know.

**Comment by kachhawayamehulgmailcom** [comment]
From one bitbucket account it is working fine but when i am using another bitbucket account all files get successfully buffered but not uploaded at ftp server ,it gives a fatal error.
