### ISSUE TITLE
Question: how to overwrite files?

### ISSUE THREAD

**Issue by vcabreupy** [git-ftp/git-ftp#273]
Hello, mates. I have a question about uploads.
When i upload my files to the ftp, a new filde/dir is created with a "#" prefix.
Example:
the "app/Controller/ExampleController.php" file is being uploaded as "#app/Controller/ExampleController.php".
Can i somehow overwrite the files?
Thank you so much, mates.

**Comment by mkllnk** [comment]
G'day mate. Your mingw32 version has a bug that causes this # prefix. If you update that one, it should work again.

**Comment by vcabreupy** [comment]
Thank you, mate. It solved my problem.
Now i can upload my files normally! :smile:
