### ISSUE TITLE
fatal: Could not upload file: 'public_html/.git-ftp.log'., exiting...

### ISSUE THREAD

**Issue by donomron** [git-ftp/git-ftp#274]
When I try to upload my latest commit using `git ftp init` or trying to catchup using `git ftp catchup`, I get the following errors:
```
fatal: Could not upload file: 'public_html/.git-ftp.log'., exiting...
fatal: Could not upload., exiting...
```
This happens on some of my hosts, while on the others it works fine and I can push upcoming commits with no errors. What could possibly be the problem?

**Comment by mkllnk** [comment]
You can get debugging output If you add the `-vv` option. It will give you every single FTP command and the server response. There you can see what is different between the different hosts.

**Comment by donomron** [comment]
Ok, I added `-vv` option and found out that I've got a Access denied: 530 ftp server error. I googled a bit and while my login info (url,user,pass) are all correct and I have access through softwares like cuteFTP or filezilla, I still don't understand what is wrong. Apparently there seems to be some permission issue. But at least I know this does not have anything to do with git-ftp. Thanks

**Comment by mkllnk** [comment]
Do these hosts allow you to create files starting with a dot?

**Comment by donomron** [comment]
I checked it and yes, they do

**Comment by lkraider** [comment]
Can we specify another path for the log file?

**Comment by JakeGonzales** [comment]
I had the same problem and I had just run out of room on the server.

**Comment by funprogrammer89** [comment]
I am getting the could not upload file error as well. I am getting 'Uploading ...
* Closing connection -1
curl: (3) URL using bad/illegal format or missing URL'

my path is 'blogs/YouTube video (2-11-23).txt'

Any suggestions?
