### ISSUE TITLE
Files not really uploading after accessing ftp

### ISSUE THREAD

**Issue by richcaputo** [git-ftp/git-ftp#275]
A team member modified files over ftp, after this occurred my files say they are uploaded but when I go on the server the files are old. I have tried everything to get it back in sync but the server thinks it is up to date but it is not. 

Any fix to this issue?

**Comment by mkllnk** [comment]
Git-ftp uploads only files you have changed. Do you know which files your colleague changed? If not, the only option you have, is uploading all your files again:

    git ftp init -f

If you know the version your colleague used, you can tell Git-ftp which version is on the server with:

    git ftp push -c $sha1_commit_id

**Comment by richcaputo** [comment]
Yes I know what files he changed and I downloaded to my local system and checked into git in order to get us synced. But now no matter how many changes I make to a file git-ftp will act normally and say it uploaded the new files. When I go onto the server the files aren't there.

So it acts normal but it isn't actually uploading anything.

**Comment by mkllnk** [comment]
Is there maybe a permission problem with the new files? When uploading multiple files, the underlying curl command does not fail is some of the files fail to upload. And then git-ftp doesn't know that something went wrong.
