### ISSUE TITLE
Upload all files in .git-ftp-include, not the directory itself.

### ISSUE THREAD

**Issue by devkiran** [git-ftp/git-ftp#278]
Hi,

My .git-ftp-include consist of following line
!source/scripts

The current version of ftp-include upload the complete "scripts/". I understand that is the expected behavior. But how can i change the git-ftp to upload all files in the directory "scripts" and not the directory "scripts".

Eg:
repository/scripts/
   index.php 
   log.php

Need to push to 
public_html/
   index.php
   log.php

**Comment by mkllnk** [comment]
> how can i change the git-ftp to upload all files in the directory "scripts" and not the directory "scripts".

I don't fully understand that question. Do you want to upload the files that are in your scripts directory into another remote directory?

If you are uploading only from the scripts directory, you can use the syncroot option. But if you want to upload other files as well, you have to find some other solution. Git-ftp doesn't support a completely user defined mapping of files.

**Comment by devkiran** [comment]
@mkllnk Thanks for the reply.

Yes, i want to upload other files as well. Can you please suggest some similar alternative ? I am looking to integrate CI with Bibucket pipeline.

**Comment by mkllnk** [comment]
Maybe you can create a `dist` directory in which you copy everything you want to upload. Then call any ftp client to upload that directory. If you use git for the `dist` directory as well, you can set that as syncroot and use git-ftp to upload only the changed files.

**Comment by kaspersoerensen** [comment]
Don't know if this it what you are looking for. But check out this video tut about using pipelines with git-ftp
https://www.youtube.com/watch?v=8HZhHtZebdw

**Comment by mkllnk** [comment]
Thanks @kaspersoerensen. I linked your tutorial from the readme now.
