### ISSUE TITLE
Idea: Pull command checking only changed files

### ISSUE THREAD

**Issue by rndmerle** [git-ftp/git-ftp#279]
Hi.

I think it would be really useful if the pull command, somehow, could only check files that changed from the last commit.
Currently it checks every files on the ftp and it takes ages.
If I modified only one file from the last uploaded commit I would prefer that the pull command only gather that single file from the server.

Thanks :)

**Comment by mkllnk** [comment]
There is no way to find out which files are different on the server without downloading them. There are heuristics like looking at the timestamp or the size. But:

timestamp: A lot of FTP servers set the timestamp of a file to the upload time, not the last-modified time of your local file. So the uploaded file will always have a newer timestamp.

file size: If file sizes differ, you know that the files are different. But if they are the same, they could still be different. It could be that you corrected a typo or changed a date without changing the file size.

**Comment by rndmerle** [comment]
Sorry I didn't make it clear.
What I meant is that currently the mirror is done on all the ftp files.
What it could do :
- git diff [commit] --name-only
- transform that into an --include list ($include)
- do a mirror --exclude '.*' --exclude '.*/' $include $ignore
So it checks only for a handfull of files instead of the hundreds on the ftp server.

_(I guess [commit] should be the DEPLOYED_SHA1 for a for a download command and $CURRENT_BRANCH for a pull command)_

**Comment by mkllnk** [comment]
I see, you have a correct commit id on the server. I thought that you modify files manually. That's a nice idea. Pull requests are welcome. :-)
