### ISSUE TITLE
changed file uploaded to /#folder/filename.ext instead of /folder/filename.ext

### ISSUE THREAD

**Issue by dsukhin** [git-ftp/git-ftp#280]
When I call git ftp push or git-ftp push changes get uploaded to my ftp server in folders with prepended hashtags. At first I thought this was a temp upload location but the actual (correct) location remains untouched after the push completes so the git changes are never really updated on the ftp server. This seems to be due to line 383, 396, or 397 in the git-ftp bash script which appends a "#" to the remote location. I am not sure what the intention was here and if it is safe to change/remove the "#"?

System: Windows 7, git-bash

Thank you for your insights and help.

**Comment by dsukhin** [comment]
Noted advice on #256, #258, #254, #269 to update the version of MINGW32. It seems the git bundled version still has this bug so it would be useful to add this note in the FAQ (somewhere other than closed issues) so that others know to update the default version. Will update and close issue if it resolves.

**Comment by mkllnk** [comment]
Thanks for that feedback. It's very good to know that the bundled version has this bug. Which FAQ did you refer to? Where did you look for this issue first?

**Comment by dsukhin** [comment]
I guess hoped to find a note about the known issue in the Limitations section in the README, in the manual, or in a separate troubleshooting doc. I opened a ticket about the issue before remembering to check closes cases which others may neglect to do as well (given the 3 duplicates referenced above). Having a more prominent note about the unexpected behavior and the suggested fix would be useful for the next person to stumble on this. 

Thank you for your response and your great work on the utility!

**Comment by LukasFritzeDev** [comment]
Is this still an issue?
Since it’s 3 years old I think we can close it now, can’t we?
