### ISSUE TITLE
Wrong password doesn't give correct error message.

### ISSUE THREAD

**Issue by oquirozm** [git-ftp/git-ftp#285]
First time rising an issue in github ever, so not sure if this is how it should be done.

Anyway, I installed git-ftp via homebrew on OSX El Capitan 10.11.6. It works great. The thing that annoyed me a little was that when trying to push with a wrong password for the server on the command (like ... --passwd mypassword21212 ...) it returns a "fatal: Could not get last commit." error instead of an expected "Can't connect to server" or "Login failed" or just a better message.

**Comment by mkllnk** [comment]
Thank you. That would be a good enhancement.

**Comment by mkllnk** [comment]
I still think this is a valid issue that is not solved yet.

**Comment by oquirozm** [comment]
@mkllnk oh sorry! My first time opening an issue here at GitHub. I wasn't sure when to close it.

**Comment by mkllnk** [comment]
@oquirozm You normally close an issue when it's solved. In this case when there is a better error message. It can take a while, because Git-ftp is a volunteer project. The open issues are kind of a todo-list for everybody who would like to pick up a task.

**Comment by oquirozm** [comment]
@mkllnk got it. Thanks for explanation!

**Comment by szymekz** [comment]
Additional issue that I encountered is when you try to add password to config that starts with hash, like

> #myPassword

You would also get 'fatal: Could not get last commit', but when running command with -v you get "No password is set"

**Comment by mkllnk** [comment]
@szymekz I agree that this error message is not good. But did you have problems setting a password with a hash `#`? It should work if you quote it properly:

```sh
git config git-ftp.password "#myPassword"
# or
git-ftp -p "#myPassword" $other_options
```

**Comment by larsbo** [comment]
After debugging with `-vv` argument I found out that everything after a `#`sign inside the password will be ignored if the password is not quoted in the git config file.

If someone else has connection problems: check your password for hash signs 😃

**Comment by DerTanzschuh** [comment]
We should a note to the manual that passwords with special characters must be quoted.
