### ISSUE TITLE
git ftp init does nothing

### ISSUE THREAD

**Issue by LoveAndHappiness** [git-ftp/git-ftp#288]
Hello folks,

I pretty much followed every step from the setup, up until the point it says `git ftp init`.

After this commands just nothing happens. After I type the command in my command line tool and press enter, no visible action is executed. Weird thing is, that no further command is accepted. That means that you can still type whatever command you want, but nothing gets executed, after you hit return.

I am on OSX and used the standard terminal and the iTerm 3.0.4.

I use `git ftp` with a Virtual Machine (vagrant) and the laravel `homestead` box, which runs on Ubuntu 16.04.

Here is my configuration:

```
    [core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
    ignorecase = true
[remote "origin"]
    url = https://github.com/LoveAndHappiness/isg-oberbarmen.git
    fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
    remote = origin
    merge = refs/heads/master
[git-ftp]
    url = ftp://wp***.web****.host**.com
    user = ftp***738**-***
    password = **********
```

I would love to try git-ftp. Therefore I hope someone can come up with a suggestion about my problem.

To replicate my error, just install vagrant and homestead and install git-ftp on the virtual machine. Then proceed with the standard installation.

**Comment by pylejeune** [comment]
You have to setup a git repositor first:

Enter your Project directory:

cd my/Project/

Init a git repository on it:

git init
git add .
git commit -m "Initial commit"

Configure you FTP:

git config git-ftp.user demouser
git config git-ftp.url ftp.example.com/demofolder
git config git-ftp.password demopassword

http://stackoverflow.com/questions/20398565/how-to-set-up-a-repository-using-git-ftp

**Comment by mkllnk** [comment]
That sounds to me like the FTP server is not responding. For example, if I do `git ftp init ftp://example.com/test/`, then it waits a minute or two, nothing happening. Eventually it prints:

    fatal: Can't access remote 'ftp://example.com', exiting...

Is that happening to you?

How big is the repository you are trying to upload? You can also try the `-vv` option to get more output about what's happening.

**Comment by pylejeune** [comment]
As you tried to access your ftp server with another client, reason why there one to the impression that you do not access at all.

**Comment by imasonaz** [comment]
I'm getting a very similar issue. I logged in with an FTP client, can see files, etc fine, but when I git-ftp, it logs in and just sits there....

```
vagrant@vagrant:/projects/PHP/hgo$ git ftp init -vv
Sun Nov 13 19:40:33 UTC 2016: Host is 'ftp.XXX.host.xx'.
Sun Nov 13 19:40:33 UTC 2016: User is 'account@XXX.host.xx'.
Sun Nov 13 19:40:33 UTC 2016: Password is set.
Sun Nov 13 19:40:33 UTC 2016: Protocol not set, using default protocol ftp://.
Sun Nov 13 19:40:33 UTC 2016: Path is ''.
Sun Nov 13 19:40:33 UTC 2016: Syncroot is '/'.
Sun Nov 13 19:40:33 UTC 2016: The remote sha1 is saved in file '.git-ftp.log'.
Sun Nov 13 19:40:33 UTC 2016: CACert is ''.
Sun Nov 13 19:40:33 UTC 2016: Insecure is '1'.
Sun Nov 13 19:40:33 UTC 2016: Check if ftp://ftp.XXX.host.xx/ is accessible.
*   Trying 123.45.67.89...
* Connected to ftp.XXX.host.xx (123.45.67.89) port 21 (#0)
< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
< 220-You are user number 2 of 50 allowed.
< 220-Local time is now 15:40. Server port: 21.
< 220-This is a private system - No anonymous login
< 220-IPv6 connections are also welcome on this server.
< 220 You will be disconnected after 15 minutes of inactivity.
> USER testian@imason.cacsite.ga
< 331 User account@XXX.host.xx OK. Password required
> PASS XXXXXXXXXX
< 230 OK. Current restricted directory is /
> PWD
< 257 "/" is your current location
* Entry path is '/'
> EPSV
* Connect data stream passively
* ftp_perform ends with SECONDARY: 0
< 229 Extended Passive mode OK (|||57717|)
*   Trying 123.45.67.89...
* Connecting to 123.45.67.89 (123.45.67.89) port 57717
* Connected to ftp.XXX.host.xx (123.45.67.89) port 21 (#0)
> TYPE A
```

I can connect with command line `ftp` with success. Any ideas here?

**Comment by pylejeune** [comment]
You launch "git-ftp push" ?

**Comment by pylejeune** [comment]
you launch git-ftp push ?

2016-11-13 20:47 GMT+01:00 Ian M <notifications@github.com>:

**Comment by imasonaz** [comment]
This was the first time I had done anything, so I set up all the variables and ran `git ftp init` as it suggests in the instructions. Or did I read something wrong?

**Comment by imasonaz** [comment]
`git ftp push` has similar results:
```
vagrant@vagrant:/projects/PHP/hgo$ git-ftp push -vv
Mon Nov 14 08:36:53 UTC 2016: Host is 'ftp.XXX.host.xx'.
Mon Nov 14 08:36:53 UTC 2016: User is 'account@XXX.host.xx'.
Mon Nov 14 08:36:53 UTC 2016: Password is set.
Mon Nov 14 08:36:53 UTC 2016: Protocol not set, using default protocol ftp://.
Mon Nov 14 08:36:53 UTC 2016: Added missing trailing / in path.
Mon Nov 14 08:36:53 UTC 2016: Path is 'test/'.
Mon Nov 14 08:36:53 UTC 2016: Syncroot is '/'.
Mon Nov 14 08:36:53 UTC 2016: The remote sha1 is saved in file '.git-ftp.log'.
Mon Nov 14 08:36:53 UTC 2016: CACert is ''.
Mon Nov 14 08:36:53 UTC 2016: Insecure is '0'.
Mon Nov 14 08:36:53 UTC 2016: Retrieving last commit from ftp://ftp.XXX.host.xx/test/.
*   Trying 123.45.67.89...
* Connected to ftp.XXX.host.xx (123.45.67.89) port 21 (#0)
< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
< 220-You are user number 1 of 50 allowed.
< 220-Local time is now 04:36. Server port: 21.
< 220-This is a private system - No anonymous login
< 220-IPv6 connections are also welcome on this server.
< 220 You will be disconnected after 15 minutes of inactivity.
> USER account@XXX.host.xx
< 331 User account@XXX.host.xx OK. Password required
> PASS XXXXXXXXXXX
< 230 OK. Current restricted directory is /
> PWD
< 257 "/" is your current location
* Entry path is '/'
> CWD test
* ftp_perform ends with SECONDARY: 0
< 250 OK. Current directory is /test
> EPSV
* Connect data stream passively
< 229 Extended Passive mode OK (|||57687|)
*   Trying 123.45.67.89...
* Connecting to 123.45.67.89 (123.45.67.89) port 57687
* Connected to ftp.XXX.host.xx (123.45.67.89) port 21 (#0)
> TYPE I
```

and then sites there, same as `init`

**Comment by imasonaz** [comment]
So I let it sit for 10+ minutes and it finally spat out:
```
* Recv failure: Connection timed out
* Closing connection 0

curl: (56) Recv failure: Connection timed out
Mon Nov 14 09:46:02 UTC 2016: fatal: Can't access remote 'ftp://ftp.XXX.host.xx/test/'., exiting...
```
I'm not sure what is going on in the background, but again both command line FTP and a normal FTP client work correctly.

**Comment by mkllnk** [comment]
You did the right thing with `git ftp init`. And the log is very helpful. Maybe the server does not support passive FTP. You can try the `--active` option. The `--disable-epsv` could also help you.

**Comment by imasonaz** [comment]
I am very confused at this point..... It looks like this FTP setup is really, really weird. Maybe redirects to a local share or something??

```
vagrant@vagrant:/projects/PHP/hgo$ git-ftp init --active -vv
Wed Nov 16 08:41:19 UTC 2016: Using active mode.
Wed Nov 16 08:41:53 UTC 2016: Host is 'ftp.XXX.host.xx'.
Wed Nov 16 08:41:53 UTC 2016: User is 'account@XXX.host.xx'.
Wed Nov 16 08:41:53 UTC 2016: Password is set.
Wed Nov 16 08:41:53 UTC 2016: Protocol not set, using default protocol ftp://.
Wed Nov 16 08:41:53 UTC 2016: Added missing trailing / in path.
Wed Nov 16 08:41:53 UTC 2016: Path is 'test/'.
Wed Nov 16 08:41:53 UTC 2016: Syncroot is '/'.
Wed Nov 16 08:41:53 UTC 2016: The remote sha1 is saved in file '.git-ftp.log'.
Wed Nov 16 08:41:53 UTC 2016: CACert is ''.
Wed Nov 16 08:41:53 UTC 2016: Insecure is '0'.
Wed Nov 16 08:41:53 UTC 2016: Check if ftp://ftp.XXX.host.xx/test/ is accessible.
*   Trying 123.45.67.89...
* Connected to ftp.XXX.host.xx (123.45.67.89) port 21 (#0)
< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
< 220-You are user number 5 of 50 allowed.
< 220-Local time is now 04:41. Server port: 21.
< 220-This is a private system - No anonymous login
< 220-IPv6 connections are also welcome on this server.
< 220 You will be disconnected after 15 minutes of inactivity.
> USER account@XXX.host.xx
< 331 User account@XXX.host.xx OK. Password required
> PASS XXXXXXXXXX
< 230 OK. Current restricted directory is /
> PWD
< 257 "/" is your current location
* Entry path is '/'
> CWD test
* ftp_perform ends with SECONDARY: 0
< 250 OK. Current directory is /test
> EPRT |1|10.0.2.15|49719|
< 500 I won't open a connection to 10.0.2.15 (only to <MY REMOTE IP>)
* disabling EPRT usage
* Hostname 10.0.2.15 was found in DNS cache
> PORT 10,0,2,15,223,245
< 500 I won't open a connection to 10.0.2.15 (only to <MY REMOTE IP>)
* Failed to do PORT
* Remembering we are in dir "test/"
* Connection #0 to host ftp.XXX.host.xx left intact

curl: (30) Failed to do PORT
Wed Nov 16 08:41:55 UTC 2016: fatal: Can't access remote 'ftp://ftp.XXX.host.xx/test/'., exiting...
```
<MY REMOTE IP> would be my IP, e.g. if I went to http://whatismyip.com, 10.0.2.15 is verbatim. (I know, class A local IP range...) This is a cPanel webhost setup, so I honestly don't know what else I can do to troubleshoot this?

**Comment by mkllnk** [comment]
You are using FTP in active mode. That means that after the client connects to the server, the server opens a second connection to the client. For the second connection, the client needs to be accessible by the server as if it were a server itself. A 10.x.x.x address is a local address. I guess that is your client's local address (your computer). It is probably behind a NAT router (standard DSL router) that translates the local address, which is not accessible from the internet, to the router's public IP. That public IP is what you see at whatismyip.com.

In order to make this work, you would need to activate a special FTP module in your router. The router would than scan the traffic for FTP commands and make sure that the second connection from the FTP server to your local computer succeeds. Not every router supports this.

If you can't change your router, you have to use passive mode. Most servers support that. You can try to drop `--active` or use `--disable-epsv` instead. Sounds all complicated? FTP is a very old protocol that was not prepared for modern routers and firewalls.

**Comment by brandiqa** [comment]
Thanks for the tip @mkllnk. I got it working on Linux Mint 18 using this command:

```bash
git ftp init -v --disable-epsv -s testing
```
Perhaps you can make a note on this in README.md

**Comment by mkllnk** [comment]
Thank you for the comment @brandiqa. What do you think about https://github.com/git-ftp/git-ftp/pull/367?

**Comment by brandiqa** [comment]
Yes that's perfect. I'll add a few more suggestions in #367 though

**Comment by swinggraphics** [comment]
How can we save the option to always use passive mode or disable EPSV in the config?

**Comment by LukasFritzeDev** [comment]
The feature to set a config flag to always disable EPSV was introduced in #524.
