### ISSUE TITLE
Nice to have: git-ftp pull

### ISSUE THREAD

**Issue by zevero** [git-ftp/git-ftp#29]
This would be really nice to have!
So in order to make an old rusty website shine we would only have to

    git-init
    git-ftp pull user@pass:domain.com/www
    git commit -m "rusty"

than we could apply our changes and go off with

    git commit -m "shiny"
    git push

and off we go!

**Comment by tomicakorac** [comment]
Is there any status change of this?

**Comment by mkllnk** [comment]
The code is there, see the branch "pull". We just tried to fix some bugs before we introduce a new feature, but that seems to take a bit longer... :-(

You can try out the pull branch version and give some feedback if that works for you.

**Comment by tomicakorac** [comment]
Will do, thanks a lot for your reply @mkllnk .

**Comment by chrispepper1989** [comment]
Is the git ftp pull feature any closer to being recommendable?

**Comment by mkllnk** [comment]
Yes, there are only two things to work on now.

1. The 1.1.0 release should be done.
2. Issue #217 indicates a problem with that branch.

But it's scheduled for the 1.2.0 release. That means it will go in the develop branch in the next iteration.

**Comment by leesavide** [comment]
+1

**Comment by mkllnk** [comment]
This has been merged into the develop branch.

**Comment by RadianSmile** [comment]
I can't wait to see its release! Thanks a lot!

**Comment by tuffz** [comment]
:+1:

**Comment by novalore** [comment]
Great!
Thank you for that
