### ISSUE TITLE
How to upload to Amazon AWS using SFTP

### ISSUE THREAD

**Issue by kunalm** [git-ftp/git-ftp#291]
I am working on a project which has a staging server on amazon aws. I have the server name, username, key file and the folder on the server where I have access to upload the files. When I set this up using filezilla, everything works fine.

Here's my settings for git-ftp which isn't working. Please help to mention if I am doing something wrong.

```
[git-ftp "staging"]
    url = {aws server name}/{staging folder i.e. var/www/html/website.com/staging}
    user = {username}
    key = /Volumes/Dropbox/{project_name}/{keyfile}`
```

**Comment by mkllnk** [comment]
Make sure that you use `sftp` as protocol and you need to add the `insecure` option since.

```ini
[git-ftp "staging"]
    url = sftp://{aws server name}/{staging folder}
    user = {username}
    key = /Volumes/Dropbox/{project_name}/{keyfile}
    pubkey = /Volumes/Dropbox/{project_name}/{keyfile}
    insecure = 1
```

Does that work? If not, can you post debugging output (`-vv`) here?

**Comment by mkllnk** [comment]
The important error message is:
> Unable to open public key file
Are you sure that it's the right file and the right path to the public key?

If you run `cat /Users/siddarth/Documents/checkout/pipelineTest/pipeline-test/undisclosablefile.pub`, you should see the content of your public file like this:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy4U2LjgHILaDMrMeDT4tFx4qXxVQWdho/CFK3zVycHEy4dtysEun5vzfubzDRgcrI6Gp1P6+Xn258J94JCFHshKzH/xbB2nlQupGt1Z04DdSNMp7KkFkEKgjD0SG8EyVsj/p2O/JyTXwx3MZxIYEoui1nQoEkLg8CZFTN2Du3YYEwW+qe8o6IKa6SvNFZ4/KSr+r5GgoQyubs7tZ+hP2f6OWdEolVEkztpyUSqZZmisuFE7GwK3+SKgbbEgaz1pLBYB4oWtAQvN8MbJrKN+FDbgMMKoYYo+Fy0GOajHa4XwD1jXFvM1oiQB4N5JHkFJE0HxZWpt7GWS9X9/4HbF6j
```

If it doesn't look like that, then you can generate the public key from your private key:
`ssh-keygen -y -f key.pem > key.pem.pub`

**Comment by sidxyz** [comment]
Hi Thanks for your swift response.
I did run the cat command and was able to view the contents like how you mentioned.

I thought that maybe I had generated the public key in the wrong way.
I used ssh-keygen -y -f undisclosed.pem > publicKey.pub

On using the newly generated public key I get the same error as before.
I even did chmod 777 publicKey.pub and I still get the same error as before.

I am running a Mac with bitbucket pipelines? does this have something to do with the error?

Do you want me to post the output here as well?

**Comment by mkllnk** [comment]
Sorry for the late reply. Can you show your public key? What does `ssh-keygen -y -f key.pem` print? Maybe the Mac version is different...
