### ISSUE TITLE
Uploading...

### ISSUE THREAD

**Issue by patrickwee** [git-ftp/git-ftp#298]
My screen is stuck at uploading...  Anyone know why that might be the case? Maybe having a progress bar would be helpful.

In particular, I get this circular problem. 

```
pwee:CommTechWebsite nyuad$ git ftp init --user xxxxxxx --passwd xxxxxxx sftp://caroline.dreamhost.com:22/xxxxxxx
fatal: Commit found, use 'git ftp push' to sync. Exiting...
pwee:CommTechWebsite nyuad$ git ftp push
fatal: Could not get last commit. Network down? Wrong URL? Use 'git ftp init' for the initial push., exiting...
```

**Comment by mkllnk** [comment]
Unless you saved username and password in the git config, you still need to pass it on to `git ftp push`. Did you do that?

**Comment by patrickwee** [comment]
`[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = https://github.com/patrickwee/commtech.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[git-ftp]
	user = pkw228
	url = caroline.dreamhost.com
	password = xxxxx
`

This is how my config file looks like. Note that I want to perform an sftp transfer.

**Comment by mkllnk** [comment]
Is it SFTP or SCP? Which errors do you get when executing these command?

```sh
curl -u pkw228 sftp://caroline.dreamhost.com:22/
curl -u pkw228 scp://caroline.dreamhost.com:22/
```
