### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by raglannyc** [git-ftp/git-ftp#299]
My web host (iPower) tells me that command line ftp is not allowed, but curl is. It is my limited understanding that git-ftp uses curl, so I thought it would work, but I'm getting a connection refused error. I've tried passive mode, ftp, sftp, etc. I am able to connect just fine with an ftp client. Here is what I get (personal info removed):

```git ftp catchup -vv
Tue Nov 15 18:13:40 EST 2016: Host is '********.com'.
Tue Nov 15 18:13:40 EST 2016: User is '*******'.
Tue Nov 15 18:13:40 EST 2016: Password is set.
Tue Nov 15 18:13:40 EST 2016: Protocol not set, using default protocol ftp://.
Tue Nov 15 18:13:40 EST 2016: Path is ''.
Tue Nov 15 18:13:40 EST 2016: Syncroot is ''.
Tue Nov 15 18:13:40 EST 2016: The remote sha1 is saved in file '.git-ftp.log'.
Tue Nov 15 18:13:40 EST 2016: CACert is ''.
Tue Nov 15 18:13:40 EST 2016: Insecure is ''.
Tue Nov 15 18:13:40 EST 2016: Uploading commit log to ftp://*******:***@********.com/.git-ftp.log.
*   Trying **.**.**.**...
* connect to **.**.**.** port 21 failed: Connection refused
* Failed to connect to ********.com port 21: Connection refused
* Closing connection 0

curl: (7) Failed to connect to ********.com port 21: Connection refused
Tue Nov 15 18:13:40 EST 2016: fatal: Could not upload file: '.git-ftp.log'., exiting...
Tue Nov 15 18:13:40 EST 2016: fatal: Could not upload., exiting...```

**Comment by imasonaz** [comment]
I think you're going to have some issues if you can't FTP (access port 21). I believe ftp-git uses both FTP and curl, or at least uses curl over FTP protocol.

By chance does your host support one of the other possible protocols: `sftp, ftps, or ftpes` ? How do oyu normally upload files to this server?

**Comment by raglannyc** [comment]
I normally connect via FTP, passive mode, port 21, using an FTP client. My host does not support those other protocols, though I did try them in git-ftp anyway. I also tried using passive mode in git-ftp using `--disable-epsv` which didn't make a difference in the errors I see. I'm guessing git-ftp does use `ftp` :)

**Comment by mkllnk** [comment]
Just to clarify: "curl" is not a protocol. Curl is an FTP client. It is also an HTTP, HTTPS, FTPS, etc. client. It supports a lot of protocols and that's why it's so handy and used by Git-ftp.

@raglannyc I don't know why the server refuses the connection to port 21. Does you normal FTP client use port 21 as well?

You can try to play around with `curl` or `ftp`:

```sh
curl ftp://your-host.example.com/
# or
ftp your-host.example.com
```

If you find a curl command that works, we can probably find a solution how to tell git-ftp to use curl in that way.

**Comment by Baldonak** [comment]
> Just to clarify: "curl" is not a protocol. Curl is an FTP client. It is also an HTTP, HTTPS, FTPS, etc. client. It supports a lot of protocols and that's why it's so handy and used by Git-ftp.
> 
> @raglannyc I don't know why the server refuses the connection to port 21. Does you normal FTP client use port 21 as well?
> 
> You can try to play around with `curl` or `ftp`:
> 
> ```shell
> curl ftp://your-host.example.com/
> # or
> ftp your-host.example.com
> ```
> 
> If you find a curl command that works, we can probably find a solution how to tell git-ftp to use curl in that way.

Hi, i have the same problem. First, i want clarify I have very limited knowledge. In my case, the curl command works. Any idea how i can fix this problem? Attached result of "git ftp init -vv"


`$ git ftp init -vv
Wed Nov 10 15:04:26     2021: git-ftp version 1.6.0 running on MINGW64_NT-10.0-19043 LAPTOP-L309IPRJ 3.1.7-340.x86_64 2021-03-26 22:17 UTC x86_64 Msys
Wed Nov 10 15:04:26     2021: Syncroot is './'.
Wed Nov 10 15:04:28     2021: Host is 'lignakalk.000webhostapp.com:21'.
Wed Nov 10 15:04:28     2021: User is 'lignakalk'.
Wed Nov 10 15:04:28     2021: Password is set.
Wed Nov 10 15:04:29     2021: CACert is ''.
Wed Nov 10 15:04:29     2021: Insecure is '0'.
Wed Nov 10 15:04:29     2021: Proxy is ''.
Wed Nov 10 15:04:29     2021: Added missing trailing / in path.
Wed Nov 10 15:04:29     2021: Path is 'htdocs/public_html/'.
Wed Nov 10 15:04:29     2021: The remote sha1 is saved in file '.git-ftp.log'.
Wed Nov 10 15:04:30     2021: Check if curl is functional.
Wed Nov 10 15:04:30     2021: Check if ftp://lignakalk:***@lignakalk.000webhostapp.com:21 is accessible.
*   Trying 145.14.144.97:21...
* connect to 145.14.144.97 port 21 failed: Connection refused
* Failed to connect to lignakalk.000webhostapp.com port 21: Connection refused
* Closing connection 0
curl: (7) Failed to connect to lignakalk.000webhostapp.com port 21: Connection refused
Wed Nov 10 15:04:33     2021: fatal:  Can't access remote 'ftp://lignakalk:***@lignakalk.000webhostapp.com:21'. Network down? Wrong URL? exiting...`
