### ISSUE TITLE
// vs /   -- two slashes after ip address work normally, but one doesn't

### ISSUE THREAD

**Issue by vedro-compota** [git-ftp/git-ftp#300]
hello!

I use last version of git-ftp (thanks for it!) 
But I found a problem:
In my situation address in config like `83.22.54.229/home/foo/`:
```
[git-ftp "test"]
     user = df836as
     url = "83.22.54.229/home/foo/"
     password = dfgd34rg34g
```

 caused error like:
```
 Thu, Nov 17, 2016 2:06:08 PM: Using scope test if available
Thu, Nov 17, 2016 2:06:09 PM: Host is '83.22.54.229'.
Thu, Nov 17, 2016 2:06:09 PM: User is 'sbah'.
Thu, Nov 17, 2016 2:06:09 PM: Password is set.
Thu, Nov 17, 2016 2:06:09 PM: Path is 'home/foo/'.
Thu, Nov 17, 2016 2:06:09 PM: Syncroot is ''.
Thu, Nov 17, 2016 2:06:09 PM: The remote sha1 is saved in file '.git-ftp.log'.
Thu, Nov 17, 2016 2:06:09 PM: CACert is ''.
Thu, Nov 17, 2016 2:06:09 PM: Insecure is ''.
Thu, Nov 17, 2016 2:06:09 PM: Uploading commit log to ftp://sbah:***@83.22.54.229/home/foo/.gi....

curl: (9) Server denied you to change to the given directory
Thu, Nov 17, 2016 2:06:11 PM: fatal: Could not upload file: 'home/foo ua/.git-ftp.log'., exiting...
Thu, Nov 17, 2016 2:06:11 PM: fatal: Could not upload., exiting..
```

You can see that in this case gitftp set path to:
```
Thu, Nov 17, 2016 2:06:09 PM: Path is 'home/foo/'.
```

To resolve this problem I changed url in uncorrect way: `83.22.54.229//home/foo/`
but it helps (don't know why).

Please tell me is this path (url) correct or (if not) why  doesn't work  `83.22.54.229/home/foo/` but `83.22.54.229//home/foo/` does.

Thanks)

**Comment by mkllnk** [comment]
You are accessing an absolute path `/home/foo/`. But when giving a URL like `83.22.54.229/home/foo/`, a relative path is assumed. If you add an extra slash, the URL is not wrong, but a bit confusing. Alternatively, you can give the option `--remote-root "/home/foo"`. That would be the correct way in this case.

**Comment by vedro-compota** [comment]
thank you @mkllnk
