### ISSUE TITLE
Branch specific .git-ftp-ignore

### ISSUE THREAD

**Issue by sdellow** [git-ftp/git-ftp#303]
Is it possible to specify different .git-ftp-ignore files depending on the branch?

I want to exclude some files from my production server (that deploys from the master branch) but I want those files on my staging server (that deploys from the staging branch).

Is this possible?

**Comment by mkllnk** [comment]
No, you can't change the name of the `.git-ftp-ignore` file. You could commit different versions of it to your branches. But than you have to be careful not merge these changes back.

You could also write a wrapper script that copies the right ignore file before deploying. Doesn't sound very nice, but possible.

**Comment by sdellow** [comment]
Ok cool. Thanks for the suggestion.
