### ISSUE TITLE
git ftp init  need auto create path or  report error when target path exists.

### ISSUE THREAD

**Issue by eromoe** [git-ftp/git-ftp#311]
When the path(dir) not exists. , `git ftp init`  would output:

```
fatal: Can't access remote 'sftp://root:***  ......
```
This error message is inccorect, and one has to create folder first to make it works.

**Comment by mkllnk** [comment]
Well, it can't access that URL, because it doesn't exist. I think that is correct. But I agree that the error message could be better.

**Comment by eromoe** [comment]
What I imagine is going to root `/` first, then goto `some/path`,   in this way we can know path exist or not.

**Comment by mkllnk** [comment]
That would not work in every case. Sometimes you just specify a relative path like `public_html` and the absolute path would have an undetermined component like `/homes/random-abc123/example.org/public_html`. I think we need to parse curl's error message to know there is an authentication failure or the path doesn't exist. And with `--force` it would skip the check and just create the path if it can.
