### ISSUE TITLE
fatal: 'garrysmod' is not a directory! Exiting...  

### ISSUE THREAD

**Issue by sirolf2009** [git-ftp/git-ftp#312]
Hello, I'm trying to setup git-ftp, but I'm running into some issues

This is my configuration
```
git config git-ftp.url ftp://95.211.217.113:8821
git config git-ftp.user SebastianT
git config git-ftp.password **CENSORED**
git config git-ftp.syncroot garrysmod
```

and here's what I send
```
git commit -a -m "Add new content"
git ftp init
```

and here's the error it produces
```
fatal: 'garrysmod' is not a directory! Exiting...  
```

we have a folder in our root called garrysmod, how come it won't connect?

**Comment by mkllnk** [comment]
I assume that 'garrysmod' is a folder on the FTP server, right? And you want to copy the contents of your repository to that folder, right? In that case:

```sh
git config git-ftp.url ftp://95.211.217.113:8821/garrysmod
git config --unset git-ftp.syncroot
git ftp init
```

The syncroot is a local directory. For example, if you compile your website into a folder 'dist' locally and want to upload it to 'public_html', you can upload that to the remote with `git ftp init --syncroot "dist" "ftp://example.org/public_html"`.

Did this solve your problem?

**Comment by sirolf2009** [comment]
Thank you, it turned out that we should've put our root folder at the end of the url. So it's working now

**Comment by romsnowcode** [comment]
> I assume that 'garrysmod' is a folder on the FTP server, right? And you want to copy the contents of your repository to that folder, right? In that case:
> 
> ```shell
> git config git-ftp.url ftp://95.211.217.113:8821/garrysmod
> git config --unset git-ftp.syncroot
> git ftp init
> ```
> 
> The syncroot is a local directory. For example, if you compile your website into a folder 'dist' locally and want to upload it to 'public_html', you can upload that to the remote with `git ftp init --syncroot "dist" "ftp://example.org/public_html"`.
> 
> Did this solve your problem?

Thanks
