### ISSUE TITLE
How to use git ftp with ssh?

### ISSUE THREAD

**Issue by denmarkdavis** [git-ftp/git-ftp#313]
$ git ftp push -u user --key key.pem sftp://x-x-x-x-x.amazonaws.com:/var/www/html -v

Returns:

Protocol "sftp" not supported or disabled in libcurl

Do you know what I'm doing wrong?

Huge thanks in advance!

**Comment by mkllnk** [comment]
Git-ftp uses the curl command under the hood. But your version of curl doesn't support sftp. You probably need to re-install curl with sftp support. If you are on MacOS, you may want to install curl with `brew install curl --with-ssh`. But be careful to run the right version if you have multiple curl versions installed. If you want to build it from source, this post can help you: http://andrewberls.com/blog/post/adding-sftp-support-to-curl

**Comment by denmarkdavis** [comment]
Thanks so much. It's super appreciated. I'm learning quick ...

I've got curl with sftp now. **But unfortunately with new errors:** git ftp push -v or git ftp init -v

Sat  7 Jan 2017 14:32:28 CET: Host is 'xx-xx-xx-xx-xx.xx.xx.amazonaws.com:'.
Sat  7 Jan 2017 14:32:28 CET: User is 'ec2-user'.
Sat  7 Jan 2017 14:32:28 CET: No password is set.
Sat  7 Jan 2017 14:32:28 CET: Using ssh private key file ~/.ssh/key.pem
Sat  7 Jan 2017 14:32:28 CET: Using ssh public key file ~/.ssh/key.pem.pub
Sat  7 Jan 2017 14:32:28 CET: Path is 'var/www/html/'.
Sat  7 Jan 2017 14:32:28 CET: Syncroot is ''.
Sat  7 Jan 2017 14:32:28 CET: The remote sha1 is saved in file '.git-ftp.log'.
Sat  7 Jan 2017 14:32:28 CET: CACert is ''.
Sat  7 Jan 2017 14:32:28 CET: Insecure is ''.
Sat  7 Jan 2017 14:32:28 CET: Check if sftp://ec2-user:***@xx-xx-xx-xx-xx.xx.xx.amazonaws.com: is accessible.

curl: (67) Authentication failure



**My git config file is:**

[git-ftp]
	url = sftp://xx-xx-xx-xx-xx.xx.xx.amazonaws.com:/var/www/html/
	user = ec2-user
	key = ~/.ssh/key.pem




**Port 22 is open and working on ec2**. Am I close to having this sussed?

**Comment by denmarkdavis** [comment]
Update (fixed!):

1) git-ftp needs absolute refs to pem/pub file: /Users/User/.ssh/key instead of ~/.ssh/key
2) git-ftp/curl needed a pem **and** a _pub_ file
3) Troubleshooting was greatly helped trying to connect with Curl first. i.e. curl -u user: --key ~/.ssh/key.pem --pubkey ~/.ssh/key.pub sftp://server.com:/var/www/html/ -v


My config file (.git/config):
[git-ftp]
	url = sftp://server.com
	user = user
	key 	= /Users/user/.ssh/key.pem
	pubkey = /Users/user/.ssh/key.pub
	syncroot = local_files_to_upload/
	remote-root = var/www/html/

Now works with git ftp push

**Comment by mkllnk** [comment]
Thanks for debugging that and sharing your solution.
