### ISSUE TITLE
problems doing catchup

### ISSUE THREAD

**Issue by kirstyannepollock** [git-ftp/git-ftp#315]
I installed git-ftp via cygwin, and the config commands all ran without problem, but `git ftp catchup` gives back `git: 'ftp' is not a git command. See 'git --help'.`

This is from within VSCode - could that be an issue?

**Comment by mkllnk** [comment]
The problem seems to be that Git can't find Git-ftp. Can you call `git-ftp`? What does `echo $PATH` say and where is `git-ftp` installed?

**Comment by kirstyannepollock** [comment]
ah, right, nope,  can't call git-ftp, right enough. Sorry, I misread the 3 setup commands, they are only calling git, that is why they worked. 

Where git-ftp is installed needs to be on the $PATH, right enough.  I will go find out where cygwin put it.

**Comment by kirstyannepollock** [comment]
hmmmm... I am confused (sorry for the German, my PC is set up in German)


`Verzeichnis von C:\cygwin64\bin

07.01.2017  10:47            44,156 git-ftp
               1 Datei(en),         44,156 Bytes
               0 Verzeichnis(se), 25,412,976,640 Bytes frei

C:\cygwin64\bin>git-ftp
Der Befehl "git-ftp" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\cygwin64\bin>`

**Comment by mkllnk** [comment]
It looks like you are in a Windows terminal. It should be much easier if you start cygwin which should open up a Unix terminal. Don't worry about the German, it's my mother tongue.

**Comment by kirstyannepollock** [comment]
I now have cygwin. :-) But I was running git from within VSCode (that is my current workflow). I am about to go on holiday for 2 weeks, but I will try it again when I get back.


So many clever Germans on the 'net :-).


________________________________
