### ISSUE TITLE
fails to delete a file it put on the ftp server

### ISSUE THREAD

**Issue by meepen** [git-ftp/git-ftp#316]
method: ftp
port: 8855

```
> LIST
< 125 Data connection already open. Transfer starting.
* Maxdownload = -1
lrwxrwxrwx   1 panel users 32 Dec 07 16:13 ip_port -> /home/somewhereelse
lrwxrwxrwx   1 panel users 65 Dec 07 16:13 ip_port_web -> /home/somewhereelse/ip_port
* Remembering we are in dir ""
< 226 Transfer complete.
> DELE ip_port/some/where/test.txt
< 550 Access Denied.
* QUOT string not accepted: DELE ip_port/some/where/test.txt
* Connection #0 to host <server> left intact
curl: (21) QUOT string not accepted: DELE ip_port/some/where/test.txt
Mon Jan  9 06:54:01 CET 2017: Could not delete ip_port/some/where/test.txt, continuing...
```

I'm not sure why this is happening, but if you need any more information just tell me.

The main directory is a "fake" home directory with symlinks to server-specific files.
1> I added a file `test.txt` in `ip_port/some/where/test.txt` and committed it and it was there
2> I removed with `git rm test.txt` and committed it and this happens.

What I expected to happen:

It would delete the file

**Comment by mkllnk** [comment]
You can see the deletion command that is executed on the server: `DELE ip_port/some/where/test.txt`
Is that path correct? Can you do the same with an ordinary FTP client? Because the error message says that you are not allowed to delete the file.

**Comment by meepdarknessmeep** [comment]
i can delete it normally within the ftp client itself, but not with git ftp. i can check the command that does work in a bit.

**Comment by LukasFritzeDev** [comment]
Is this still relevant? Have you found a solution?

If so I must say that this working fine in my test repo even with a symlink on the server side path. 
Wich version of Git-ftp did you use?
