### ISSUE TITLE
Why does SFTP connection need --pubkey option?

### ISSUE THREAD

**Issue by vedro-compota** [git-ftp/git-ftp#319]
Hi there!
Tell me please why does SFTP connection need --pubkey option?
Usually to connect via ssh we need only private key on client side.

> --key : SSH private key file name.
--pubkey : SSH public key file name. Used with --key option.

**Comment by mkllnk** [comment]
Yes, but Git-ftp uses Curl to transfer files and, as far as I know, Curl needs both options. If curl doesn't need both options, it's a false assumption in Git-ftp and we should change that.

**Comment by adrum** [comment]
When passing the `--insecure` into curl, it allows sftp connection with private key only.

**Comment by vedro-compota** [comment]
> When passing the --insecure into curl, it allows sftp connection with private key only.

@adrum  is it possoble using git ftp? If so please put example here)

**Comment by adrum** [comment]
`git ftp push --key ~/path/to/key --insecure sftp://example.org`

These are the parameters needed to make this work. You would obviously want to add the other parameters you need like syncroot, user, etc.

**Comment by vedro-compota** [comment]
@adrum thank  u)
