### ISSUE TITLE
git-ftp with SFTP -- without public key (setting), resolve error on Windows

### ISSUE THREAD

**Issue by vedro-compota** [git-ftp/git-ftp#320]
Hi there!

I found that get git-ftp can work through SFTP (cURL) _without using public key_ (.pem private one only).
To **resolve errors:**
```
SSH public key authentication failed: Invalid key data, not base64 encoded
curl: (67) Authentication failure
(and other)
```

You should replace this line in git-ftp source file (before install git-ftp) :
```
REMOTE_CMD_OPTIONS="$REMOTE_CMD_OPTIONS --key $CURL_PRIVATE_KEY --pubkey $CURL_PUBLIC_KEY "
```
by:
```
REMOTE_CMD_OPTIONS="$REMOTE_CMD_OPTIONS --key $CURL_PRIVATE_KEY " #--pubkey $CURL_PUBLIC_KEY
```

russian text of solution here:   http://fkn.ktu10.com/?q=node/8543  <--**по-русски здесь**

**Comment by mkllnk** [comment]
Oh. Thank you. That means I was wrong in https://github.com/git-ftp/git-ftp/issues/319. We should change Git-ftp do use the two options independently.

**Comment by mkllnk** [comment]
Can you test if this version works for you as well? https://github.com/git-ftp/git-ftp/commit/3949cf3718b4ffc4aaa5452861574bdca6f962dc
