### ISSUE TITLE
What are the steps when you encounter fatal: Dirty repository: Having uncommitted changes. Exiting...

### ISSUE THREAD

**Issue by mvaneijgen** [git-ftp/git-ftp#327]
Couldn't find anything in the readme and there is no wiki

**Comment by tuffz** [comment]
Looks like you have "uncommitted changes", try 
```sh
$ git status
```
and commit or discard your changes.

**Comment by devpilot** [comment]
I have a remote repo (not bare), added a post-receive hook
`git ftp push -b master`
When pushing changes from client machine the post-receive hook showing fatal: Dirty repository: Having uncommitted changes. Exiting...
```
$ git push origin master
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 303 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: fatal: Dirty repository: Having uncommitted changes. Exiting...
To cool-server.com:repo/test-deploy_b
   b3b43c9..4c105ad  master -> master
```
When executing the post-receive hook on the remote machine manually its working fine
```
$ ./.git/hooks/post-receive
1 file to sync:
[1 of 1] Buffered for upload 'index.html'.
Uploading ...
Last deployment changed from 4c105ad1fe6ed2da81963f911b9a3f9f02341d7f to 2b84348065315a077abdd26926aa7a7f992a5ce5.
```
FYI: No direct commits on remote repo, only push

**Comment by mkllnk** [comment]
@devpilot Which output do you get if you call `git status` just before `git ftp push`?

**Comment by devpilot** [comment]
Git status showing working directory is clean

**Comment by mkllnk** [comment]
Interesting. What if you call `git status -uno --porcelain`? Do you use the most recent version of Git-ftp? I'm wondering if something somehow creates files there. You don't do something like `git ftp push > deploy.log`, do you?

**Comment by devpilot** [comment]
Hi, @mkllnk 
I'm using git-ftp version 1.3.3

So iI've added `git status -uno --porcelain` to my post-receive hook
```
#!/bin/sh
echo $(git --version)
echo $(git-ftp --version)
echo "Running: git status -uno --porcelain"
git status -uno --porcelain
echo "Running: git-ftp push -b master"
git-ftp push -b master
```
and the output
```
$ git push origin master
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 314 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: git version 1.7.1
remote: git-ftp version 1.3.3
remote: Running: git status -uno --porcelain
remote:  D .gitignore
remote:  D README.md
remote:  D app.js
remote:  D index.html
remote:  D package.json
remote: Running: git-ftp push -b master
remote: fatal: Dirty repository: Having uncommitted changes. Exiting...
To server.com:repo/deploy
   30e191b..d6ed432  master -> master
```
I don't know how those `D` status are coming. :worried:
FYI: However executing the post-receive script manually on remote repo's server going smoothly as it suppose to.
On the remote repo I checkeout a commit hash to keep HEAD detached so I can push to master branch.

**Comment by mkllnk** [comment]
I have a suspicion. The post-receive hook is usually called within the .git folder. But Git-ftp assumes that your are in the working tree. Check `pwd`, `echo $GIT_DIR` and `echo $GIT_WORK_TREE`. You can do something like:
```sh
cd "$GIT_WORK_TREE"
unset GIT_DIR
unset GIT_WORK_TREE
```

That works if you have the .git directory in your work tree. Otherwise you need to set the GIT_DIR variable.

**Comment by devpilot** [comment]
Hi @mkllnk 
You were right post-receive hook is called within .git. So I added the mentioned echos to my script

```shell
#!/bin/sh
echo "pwd"
echo $(pwd)
echo "GIT_DIR"
echo $GIT_DIR
echo "GIT_WORK_TREE"
echo $GIT_WORK_TREE
cd ..
unset GIT_DIR
unset GIT_WORK_TREE
echo $(pwd)
echo "Running: git status -uno --porcelain"
git status -uno --porcelain
echo "Running: git-ftp push -b master"
git-ftp push -b master
```
and the output
```
$ git push
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 297 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: pwd
remote: /home/user/repo/deploy/.git
remote: GIT_DIR
remote: .
remote: GIT_WORK_TREE
remote:
remote: /home/user/repo/deploy/
remote: Running: git status -uno --porcelain
remote: Running: git-ftp push -b master
remote: 1 file to sync:
remote: [1 of 1] Buffered for upload 'index.html'.
remote: Uploading ...
remote: Last deployment changed from 64598e0359d0640dc699450db1c192846979d431 to ce6bf622b271aafa35f779d5216d21e1e6015468.
To server.com:repo/deploy
   a3d8831..ce6bf62  master -> master
```
$GIT_WORK_TREE was empty so I `cd ..` instead and it worker, Thanks :+1: 

Yes I have .git in my work tree. However I couldn't understand the parts...

`$GIT_DIR = .` Shouldn't it be path to .git?
`$GIT_WORK_TREE = ` Why it's empty?
Why need to unset?
`unset GIT_DIR`
`unset GIT_WORK_TREE`

 I'd be glad if you could explain  :smiley:

**Comment by mkllnk** [comment]
Usually, you are in the work tree when calling `git` yourself. And usually, `GIT_DIR` and `GIT_WORK_TREE` are not set. Git then looks for the `.git` directory as Git directory and assumes that its parent is the Git work tree.

The post receive hook is executed from within the `.git` directory. It sets `GIT_DIR` to `.` (meaning the current directory) to tell all commands that they are executed within the Git directory. Since the `GIT_WORK_TREE` is empty, all commands should assume that it's the parent directory of the Git directory. Usual Git commands work with that. Only Git-ftp is a bit stupid and needs to be called from the Git work tree.

**Comment by devpilot** [comment]
@mkllnk understood, Thanks

**Comment by mkllnk** [comment]
It would be great to start an FAQ document. Is anyone up for creating one?

**Comment by antoine1003** [comment]
Hi I have this issues when I try to push just one file ti the FTP : 
```
git add myfile.txt
git commit -m "file added"
git push
git ftp push
fatal: Dirty repository: Having uncommitted changes. Exiting...
```
Hope you can help !

**Comment by mkllnk** [comment]
Yeah, it doesn't work if you have other changes in your repository. Put you can do it like this:

```
git add myfile.txt
git commit -m "file added"
git push
git stash
git ftp push
git stash pop
```

**Comment by antoine1003** [comment]
@mkllnk Okay thx i'll try 😄
