### ISSUE TITLE
Auto deploy

### ISSUE THREAD

**Issue by HTeker** [git-ftp/git-ftp#328]
Is it possible to let Git FTP keep track of a specific branch (develop) and sync the changes whenever something has been merged?

I read the documentation and cannot find anything like it.

**Comment by mkllnk** [comment]
Can you explain your use case a bit? Would you like to run Git-ftp after running `git merge develop`?

I guess you could create a shell alias like `alias project-releas="git merge develop && git ftp push"`. Or you could create a Git post-merge hook that checks if you just merged develop into master and then executes Git-ftp. You can look at `man githooks` to see how they work.
