### ISSUE TITLE
Can i push to a sub domain?

### ISSUE THREAD

**Issue by codehakase** [git-ftp/git-ftp#333]
I tried pushing to a sub domain and i get an error `fatal: Can't access remote 'ftp://test:***@ftp.sandbox.test.com, exiting...` 
`sandbox` is the subdomain here.

How do i fix this?
`

**Comment by amayer5125** [comment]
Have you tried without putting ftp. At the begining?
ftp://test:***@sandbox.test.com

**Comment by codehakase** [comment]
@amayer5125 not really, i'll do that now

**Comment by workingwebsites** [comment]
I'm having the same issue.  git-ftp works fine on main sites, but I can't get it to work on sub-domains.
I've tried removing the ftp.xxxx, still getting the error:
fatal: Can't access remote 'ftp://username%40sitename.com:***@ftp.sitename.com', exiting...

The config file looks like:
`[git-ftp]
	url = ftp.website.com
	user = "username@website.com"
	password = "password"`

**Comment by amayer5125** [comment]
I'm guessing it worked for them. Since they didn't comment back.

Can you ftp to the subdomain you are using with another client? Such as Filezilla?

I haven't actually worked with FTP in about 2 years. So I may not be the best person to try and debug your issue.
