### ISSUE TITLE
Push my ftp-config 

### ISSUE THREAD

**Issue by sunnyton93** [git-ftp/git-ftp#335]
How can I push git-ftp.url, user, password in my remote repository?

I want to clone my repository but it does not contain my git-ftp configuration information

**Comment by mkllnk** [comment]
Git configurations are always local. They are not cloned or pushed. You could add a setup script to your repository that sets the configuration. But be careful not to upload that script to a public server like a web server, because it would contain your FTP password.

**Comment by sunnyton93** [comment]
How could I use a script? Hooks?

**Comment by mkllnk** [comment]
Open a text file, for example `git-ftp-setup.sh` and put in there stuff like:

```sh
git config git-ftp.user john
git config git-ftp.url ftp.example.com
git config git-ftp.password secr3t
```

Then add that filename to `.git-ftp-ignore` so that you don't deploy it.
