### ISSUE TITLE
Remove value set in git-ftp.keychain

### ISSUE THREAD

**Issue by digisavvy** [git-ftp/git-ftp#336]
Hey there,
How do I change or remove a setting I put in place for the git-ftp.keychain setting?

**Comment by mkllnk** [comment]
Git-ftp uses [git-config](https://git-scm.com/docs/git-config).
```sh
git config git-ftp.keychain NewValue@example.org # change
git config git-ftp.keychain --unset # remove
```

**Comment by digisavvy** [comment]
Super swell, thanks!
When I used the `--unset` flag and then I tried running git ftp init I received this error `fatal: Password not found in keychain for account '--unset @ hostname_or_ip'.` 

But running
`git config git-ftp.keychain ""` seemed to drop the value I originally placed.
