### ISSUE TITLE
git ftp push generate "#" in files, example "#index.php" 

### ISSUE THREAD

**Issue by erojasm** [git-ftp/git-ftp#337]
When the files are published this generates a "#" at the beginning of the name of each file. For example in local "index.php", and when uploading the file is named "#index.php".

Some help please.

**Comment by mkllnk** [comment]
Try installing a newer version of mingw32. See also: #280, #269, #258 and #256.

**Comment by erojasm** [comment]
Hello, update the version as indicated in the other issues but the problem persists. Any download link or something?

Thank you anyway.

**Comment by mkllnk** [comment]
Which version are you using?

**Comment by erojasm** [comment]
Hello,
I am using the version that comes in the git-ftp package, seeing one of its files has version 4.4.0-tdm-1.

**Comment by erojasm** [comment]
Hi, apparently it does not install git-ftp correctly. Now I did it with these commands and everything works fine, I no longer have the "#" errors.

Cd
Git clone https://github.com/git-ftp/git-ftp git-ftp.git
Cd git-ftp.git && chmod + x git-ftp
Cp ~ / git-ftp.git / git-ftp / bin / git-ftp

Thanks for your help.

**Comment by mkllnk** [comment]
What did you do before?
