### ISSUE TITLE
Problem .git-ftp-include

### ISSUE THREAD

**Issue by eduardocintra** [git-ftp/git-ftp#340]
Hello, everybody.

I'm with a problem to send to ftp a file that's in my ".gitignore". I put it in my ".git-ftp-include",  but i noted that when I sent the command "git push" the file is not sent to my FTP.

.git-ftp-include:

`!bundle.js`

For all to understand, I'm using a tool called "PIPELINE" to do deploy from "bitbucket" and webpack to build my front-end files. From what i understand git ftp will send just the files committed, correct? But, if the file is in my ".gitignore" how am I commit it?

Sorry about my English.

**Comment by mkllnk** [comment]
Let's see if I understand this correctly. The file `bundle.js` is on your local computer, but it's not tracked by Git and therefore not uploaded to Bitbucket. If you would run `git-ftp push` on your local computer, the file should be uploaded. If you run that command in a Bitbucket pipeline and the file is not there, it can't be uploaded. How do you generate `bundle.js`? If you run a command to compile it from your source, you should be able to run the same in your pipeline before you try to upload it.

**Comment by eduardocintra** [comment]
First, thank you very much for trying to help me.

I generate the file "bundle.js" through of webpack, and I can generate it inside of pipeline in Bitbucket.

My pipeline script is this, look:

`pipelines:`
`  custom: # Pipelines that are triggered manually`
`    deployment-to-staging:`
`      - step:`
`          script:`
`            - apt-get update`
`            - npm update`
`            - apt-get -qq install git-ftp`
`            - ls`
`            - webpack`
`            - ls`
`            - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://64.111.121.30/teste/ --all`

I put two ls command in the pipeline script.

The output from the first ls command is:

`bitbucket-pipelines.yml`
`content.js`
`entry.js`
`index.html`
`node_modules`
`package.json`
`style.css`
`webpack.config.js`

Te second is:

`+ ls`
`bitbucket-pipelines.yml`
`bundle.js`
`content.js`
`entry.js`
`index.html`
`node_modules`
`package.json`
`style.css`
`webpack.config.js`


The bundle.js was created from "webpack" command.

But, in my FTP the file "bundle.js" not existent.

Look:
http://prntscr.com/em1iau

**Comment by mkllnk** [comment]
Okay, now I see the problem. The Bitbucket pipelines use an old version of Git-ftp (0.9.0). That version didn't support that syntax starting with `!`. You could either use a newer version of Git-ftp (https://github.com/git-ftp/git-ftp/issues/339#issuecomment-289418733) or you use a different syntax:

    bundle.js:content.js
    bundle.js:entry.js
