### ISSUE TITLE
Files in `.git-ftp-include` get deleted

### ISSUE THREAD

**Issue by JoshuaCrewe** [git-ftp/git-ftp#348]
I have found an issue with my current setup where any file listed in `.git-ftp-include` gets deleted. 

I am using version 1.3.3 install with homebrew on macOS version 10.11.6 and have `syncroot` option set to `app/`.  This is pretty much the whole set up.

**What I do**
The project structure has various configurations in the root such as the `.gitignore`, `gulpfile.js` and `node_modules` etc. The files being targeted are all in the app folder with a few of the distribution files being ignored by git. These are basically `app/assets/css/app.min.css` and `app/assets/js/app.min.js`. These files are included in the `.git-ftp-include` file like so :
```
!/app/assets/css/app.min.css
!/app/another-file.txt
```
The project is initiated and the output shows that there are some files for uploading and files for deleting.

**What I expect to happen**
I would expect that everything that is tracked in git that is inside `app/` will get uploaded to the server, while those files which are defined in `.git-ftp-include` get uploaded to the server despite being ignored by git.

**What actually happens**
All tracked files in `app/` get uploaded fine. Those files defined in `.git-ftp-include` also get uploaded but then the same files get deleted.

This is the output of a very simplified project structure which shows the issue.

```
/app/assets/css/app.min.css                                                                                                                                    
/app/another-file.txt                                                                                                                                          
7 files to sync:                                                                                                                                               
[1 of 7] Buffered for upload '.git-ftp-include'.                                                                                                               
[2 of 7] Buffered for upload '.gitignore'.                                                                                                                     
[3 of 7] Buffered for upload 'app/another-file.txt'.                                                                                                           
[4 of 7] Buffered for upload 'app/assets/css/app.min.css'.                                                                                                     
[5 of 7] Buffered for upload 'app/assets/src/sass/app.scss'.                                                                                                   
Uploading ...                                                                                                                                                  
[6 of 7] Buffered for delete '/app/another-file.txt'.                                                                                                          
[7 of 7] Buffered for delete '/app/assets/css/app.min.css'.                                                                                                    
Deleting ...                                                                                                                                                   
Last deployment changed from  to 9b3f27363c9eaebbff26c80efa1ef79a35cf8863.
```
As far as I can tell any file that gets put in `.git-ftp-include` goes on the delete list.

In other news this is the first Issue I have ever submitted so forgive me if it is too verbose / not verbose enough.

Happy to provide any additional information required to reproduce.

**Comment by mkllnk** [comment]
Thank you for your report. The issue is that the leading `/` is seen as your system's root `/`, not the Git working directory. This is confusing, because the syntax with `target.txt:/source.txt` is supported. So the Git tracked source file can be prefixed with `/`. But since the target file could be anywhere in your filesystem, the `/` is not seen as your Git working directory.

Does it work when you remove the leading slashes?

**Comment by JoshuaCrewe** [comment]
Hello,

Sorry that was my fault. I must have been trying a few things to try and debug. 

Removing the preceding slash from that includes file does seem to fix that. Which means that the issue does not occur in the simplified example. There is however no preceding slash the include file for the actual project I am working on. This means that there is an issue with some other configuration or set up that I have done there. 

I am going to say that the issue with with me at this point and not something for anybody else to worry about. I am going to have some lunch and hopefully that will fix it.

Thanks for your prompt response!

**Comment by JoshuaCrewe** [comment]
While my lunch was in the microwave, I had a fiddle around again. The issue I was having was the same one in both places essentially.

In my project there is the `.git-ftp-include` file which had my distribution files listed. I also have `--syncroot` set to `app/`. The paths in the includes file were written as if the root were `app/`. By changing the paths to be originating from the actual root then there are no issues. 

The man page says that the former is correct I believe. Unless I have got confused over the matter. 

My `.git-ftp-include` did say :
```
!assets/css/app.min.css
!assets/js/app.min.js
```
My `.git-ftp-include` now says :
```
!app/assets/css/app.min.css
!app/assets/js/app.min.js
```
Where there is no issue and doesn't result in a deletion of those files.

**Comment by mkllnk** [comment]
I see, the man page says:

> When using the `--syncroot` option, all paths are relative to the set syncroot.

That is wrong. Only the source file on the right side of the `:` is prefixed with the syncroot. The target files to include have to be relative to the Git working tree.

**Comment by JoshuaCrewe** [comment]
Ahhhh I see! that totally makes sense. Sorry about the confusion.

👍 for an awesome project BTW
