### ISSUE TITLE
Question: Is it possible to ignore files on a 'per scope' basis?

### ISSUE THREAD

**Issue by danlake** [git-ftp/git-ftp#354]
I am looking to be able to deploy code from a single repo (multiple directories) to different servers. I am all good with scopes but it seems that I can't ignore some directories for each scope?

Have I missed anything or is this a feature request?

**Comment by mkllnk** [comment]
Can you give an example? Do you want the same as https://github.com/git-ftp/git-ftp/issues/338?

Is it that you would like to ignore a folder like example_data when you push to production, but ignore the directory production_secrets when you push to staging?

Currently, the file `.git-ftp-ignore` is the same for all scopes.

**Comment by danlake** [comment]
Yes, that would work. My specific use case is for deploying specific code to different servers from a single repo. So a repo structure could be:
.
|─cms/
|─app/
|─api/

...and I would need to deploy the contents 'cms' and 'app' to custom locations on a single server and the contents of 'api' to a separate server separate from the CMS for instance - oh and different branches for pre-prod and prod.

**Comment by mkllnk** [comment]
Closing this as the current answer is: no, that feature doesn't exist. It has been requested in #338. You can only define different syncroot options.
