### ISSUE TITLE
Add installation instructions for Alpine Linux

### ISSUE THREAD

**Issue by aaron-haskins** [git-ftp/git-ftp#355]
It would be nice to have git-ftp installation instructions for [Alpine Linux](https://alpinelinux.org/) as it is currently gaining popularity as a super lightweight docker container for CI/CD.

**Comment by mkllnk** [comment]
Maybe you should ask the Alpine Linux community to create a package? Otherwise, the simplest installation that should work on any system as root is:
```sh
curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > /bin/git-ftp
chmod 755 /bin/git-ftp
```

Uninstall:
```
rm /bin/git-ftp
```

Would you like to have that in INSTALL.md? Where does it best fit in?

**Comment by LukasFritzeDev** [comment]
Probably this might be a good addition the installation with Git currently described in [`INSTALL.md`](https://github.com/git-ftp/git-ftp/blob/master/INSTALL.md#linuxunix-based-systems-using-make). But we should mention this installs the most recent version even if it’s unreleased.
