### ISSUE TITLE
Feature Request: Slack notifications when deployed

### ISSUE THREAD

**Issue by briansaycocie** [git-ftp/git-ftp#356]
I'm using `git-ftp` as my CI deployment tool. It would be fantastic to hook this into Slack so I can get a notification when the deployment goes through successfully (or if it failed). DeployBot (great deployment tool but at a cost) has something similar setup: https://deploybot.com/blog/slack-notifications-for-your-deployments

**Comment by mkllnk** [comment]
You can check the exit code in your deploy script and than call the API. You can also use the post-ftp-push hook (only called if successful). But I don't think that this integration needs to be inside of Git-ftp.

A warning though: The underlying upload program `curl` doesn't exit with an error code as long as the last file uploaded successfully. So you won't catch all errors unless you check the output for error messages.

Even though there is no need for a Slack integration in Git-ftp, an example script how to use Slack with Git-ftp would be handy. Who has done it?

**Comment by briansaycocie** [comment]
Went with a different solution.

**Comment by DerTanzschuh** [comment]
@briansaycocie It would be great if you could share your solution here 🙂
