### ISSUE TITLE
vsftpd, cannot connect after upgrade to Debian9

### ISSUE THREAD

**Issue by zvolsky** [git-ftp/git-ftp#362]
Solved --> Firewall requires some additional port as earlier

### Question

With Debian8 stable on production there was no problem.

After upgrading from Debian 8 to Debian 9 on the production server
ftp ip-address
ftp domain
both work well with user+password which I have in git config.

But git-ftp push hangs: Retrieving last commit from ftp://www-data:***@zitranavylet.cz/www-data/... ....... after few minutes: curl: (8) Failed to connect to zitranavylet.cz...
git-ftp init hangs: Check if ftp://www-data:***@zitranavylet.cz is accessible.

What can I try now?

### Environment

client
Linux zvolsky2 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux
git-ftp version 1.3.1
(echo "$SHELL") /bin/bash

git config -l
git-ftp.forpsi.url=zitranavylet.cz/www-data/web2py/applications/krepo
git-ftp.forpsi.user=www-data
git-ftp.forpsi.password=xxxxxxxxxx

server
Linux mzDebian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u1 (2017-06-18) x86_64 GNU/Linux
vsftpd/stable,testing,now 3.0.3-8+b1 amd64 [installed]

vsftpd: /etc/vsftpd.conf
write_enable=yes
chroot_local_user=yes
local_root=/home
pam_service_name=ftp
userlist_enable=yes
userlist_file=/etc/vsftpd.userlist
userlist_deny=no
/etc/vsftpd.userlist: www-data (1 row only)

/etc/var/vsftpd.log has 2 rows:
Thu Jun 22 13:56:34 2017 [pid 9619] CONNECT: Client "::ffff:188.95.124.10"
Thu Jun 22 13:56:34 2017 [pid 9618] [www-data] OK LOGIN: Client "::ffff:188.95.124.10"
.......... that is exactly how it was earlier (where however DOWNLOAD row follows)

vsftpd.service status
Jun 22 14:06:45 mzDebian systemd[1]: Starting vsftpd FTP server...
Jun 22 14:06:45 mzDebian systemd[1]: Started vsftpd FTP server.
.......... and nothing more

**Comment by zvolsky** [comment]
I have tested with vsftpd 3.0.2-17+deb8u1 on the server, which was Deb8-Jessie version. No change, no success.

**Comment by zvolsky** [comment]
Problem is in the firewall. With this setting it works:
ufw allow proto tcp from 188.xxx.xxx.xxx/24 to any port 1025:65535
However what should be the proper setting?

**Comment by mkllnk** [comment]
Thank you for documenting your story here. It is correct that FTP uses arbitrary ports for data transfer and they have to be open in the firewall.
