### ISSUE TITLE
Problem with nested git directory

### ISSUE THREAD

**Issue by muuvmuuv** [git-ftp/git-ftp#364]
### Bug / Enhancement / Question ?

* How to reproduce the issue?
Creating a project where sub directories have other git repos while the root is another too

* Can you point to a Git repository to reproduce it?
No, but the two sub repos are
- https://github.com/muuvmuuv/grav-theme-flaten
- https://github.com/muuvmuuv/grav-skeleton-flaten

* Or can you describe the directory structure?
I have my root where the .git, .git-ftp-ignore, .git-ftp-include files are. Then I have a user folder where my content belongs (second git repo), inside there is a theme folder with my theme (third repo).

The Problem: So I'd first init git ftp and that many times until I got my user directory working (so I thought), I had to force include it with git-ftp-include what is not really great. After that it crawled over 9000 files, what is particular right (just a few files where missing like two directories and some files). The problem is just that I want to have all files upload except the one I declared in my git-ftp-ignore. And my sub directories has a gitignore files but no other git-ftp-ignore.

### Environment

```sh
/bin/zsh
Darwin marvin.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun  8 19:12:26 PDT 2017; root:xnu-3789.70.15~12/RELEASE_X86_64 x86_64
git-ftp version 1.4.0
```

.git-ftp-ignore: https://pastebin.com/LMXnfkCb
.git-ftp-include: https://pastebin.com/DEGQJWLM

**Comment by mkllnk** [comment]
Just to clarify, your problem is that git-ftp uploads files that are declared in `.git-ftp-ignore`. Is that right? Can you give some examples? So which file gets uploaded and which pattern in `.git-ftp-ignore` should prevent that?

Did you add the nested Git repositories as Git submodules or are you tracking them in your root repository?

**Comment by muuvmuuv** [comment]
@mkllnk - Yes and no. It is a bit strange. The .git directories will be uploaded until I ignore them and the user dir will only be uploaded by include them. I havent used submodules before, how does that work?

**Comment by mkllnk** [comment]
Have a read of https://git-scm.com/book/en/v2/Git-Tools-Submodules. It is a way to make your root repository track only the versions of your nested repository and not care about the files within it. But that is just another way to organise your repository and is not needed to work with Git-ftp.

I don't have enough information to find out what is happening for you. For example, do you ignore anything in `.gitignore`? Git-ftp basically uses `git diff` to list the changed files, filters that list according to `.git-ftp-ignore` and add more files according to `.git-ftp-include`. So it would be interesting if the files in your `user` directory are listed by `git diff`.

**Comment by LukasFritzeDev** [comment]
As @mkllnk mentioned Git submodules would be the way to go here.

Looks like you have solved the issue in the meantime. I will close this issue for now but please feel free to re-open it if my guess is not correct and you still have this problem with Git-ftp.
