### ISSUE TITLE
.git-ftp-ignore is not working since git-ftp-1.3.1-1

### ISSUE THREAD

**Issue by kaweepatt** [git-ftp/git-ftp#365]
### Bug

* I just found that right now the git ftp does not respect .git-ftp-ignore file any more. It is still upload the files that they are listed in this file.

### Environment

* Bitbucket pipeline

+ apt-get -qq install git-ftp
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libcurl3:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 10112 files and directories currently installed.)
Preparing to unpack .../libcurl3_7.52.1-5_amd64.deb ...
Unpacking libcurl3:amd64 (7.52.1-5) ...
Selecting previously unselected package curl.
Preparing to unpack .../curl_7.52.1-5_amd64.deb ...
Unpacking curl (7.52.1-5) ...
Selecting previously unselected package git-ftp.
Preparing to unpack .../git-ftp_1.3.1-1_all.deb ...
Unpacking git-ftp (1.3.1-1) ...
Setting up libcurl3:amd64 (7.52.1-5) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Setting up curl (7.52.1-5) ...
Setting up git-ftp (1.3.1-1) ...

git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://flowsale.com/domains/flowsale.com/private_html/origin/sso13s
+ git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://flowsale.com/domains/flowsale.com/private_html/origin/sso
1 file to sync:
[1 of 1] Buffered for upload 'index.php'.
Uploading ...
Last deployment changed from 0b4ae8ecff990444d7dd1bd86189d5ada957717f to 17b0462dad90557d9a4a2464024aff1bc96a6a87.

.git-ftp-ignore file contains below code:
'bitbucket-pipelines.yml'
'index.php'
'assets/*'
'upload/*'
'protected/runtime/*'

**Comment by mkllnk** [comment]
Hi!

You posted the following `.git-ftp-ignore` file:

> 'bitbucket-pipelines.yml'
> 'index.php'
> 'assets/*'
> 'upload/*'
> 'protected/runtime/*'

Do you have the single quotes `'` in your file? It should work without them. Can anyone else confirm this issue?

**Comment by kaweepatt** [comment]
Hi,
Without single quotes, it is working properly now. Thank you for your reply. It seems that the translation of .git-ftp-ignore is different between 0.9.0 and 1.3.1.
In 0.9.0, if I do not put single quotes then it will ignore all file that it contains the text such as it will ignore "index.php", "/protected/view/index.php" also.
