### ISSUE TITLE
TLS Version 1.2?

### ISSUE THREAD

**Issue by hadfiiw** [git-ftp/git-ftp#369]
Trying to get git-ftp working on a Mac and I cannot connect.  When I run the “git ftp init -vv” it fails and I eventually get a...

* Connection failed
* connect to x.x.x.x port yyy failed: Operation timed out
* Failed to connect to ftp.xxxx.com port yyy: Operation timed out
* Closing connection 0

But, if I run the command...

curl -v -u “userName:password” "ftps://ftp.xxxx.com" --tlsv1.2

...I can connect without a problem (I think - here is the output)...

* Rebuilt URL to: ftps://ftp.xxxx.com/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying x.x.x.x…
* TCP_NODELAY set
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0^C

Likewise, if I try the above curl command without the "--tlsv1.2" option, it does not work and fails with the same errors as with git-ftp...

* Connection failed
* connect to x.x.x.x port yyy failed: Operation timed out
* Failed to connect to ftp.xxxx.com port yyy: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to ftp.xxxx.com port yyy: Operation timed out

So I am guessing it may have to do with the TLS version 1.2 option?  I added “--tlsv1.2“ to my .curlrc file but I am not sure if git-ftp is actually using it(?)

Is there another way to force git-ftp to use TLS version 1.2?

Thanks!

******************************

/bin/bash

Darwin <local hostname> 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

git-ftp version 1.4.0

**Comment by adrum** [comment]
If you have homebrew installed, can you try running the following?

```
brew install curl --with-openssl
brew link curl —force
```

This should replace the command line tools curl with openssl built in. Make sure this curl is used via

```
which curl
```

That should output `/usr/local/opt/curl/bin/curl`. If it's not, you may need to add this to your `.bash_profile`

```
export PATH="/usr/local/opt/curl/bin:$PATH"
```

**Comment by hadfiiw** [comment]
I had installed curl with openssl but had not run the other commands.  After running those, it now shows...
```
$ which curl
curl is /usr/local/opt/curl/bin/curl
curl is /usr/local/bin/curl
curl is /usr/bin/curl
```

...and .bash_profile has...

```
export PATH="/usr/local/opt/curl/bin:$PATH"
#export PATH
```

I still get the same issues BUT now it seems to be a bit worse.  When I run...

`curl -v -u “userName:password” "ftps://ftp.xxxx.com" --tlsv1.2`

...I now get the same output as the failed attempts...

* Connection failed
* connect to x.x.x.x port yyy failed: Operation timed out
* Failed to connect to ftp.xxxx.com port yyy: Operation timed out
* Closing connection 0
* curl: (7) Failed to connect to ftp.xxxx.com port yyy: Operation timed out

**Comment by hadfiiw** [comment]
Took two steps forward.  So this now works...

`curl -v -u “userName:password” "ftps://ftp.xxxx.com"`

...by adding the following to my ~/.curlrc file...

```
	-o PreferredAuthentications=password
	--tlsv1.2
```

Unfortunately, "git ftp init -vv" still does not work.

**Comment by hadfiiw** [comment]
Going to close this for now.  I can't even get curl to work so git-ftp has no chance.  If I can get curl to work with my ISP, and git-ftp still doesn't work, I can re-open.
