### ISSUE TITLE
catchup doesn't create .git-ftp.log files for submodules

### ISSUE THREAD

**Issue by JasonWoof** [git-ftp/git-ftp#37]
I just tested ``git ftp catchup`` like so:

1.    on server, remove the ``.git-ftp.log`` file from the root dir and from the submodule dir

2.    on my home computer, run ``git ftp catchup``

Results: the server now has a ``.git-ftp.log`` file in the root directory, but is missing the one that should be in the submodule dir

3.    on home computer, make a commit (just changed a file in the root dir)

4.    ``git ftp push``  (works as it should)

5.    make a commit in the submodule, then one in the root dir to record the new version of the submodule

6.    ``git ftp push`` from main repo (not from within submodule)

Results: "fatal: Could not get last commit. Network down? Wrong URL? Use 'git ftp init' for the inital push., exiting..." and then it uploaded all the files again.

Request: make ``git ftp catchup`` create ``.git-ftp.log`` files for all submodules.

Thanks!

- Jason

P.S. It's odd that it says "fatal" and then proceeds. I think it should either stop (ie treat it like a fatal error) or it should say something more like "ERROR: couldn't blah blah. uploading everything just in case".

**Comment by mkllnk** [comment]
You are probably not around any more. I just merged a patch for this problem and therefore close the issue.

**Comment by JasonWoof** [comment]
Yay! I'm so glad to see that this project is being actively maintained. I stopped paying attention a couple years ago. It looks like the pace of commits has picked up considerably.

I use git-ftp all the time, though I've got some hacks, fixes, etc in my tree. I'll try to convert those into bug reports and/or pull requests. I'd love to get in sync with upstream (you)
