### ISSUE TITLE
pull: Fetching files without checkout deployed sha

### ISSUE THREAD

**Issue by ScreamingDev** [git-ftp/git-ftp#371]
### Bug / Enhancement / Question ?

* How to reproduce the issue?

See https://github.com/git-ftp/git-ftp/blob/master/git-ftp#L1160

What if I don't want to checkout ?
Because the repo is in some messed up state or I want to update the main branch.
This lines puts me in some detached head state which truly interrupts working.

Is there a fetch command? 
This should not do the checkout but only fetch files.

Also this should not be done `git add --all` which can not be suppressed by now:
https://github.com/git-ftp/git-ftp/blob/master/git-ftp#L1152

**Comment by mkllnk** [comment]
> What if I don't want to checkout ?
> Is there a fetch command?

If you want to merge the remote changes into the right version, you have to go back to that state. Maybe you are looking for `git ftp download`?

**Comment by ScreamingDev** [comment]
Ah nice. Sorry.
Sometimes things seem out of sync and in some worst cases the customer deletes the sha file.
Download helps very much! :)
