### ISSUE TITLE
Installation on ubuntu

### ISSUE THREAD

**Issue by theo4u** [git-ftp/git-ftp#375]
Having issue in getting the latest version on node docker image using apt-get , trying to follow the installation guide i need to do this in a pipeline for continous integration purpose 
`add-apt-repository ppa:git-ftp/ppa` 
after 
`apt-get update` 
returned 

git-ftp version
sh: 81: git-ftp: not found

and i want the latest version instead of version 0.9.0

After doing the `make install` from the clone i can't call `git-ftp version` unless i go through /usr/local/bin/git-ftp which is not what i want to do

**Comment by theo4u** [comment]
Finally did it, was mixing the installation with apt-get and make install, removed the `apt-get remove git-ftp` and now used the clone method with `make install` everything up to date.

**Comment by mkllnk** [comment]
If you want a lightweight Docker image that has only the script, you can just do:

```sh
curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > /usr/bin/
```
