### ISSUE TITLE
password with #

### ISSUE THREAD

**Issue by strukturart** [git-ftp/git-ftp#376]
Appears in the password a # 
git ftp can't login

**Comment by mkllnk** [comment]
That could be, because of an encoding problem as in https://github.com/git-ftp/git-ftp/issues/318 or because of a quoting problem as in https://github.com/git-ftp/git-ftp/issues/285#issuecomment-249797266.

**Comment by DerTanzschuh** [comment]
I can’t confirm this with the current version.

```
git config git-ftp.password abc#123
git ftp init
```
```
git ftp init -v -u test -p abc#123 ftp://127.0.0.1/
```
Both variants are working fine for me.

If the `#` is the first character in your password, you have to quote it, as mkllnk already commented:
```
git config git-ftp.password '#123'
git ftp init -v -u test -p '#123' ftp://127.0.0.1/
```
But it’s working. (_we might add this to documentation_) If it’s not the first character (in the middle as above or last character) you can use it as is.

As noted there are issues in connection to special characters in passwords, but at the moment `#` is not one of these characters.

---

Have tried quoting your password? What system do you use?
