### ISSUE TITLE
Upload changed files between two commits

### ISSUE THREAD

**Issue by EizEddin** [git-ftp/git-ftp#384]
Is it possible to upload all changed files between two commits? Irrespectively of the recorded upload history.

I can list those changes files using the following git command:
git diff --name-only SHA1 SHA2

So I want to upload the outputted list of those files.

Is this possible? and how to do that?

Thanks

**Comment by mkllnk** [comment]
Sure, that is possible, but you need to checkout the version that you want to upload:
```sh
git checkout SHA2
git ftp push --commit SHA1
```

This will upload the files of SHA2 that have changed compared to SHA1. But it will also consider your .git-ftp-ignore and .git-ftp-include files. So the actual list of files may be different to `git diff`.

Thanks to your question I just noticed that the `--commit` option is not documented in the manual, only on the help screen (`git ftp --help`). Let's leave this issue open until it's documented.

**Comment by mkllnk** [comment]
I added some documentation in https://github.com/git-ftp/git-ftp/commit/6383590273f068bd7d5279039e23b16f0b8490e6.
