### ISSUE TITLE
.git deleted after git-ftp download

### ISSUE THREAD

**Issue by juzala** [git-ftp/git-ftp#386]
### Bug / Enhancement / Question ?

after one of a download from ftp a .git catalogue was deleted. I cloned again my repository and add a .git to a .git-ftp-ignore, but i think its shouldn't happen. :)

### Environment

Please copy the output of the following commands.

```sh
echo "$SHELL"
uname -a
git-ftp version
```

/bin/bash
Darwin WafBookPro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
git-ftp version 1.4.0

**Comment by mkllnk** [comment]
Thank you for reporting.

**Comment by c-holtermann** [comment]
I have the same problem. Local .git dir keeps on being overwritten or deleted by remote.

/bin/bash
Linux laptop-c-holtermann.holternetz.netz 3.16.7-53-default #1 SMP Fri Dec 2 13:19:28 UTC 2016 (7b4a1f9) i686 i686 i386 GNU/Linux
git-ftp version 1.4.0

**Comment by c-holtermann** [comment]
Suggested solution in pull request https://github.com/git-ftp/git-ftp/pull/441

**Comment by mkllnk** [comment]
Thank you @c-holtermann. A little contribution can fix big bugs. ;-)
The master branch should be fixed. Please re-open this issue if that's not the case.
