### ISSUE TITLE
clarify manual regards conditional includes

### ISSUE THREAD

**Issue by swiffer** [git-ftp/git-ftp#387]
### Enhancement / Question

What happens in case an untracked File (from package in vendor folder) is No Longer present locally but still on remote Server in case the tracked File changes (Composer.lock)

* Manual seems unclear (See quotes below) do Files persist on the Server ?

If a local untracked file is deleted, any change of a paired tracked file will trigger the deletion of the remote file on the server.

vendor/:composer.lock

But keep in mind that this will upload all files in the vendor folder, even those that are on the server already. And it will not delete files from that directory if local files are deleted.

**Comment by mkllnk** [comment]
It depends.

If you use `vendor/:composer.lock`, then Git-ftp just uploads all files in `vendor` without deleting any from the server. That is to make sure that it doesn't delete any other files that have never been uploaded via Git-ftp.

If you are more explicit and use `vendor/some.file:composer.lock`, then `some.file` will be uploaded if it exists. If it doesn't exist, then it will be deleted on the server as well.

Do you have an idea how to improve the manual? Pull requests are welcome... :-)

**Comment by swiffer** [comment]
Ok, I think that is the behaviour descriped in the manual. Hoped git-ftp would delete a file in a folder aswell.
