### ISSUE TITLE
Connecting with SFTP Init Not Working

### ISSUE THREAD

**Issue by RichPitul** [git-ftp/git-ftp#388]
I am trying to use Bitbucket Pipelines to push my git repository to my server using SFTP automatically.
Just not sure what I am missing.

This is the command
git ftp init -vv --user [USER] --passwd [PSWD] sftp://[DOMAIN]:[PORT]/httpdocs/dev/ --syncroot "site/"

The connection seems to work according to the logs but it says it is trying and failing to create the directories httpdocs and dev, though they already exist on the server.

I get this in the log:
* Initialized password authentication
* Authentication complete
* Creating directory '/httpdocs'
* Creating directory '/httpdocs/dev'
* Creating the dir/file failed: No such file or directory

curl: (78) Creating the dir/file failed: No such file or directory

**Comment by mkllnk** [comment]
Is `httpdocs` in the root directory on the server or in your home directory? On most servers you have access only to your home directory and need to add a `~` to get the right path:
```
git ftp init -vv --user [USER] --passwd [PSWD] sftp://[DOMAIN]:[PORT]/~/httpdocs/dev/ --syncroot "site/"
```

**Comment by RichPitul** [comment]
That was it. Thanks for your help.
