### ISSUE TITLE
Keychain Use Question

### ISSUE THREAD

**Issue by hadfiiw** [git-ftp/git-ftp#389]
I am trying to use git-ftp and I am confused on how to use the "--keychain [[user]@[account]]" option.

More specifically, which user and account should I use?  Being that I am calling the local keychain, is this the login of my Mac?  If so, what would the account be?  Or is it the user/account of the actual keychain item?  Or maybe the user/account of the SFTP server?

I believe I have tried all 3 with no luck.

The other strange thing is no matter what user@account I specify, it always tries to use the user and URL (but not the full path) from the .git/config file.  For example, I have the following config file...

```
[git-ftp]
        user = <sftp username>
        url = sftp://<website>:<port>/home/<username>/public_html/
        syncroot = /Users/ian/Workspaces/<local_git_repo>/
        key = ~/.ssh/id_rsa_a2
        verbose = 1

```
...and run a "git ftp push -k <anything>@<anything> -vv", I get the following error...

```
fatal: Password not found in keychain for account '<sftp username> @ <website>:<port>'.
```

But it shows the same <sftp username> @ <website>:<port> (with a space on either side of the @) no matter what I put in for the -k option.

If I totally leave out the -k option, it gets to actually using CURL with the following error:

* Connected to <website> (x.x.x.x) port <port> (#0)
* SSH MD5 fingerprint: <fingerprint>
* SSH authentication methods available: publickey,gssapi-keyex,gssapi-with-mic,password
* Using SSH private key file '~/.ssh/id_rsa_a2'
* SSH public key authentication failed: Unable to extract public key from private key file: Unable to open private key file
* Failure requesting identities to agent
* Authentication failure
* Closing connection 0

The SSH private key is protected with a passphrase.  If I can get the private key password correctly into the keychain, then have git-ftp correctly call the keychain, I should be able to connect.

On a side note, I can connect so my SFTP site using this same key (and the keychain) using Cyberduck without an issue.

```
$ echo "$SHELL"
/bin/bash

$ uname -a
Darwin <hostname of my Mac> 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

$ git-ftp version
git-ftp version 1.4.0
```

**Comment by mkllnk** [comment]
Thank you for the detailed bug report. I would love someone with OSX experience to answer this. I can just guess and give you some hints.

- The syncroot should be a relative path from your repository. You only need to set it if you want to upload a sub-directory of your repository.
- I would guess that `user@account` means the SFTP user as `user` and your OSX username as `account`. But I'm not sure how the OSX keychain works. According to the manual, it is used to retrieve the FTP password from the keychain. It doesn't mention that it can retrieve the password for the private key.
- Somehow it can't open your private key file. Have you tried to use an absolute path their? You can also try to supply the path to your public key file.

**Comment by hadfiiw** [comment]
Thanks mkllnk.  I will give some of that a shot and let you know.

Maybe as a workaround, is there a way to hard code (or prompt for) the private key password in the .git/config file for git-ftp?

**Comment by hadfiiw** [comment]
Oh, and the keychain can store the keychain password - at least for SSH.

On a Mac, if you edit the .ssh/config file for a host (or all by using * for all hosts) and add some options, it will use a secure key, with a password, without prompting for the password (after the first time).  For all hosts, it would looks something like:

```
Host *
 AddKeysToAgent yes
 UseKeychain yes
 IdentityFile ~/.ssh/id_rsa
```

**Comment by hadfiiw** [comment]
I removed synroot and also put in the full path to the private key file with no luck.

BUT I did get it to work!

I finally noticed that it was curl that was throwing the error that it could not open up the key as I have my key password protected.

After adding the `pass <key_password>` to the _CURL_ config file (located at `~/.curlrc`), it is now connecting correctly and transferring files!

Not sure how I feel about keeping the key password in the .curlrc config file so maybe there is a better way?  I will have to see if curl can use the Mac OSX Keychain (or maybe a new feature for git-ftp?)

If you wouldn't mind leaving this open (for now) I will see if CURL can use the Mac OSX Keychain.

**Comment by LukasFritzeDev** [comment]
I had some trouble to get the keychain feature working as well. As you mentioned the naming `user` and `account` was confusing. Therefor I updated the manual recently so this matches the naming in  Keychain Access Utility now. As well I added [a detailed chapter to the manual](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#keychain-on-macos) with a in depth explanation.

Currently password protected SSH key are not supported by Git-ftp. There is a issue for this: #349. We are working on a solution there. Your trick adding the password to `.curlrc` is a workaround. 

I will close this issue for now but please feel free to re-open it if you still have problems with the keychain.
