### ISSUE TITLE
Using git-ftp with Cloudflare.

### ISSUE THREAD

**Issue by DimitrisPr** [git-ftp/git-ftp#392]
### Bug / Enhancement / Question ?

git-ftp worked properly until I started using cloudflare for security and CDN, changing my nameservers to the cloudflare ones. Now git-ftp push command does nothing.

### Environment

 x86_64 x86_64 x86_64 GNU/Linux
git-ftp version 1.4.0

**Comment by mkllnk** [comment]
What does Git-ftp tell you if you use the `-vv` option?

**Comment by mkllnk** [comment]
It's a bit late now but I guess that you continued to use the same domain name to connect to your server. But by using Cloudflare, your domain name was then pointing to a Clourdflare server and not to your own server. Cloudflare doesn't redirect FTP requests to your original server. That means you need to use your server's IP address when connecting. For example:

```sh
# Before using Cloudflare:
git ftp push ftp://example.com/

# example.com pointed to 1.2.3.4
# After setting up Cloudflare:
git ftp push ftp://1.2.3.4/
```

I hope this information will be useful if somebody else has the same issue. I will close this issue for now but please feel free to re-open it if my guess is not correct and you still have this problem with Git-ftp.
