### ISSUE TITLE
LFS files support

### ISSUE THREAD

**Issue by scanzy** [git-ftp/git-ftp#393]
### Enhancement

It would be great to provide some option to deploy **LFS files**.
Now if I try to deploy some LFS files, the file deployed constains the link data like below, not the file:

```
version https://git-lfs.github.com/spec/v1
oid sha256:ea5452ae8f6a0b88f9bf6c59b8029a651f5b8a19098441c18bfdf5106ded4d5c
size 953
```

Hope you implement this feature, what do you think?

**Comment by mkllnk** [comment]
Sounds good, but I haven't used LFS myself. So this task is probably better for someone else. A question out of interest: Is the file you want to upload actually in your local filesystem or still remotely on Github?

**Comment by scanzy** [comment]
Well, they are stored remotely, but they could be also on local filesystem.

LFS was created to clone **fast** also repos with large files. In fact the large files are not downloaded with the repo, they are stored in a different server/location. In the repo there are some "links" to the large files, so git downloads only the tiny link files when you clone.

You can have the large files locally only if you need them (`git lfs pull` downloads files of current branch and revision), without downloading all the large files of all your repo history.

**Comment by mkllnk** [comment]
Just asking because Git-ftp would need to download the file before it can upload the file. Unless you have shell access, there is probably no way around it.

**Comment by scanzy** [comment]
I should try running git-ftp after `git lfs pull`, if git-ftp uploads files from the working directory it _should_ work, since git lfs would donwload the large files and place them in the working directory. 
What do you think?

**Comment by scanzy** [comment]
It works!
If you have time, I would suggest adding this to the docs (doing `git lfs pull` before `git ftp push` to replace the link files in the working directory with the large files, if they are not yet there) or I can create a pull request.

If you think that would not be helpful we can just close the issue.

**Comment by mkllnk** [comment]
Sorry for the long delay in answering. Great to hear that you got it working. A pull request would be wonderful since my time is very limited at the moment. Thank you! :-)

**Comment by scanzy** [comment]
Sorry for the long delay, finally I created the pull request #428
The suggestion is based on my tests, dicussed in previous comments. 
I've not tried it again using code from the latest commit, but I think it should work since I've not seen so many changes in code
