### ISSUE TITLE
Show upload progression

### ISSUE THREAD

**Issue by sarahdayan** [git-ftp/git-ftp#397]
First, thanks for the amazing tool! This issue is an enhancement suggestion.

### Enhancement

Currently the terminal only shows an _"Uploading..."_ message while the files are being transferred. This is fine but if you're uploading a large amount of files, you may believe it's stuck.

It would be great to see the progression instead. Either a progressbar, a percentage, and/or an ETA would be ideal. Most CLI programs do it already, it would only make Git-FTP better.

Thanks for considering!

**Comment by mkllnk** [comment]
Yes, that would be amazing and has been requested a lot of times: #167, #368.
