### ISSUE TITLE
How to re init a project ?

### ISSUE THREAD

**Issue by eromoe** [git-ftp/git-ftp#399]
I have a project already init before,  now I make  a new branch and  want to deploy this  instead of master.

But I found git ftp push ,just send new files to remote.
Then I delete all files on remote server, and try re init
```
git ftp init
```

got error:
```
fatal: Commit found, use 'git ftp push' to sync. Exiting...
$ git ftp push
No changed files for xxxxxxx:9999/mnt/aaa/. Everything up-to-date.
```

##  Env
os: win7
git: gitbash

**Comment by mkllnk** [comment]
Hi. Git-ftp still thinks that all files are on the remote. To upload all files anyway:
```sh
git ftp init --force
```

From then on, you should be able to upload only the changed files with the push command:
```sh
git checkout other-branch
git ftp push
```

**Comment by eromoe** [comment]
Looks like  `rm -rf` doesn't delete the  hidden file  `.git-ftp.log` which stuck me. Everything is  fine after  delete that file.
