### ISSUE TITLE
check_is_dirty_repository not respecting gitmodules

### ISSUE THREAD

**Issue by ScreamingDev** [git-ftp/git-ftp#400]
### Bug

* How to reproduce the issue?

Have a repo with submodules
Make to major git repo dirty.
Make the subrepo (in directory "srv") clean.
Configure git ftp to sync "srv".

`check_is_dirty_repository` will fail as it looks in the major repo.
It should look in the subrepo instead because this is synced.

**Comment by LukasFritzeDev** [comment]
Should be fixed by #508, so I’ll close this issue.

If someone still has a similar problem with the current dev version, fell free to comment here, then we can reopen the issue.
