### ISSUE TITLE
Submodules are not respected - for no command

### ISSUE THREAD

**Issue by ScreamingDev** [git-ftp/git-ftp#401]
### Bug

* How to reproduce the issue?

See #400 

Try any command like `git catchup` and see that it won't use the submodule (which is the synced one) but the meta-repo (which the developer have).

Why submodule?

You do not want to put the git-ftp config in the submodule or in the final repo, to not have sensitive information in there.
Also the customer came with his environment to you and you now need to wrap around another repo to enable your team working on this.

So please respect submodules.

### Environment

```sh
/bin/bash
Linux vm 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
git-ftp version 1.3.3
```

Please make this `echo $SHELL; git-ftp version; uname -a` so that it's easier to copy from bash. Otherwise you have those "me@mymachine:~/blablalba" in between.

**Comment by DerTanzschuh** [comment]
I think this might be fixed by the recent commits. 

@ScreamingDev Could yo test if this is fixed in the current version `1.6.0-UNRELEASED`. If so we can close this issue.
