### ISSUE TITLE
curl: (79) Error in the SSH layer

### ISSUE THREAD

**Issue by oquirozm** [git-ftp/git-ftp#404]
### Environment
Shell: zsh
Darwin mymac.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
git-ftp version 1.4.0

Suddenly, I started getting this error from a server I've always worked with that didn't present any problems before. It has only happened with this repo, all the others repos are pushing fine. Any idea what should I look at? What could be causing the problem?

**Comment by quincunx** [comment]
Do you know if something has been changed on that server? Maybe the path changed? See https://stackoverflow.com/questions/22507249/curl-error-79-error-in-the-ssh-layer

**Comment by oquirozm** [comment]
@quincunx we already figured it out. The server ran out of space, we had to expand the partition. I'm not the sysadmin so it was hard to diagnose from my side.

Thanks anyway, I'm going to close the issue.
