### ISSUE TITLE
Jenkins and Linode server

### ISSUE THREAD

**Issue by abdulrahman19** [git-ftp/git-ftp#411]
### Question
Hello everyone, please I need some help to deploy my code to my server using Jenkins

* How to reproduce the issue?
the command that I used
git ftp init -u **** -p **** sftp://176.58.113.185/path/to/website/
to clone files from my repo to my server
but It gives me an error every time I try, I use same credential with FileZilla and it works.
* Can you point to a Git repository to reproduce it?
It's a private bitbucket repo 
* Or can you describe the directory structure?

### Environment

Please copy the output of the following commands.
=> git-ftp version 1.0.2
![screenshot from 2018-01-12 16-35-44](https://user-images.githubusercontent.com/22733622/34881330-f3f0e12e-f7bb-11e7-8cdc-5243afd5801a.png)

**Comment by mkllnk** [comment]
The error "Can't access remote" can mean several things.

- Your Jenkins server can't reach the SFTP server.
- Your Jenkins server hasn't verified the SFTP's server public key yet. Try to manually ssh from the Jenkins server with the jenkins user to the SFTP server and confirm the question to add the host to the known_hosts file. Or use the Git-ftp option `--insecure`.
- There is a permission problem.

In any case, it helps to add the `-v` or `-vv` option to the Git-ftp to get a better error message.

**Comment by abdulrahman19** [comment]
It gives me that error 
![screenshot from 2018-01-13 18-08-43](https://user-images.githubusercontent.com/22733622/34907804-f608d1ca-f88c-11e7-8caf-ef2959542bbc.png)

**Comment by mkllnk** [comment]
Okay, so that error `curl: (56) response reading failed` means that there is an issue on the network layer. The manual curl manual says: "Failure in receiving network data."

Oh, your are using the FTP protocol, but specified the SSH port 22 and an SSH server replies. You need to use `sftp://` instead of `ftp://`.

**Comment by abdulrahman19** [comment]
I did 
but nothing happens also :( 
I try everything and doing a search during two days and I can't solve this issue.
that's really disappointed
anyway thanks for your time and effort, best regards.
