### ISSUE TITLE
Entering password just does nothing

### ISSUE THREAD

**Issue by iamdriz** [git-ftp/git-ftp#412]
When I do this:

`git config git-ftp.password "MYPASSWORD"`

Instead of it then opening a new command line like when I enter the URL and USER it just seems to open a new break line.. (where you have to CTRL+C to get out) as if it's expecting more or has crashed? Even adding `-v` at the end of the command doesn't raise anything.. or reveal what the issue is. It's not hanging it just opens that break line.

Have I done something wrong? The password is correct I'm passing to it. It just seems to not properly save it and I have to CTRL + C to get back out again.

I've also noticed that if I call the command: `git config git-ftp.url` it shows the URL that has been saved, but if I do the password one, it just shows blank... is this deliberate or has it not successfully saved the password?

**Comment by iamdriz** [comment]
Weirdly... I changed the name of the parent folder to something else and now it's suddenly allowed the password to be saved :/
Still confused as to what's caused the issue!

**Comment by mkllnk** [comment]
This problem sounds either like you have a special character like `"` in your password and didn't escape it properly or `git-config` has a bug. If renaming the parent folder helped, then that sounds like a bug. Can you re-produce it by renaming the folder again? If yes, it could be good to report the bug with the Git people at git@vger.kernel.org. Or are you on Windows? Then it may be a bug in that implementation and that is probably a different project as well.

**Comment by iamdriz** [comment]
The folder was originally called `github` and had all my projects in. But as I wasn't actually hosting them on github I decided to rename it to `develop`. Git isn't initiated in the parent folder and just on the individual project folders that point to the different repos.

**Comment by iamdriz** [comment]
@mkllnk Ah okies so it wasn't the folder name. The password had an `!` in it. As my host requires a special character in the password. Changed it to something else and it worked. So seems Git Ftp doesn't allow passwords with certain characters in.

**Comment by TechCtrl** [comment]
I had a similar problem using # in my password.  It was resolved by closing my password in double quotes "example!"  NOTE: Single quotes 'example!' does not work.

**Comment by iamdriz** [comment]
@TechCtrl The password was entered in double quotes.

**Comment by mkllnk** [comment]
I think the other way around should work:
```sh
echo 'example!example'
# example!example
echo "example!example"
# bash: !example: event not found
```

**Comment by TechCtrl** [comment]
Interesting.  I just confirmed my notes about this and it not working with single quotes. I noted that it did work with single quotes for command line access

`git ftp catchup -u myName@mydomain.com -p 'PassWord#' ftp.mydomain.com`

but not in .git/config.  For it to work from my .git/config settings I have to use double quotes:
```
[git-ftp]
  user = myName@mydomain.com
  url = ftp.mydomain.com
  password = "PassWord#"
```

**Comment by mkllnk** [comment]
Ah, yes, the Git config files have their own syntax. From https://git-scm.com/docs/git-config:

> A line that defines a value can be continued to the next line by ending it with a \; the backquote and the end-of-line are stripped. Leading whitespaces after name =, the remainder of the line after the first comment character # or ;, and trailing whitespaces of the line are discarded unless they are enclosed in double quotes. Internal whitespaces within the value are retained verbatim.
> 
> Inside double quotes, double quote " and backslash \ characters must be escaped: use \" for " and \\ for \.
> 
> The following escape sequences (beside \" and \\) are recognized: \n for newline character (NL), \t for horizontal tabulation (HT, TAB) and \b for backspace (BS). Other char escape sequences (including octal escape sequences) are invalid.

It doesn't mention single quotes which means that they are treated like any other character. It also lists a few other characters you have to be careful about. The safest is to use shell commands to set values and use single quotes for the shell commands.

**Comment by mkllnk** [comment]
@iamdriz Can this issue be closed?

**Comment by TechCtrl** [comment]
@mkllnk Thank you for that! That resolves a long standing question I've had in the back of my brain.

**Comment by iamdriz** [comment]
So single quotes if setting in the command line and double quotes if setting in a config file?
