### ISSUE TITLE
Different Configs For Each Environments

### ISSUE THREAD

**Issue by ruelluna** [git-ftp/git-ftp#415]
###Enhancement / Question ?

I don't know if this is helpful for anybody but I kinda need this kind of workflow.

1. Setup production Git FTP Credentials and assign an identifier like ```production```
2. Setup staging Git FTP Credentials and assign an identifier like ```staging```
3. So if I want to push to production I would just type ```git ftp push --production``` and use the Git FTP config for the production.
4. So if I want to push to staging I would just type ```git ftp push --staging``` and use the Git FTP config for the staging.

I want to help build this but not familiar with server commands. :)

**Comment by ruelluna** [comment]
I know we can have specific commands to get the specific environments and we can prepare that from notes or something. What I envisioned it here is that we don't need to pull that note every time we deploy something. Just had the configuration at first and then deploy simply to different environments. Noting that it's not that of an issue, imagine handling multiple client websites with multiple environments like ```development```, ```staging```, ```production```, etc.

**Comment by ruelluna** [comment]
I deeply apologize. This has been already realized using [scopes](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#scopes). I was an avid user of this plugin I never had the chance to see the main documentation. You can close this ticket now.

**Comment by mkllnk** [comment]
Thank you for your contribution anyway. It's nice to see that people want to help out. You are welcome to create a pull request to improve the documentation as well.
