### ISSUE TITLE
How to update manually the SHA1 in .git-ftp.log so that the bitbucket pipeline sync the latest changes

### ISSUE THREAD

**Issue by vmalhotra22** [git-ftp/git-ftp#416]
### Bug / Enhancement / Question ?

Hi Guys,

I am trying to fix my Bitbucket pipeline for a repo which had stopped working few weeks ago.
But after fixing I get the message that there is nothing to SYnc.

Thu Jan 18 00:18:17 UTC 2018: Last deployed SHA1 XXXXX/var/www/html/ is .
Thu Jan 18 00:18:17 UTC 2018: No changed files for XXXXXX/var/www/html/. Everything up-to-date.

I tried deleting the SHA1 from .git-ftp.log and rerun the pipeline but of no use. Getting the same message.

How I can sync my latest commit in Bitbucket and the commit mentioned in .git-ftp.log so that my pipeline runs and start syncing the latest commits.

Cheers,
Vroom

**Comment by mkllnk** [comment]
If you know which commit is on the server, you can use `git ftp catchup`.
