### ISSUE TITLE
Always getting "Unknown SHA1 object" with Git 2.16.0

### ISSUE THREAD

**Issue by adamromanowski** [git-ftp/git-ftp#417]
Hello!

I'm just trying out GIT-FTP on Windows 10. I've managed to upload files (to prepared empty directory), but when I make some changes, commit, and try to ``git ftp push`` it I always receive a following message:

``
Unknown SHA1 object, make sure you are deploying the right branch and it is up-to-date.
``

I tried verbose mode to get some information on that, receiving:

``
Last deployed SHA1 for ftp.XXXXXXX is 61ae5251fc4b9709b6dbf97106c90de0abb00478.
``

It appears to be fine when I checked it with repo's log (``git log --format=format:%H``).

I'm clueless at this point :(

Here's my repo:

https://bitbucket.org/j15team/sample_project/

### Environment

```
(...)>echo "$SHELL"
"$SHELL"

(...)>uname -a
'uname' is not recognized as an internal or external command,
operable program or batch file.

(...)>git-ftp version
'git-ftp' is not recognized as an internal or external command,
operable program or batch file.

```

Has anybody encountered this or have any idea what can possibly cause it?

Thanks!

**Comment by oquirozm** [comment]
Having the same issue when trying to push to FTP servers that previously worked without problems.
I'm on MacOS 10.13.2.
git-ftp version 1.4.0.

**Comment by Anahkiasen** [comment]
Same here

**Comment by oquirozm** [comment]
I went to git-scm.com to see what the latest release was and I noticed that the newest version (2.16.0) was released on 2018-01-17, which was very recent. Because I had installed git with homebrew, my current git version was 2.16.0. It updated automatically after I ran `brew update; brew upgrade` a couple of days ago.

The solution was to uninstall the homebrew version of git in my system and now I'm back to 2.14.3. git-ftp is working fine.

So it looks like there's some sort of incompatibility with git-ftp 1.4.0 and git 2.16.0

**Comment by mkllnk** [comment]
@oquirozm Thank you! Great detective work. We have to find out which command changed. I guess you are not setting a syncroot and a command is just passing the empty string to Git, which worked fine in the past and doesn't any more. You can try to set the syncroot to `.` and see if that works with the new Git release.

**Comment by oquirozm** [comment]
@mkllnk thanks! I'm on a rush delivering a project but as soon as I have some time I will try setting the syncroot to .

**Comment by adamromanowski** [comment]
@mkllnk @oquirozm Indeed, setting syncroot to ``.`` solved the problem (for GIT 2.16.0 and GIT-FTP 1.4.0).

**Comment by TechCtrl** [comment]
Because I just had this same problem on a new system when I installed Git 2.16.0 and had no idea about how to set syncroot to .  here is how for future people who see this thread and save them a few minutes of time:

`git config git-ftp.syncroot .`

**Comment by oquirozm** [comment]
@adamromanowski @mkllnk Yep, that works. Should it be added to the manual as a warning a la "required settings"? Or do we just leave the issue open until someone can take a deep look at it?
