### ISSUE TITLE
.git-ftp-ignore - ignore directory only in root directory

### ISSUE THREAD

**Issue by evromalarkey** [git-ftp/git-ftp#419]
### Question ?

I need to ignore src directory only in root directory, now it ignores also src directory in subdirectories

### Environment

Following commands doesn't work, it ignores also src directories in subdirectories

```sh
src/*
```

**Comment by DerTanzschuh** [comment]
Might be a bit late but have you tried this:
`./src/*`

It should only match for the directory in git root.

**Comment by evromalarkey** [comment]
that doesn't work for me, it does not ignore the src folder at all

**Comment by DerTanzschuh** [comment]
I finally had time to test it more closely. You’re right. My suggestion does not work at all. Nothing is ignored with this.

I’ve create a test repo with this structure:
```
- dist/
    - src/
        - test.txt
    - test.txt
- src/
    - test-in-src-to-ignore.txt
- test.txt
```

Your first ignore pattern worked fine for me:
```
src/*
```
```
3 files to sync:
[1 of 3] Buffered for upload 'dist/src/test.txt'.
[2 of 3] Buffered for upload 'dist/test.txt'.
[3 of 3] Buffered for upload 'test.txt'.
```
---
If I want to ignore `src/` in the subdirectory I had to use this:
```
*/src/*
```
But this does not match `src/`dir in root, so it will be uploaded:
```
3 files to sync:
[1 of 3] Buffered for upload 'dist/test.txt'.
[2 of 3] Buffered for upload 'src/test-in-src-to-ignore.txt'.
[3 of 3] Buffered for upload 'test.txt'.
```
---
So what command did you call (`init` or `push`)? What system do you use? Is any syncroot set up in your config or command?

**Comment by evromalarkey** [comment]
Seems to be working ok now, the problem was propably with older version. Thanks for the help!

**Comment by DerTanzschuh** [comment]
You’re welcome.
