### ISSUE TITLE
Disable EPSV via config

### ISSUE THREAD

**Issue by dennis-f** [git-ftp/git-ftp#425]
### Enhancement

Disabling epsv works for me, but for deployment it would be better if i could the setting for that in the config. 

Should work like so:
```sh
git config git-ftp.disable-epsv true
```

**Comment by DerTanzschuh** [comment]
Instead of `true` I’d recommend doing it the same way as for `insecure` with `1`

> `git config git-ftp.insecure 1`

So it would be:
```
git config git-ftp.disable-epsv 1
```

---

But I agree, `true` would be more intuitive. Maybe we can add this as an alternative to all boolean options. As far as I can see we only have `insecure` and then the new one `disable-epsv`.
