### ISSUE TITLE
I cannot "git ftp push" for 2 days

### ISSUE THREAD

**Issue by faytekin** [git-ftp/git-ftp#426]
I have been using git ftp for 2 years. But last 2 days, when I try "git ftp push" I get the error below. I tried it different servers and different repos.

Unknown SHA1 object, make sure you are deploying the right branch and it is up-to-date.
Do you want to ignore and upload all files again? [y/N]: 

fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
There are no files to sync.
Last deployment changed from fb14adfaa121d4c19cf9b41c4579eacc3fe24752 to fb14adfaa121d4c19cf9b41c4579eacc3fe24752.

### Environment
```
Fatihs-iMac:~ aytekin$ sh
sh-3.2$ echo "$SHELL"
/bin/bash
sh-3.2$ uname -a
Darwin Fatihs-iMac.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
sh-3.2$ git ftp version
git-ftp version 1.4.0
sh-3.2$ 
```

**Comment by faytekin** [comment]
[This answer ](https://github.com/git-ftp/git-ftp/issues/417#issuecomment-361418751) solved my problem.

**Comment by Abdelalim-dev** [comment]
Just so you don't have to click on yet another link here's the solution from same link mentioned [above](https://github.com/git-ftp/git-ftp/issues/417#issuecomment-361418751)
`git config git-ftp.syncroot .`
