### ISSUE TITLE
Is `git ftp init` also _pushing_ files to the ftp server?

### ISSUE THREAD

**Issue by khrlimam** [git-ftp/git-ftp#433]
Hey, I am a bit confused with `git ftp init` is that command pushing the file to the ftp server? Since I have understanding about `git init` that this command only initializing the repository not pushing the files to the git remote. Thanks

**Comment by HynekS** [comment]
`git ftp init`  will push files to remote server **if there aren't any files from your local repository** (other files seem to be ignored).  If there are some, you have to use `git ftp push` and your files will be synced. Yes, it used to confuse me as well.
