### ISSUE TITLE
Download seems to do nothing

### ISSUE THREAD

**Issue by jennypabon** [git-ftp/git-ftp#435]
When i make git-ftp download it seems to do nothing. how can i see any log? 
Screenshot while it supose executing download, as you can see, nothings occur, even if i wait for a while or a long time.

![image](https://user-images.githubusercontent.com/31859430/37328942-28833f22-269c-11e8-923e-990f1a142e41.png)

### Environment
/bin/bash
$ Linux PCSISPMI152 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
git-ftp version 1.3.3

**Comment by mkllnk** [comment]
Have you tried `-vv` to increase verbosity?

**Comment by DerTanzschuh** [comment]
Depending on what you try to download and on your network speed download takes quite a while. It downloads all files from the server. As mklink suggested you could use -v or -vv to see things happen. Or you just look in your file explorer / finder to see files plopping up ;)
