### ISSUE TITLE
Sync not working anymore

### ISSUE THREAD

**Issue by ThomasBlt** [git-ftp/git-ftp#436]
https://github.com/git-ftp/git-ftp/blob/08b79512d1beedbca6b0f0166944e9390858359c/git-ftp#L57
@quincunx @mkllnk I don't know why but this is breaking my pushes : all goes smoothly, delta is fine, gitlog is uploaded ... but file content is not 

it uploads all new file content to a subdirectory by the name of my syncroot

I have a syncroot defined to "site/" and for a file named "file.txt" located in my git's "./site/file.txt" file is uploaded to my ftp's 'domain/subdomain/site/file.txt' instead of 'domain/subdomain/file.txt'

**Comment by mkllnk** [comment]
Thank you for the report. I think I found the issue and fixed it in 0aad4b299cad34ad50716e9c1e21bcf31190fbfb.
