### ISSUE TITLE
Issues with git > 2.15.1

### ISSUE THREAD

**Issue by macbookandrew** [git-ftp/git-ftp#439]
### Bug

When using git-ftp with git versions 2.16.1 and 2.16.2, I consistently get this error message from git-ftp: “Unknown SHA1 object, make sure you are deploying the right branch and it is up-to-date.”

I haven’t had time to track down the change in git that is breaking git-ftp, but thought I’d open an issue in case it helps others. When I have time to figure out what’s going on, I’ll update and submit a PR.

For now, downgrading git to v2.15.1 works around the issue and git-ftp works.

### Environment

Please copy the output of the following commands.

```sh
$ echo "$SHELL"
/bin/bash
$ uname -a
Darwin my-computer.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
$ git-ftp version
git-ftp version 1.4.0
```

### Additional Info

I don’t think this is related, but I typically access all my servers via SFTP and I also use dev/production scopes. I’ll test this out more when I have time as well.

**Comment by TechCtrl** [comment]
Add to your .git/config

`[git-ftp]
syncroot= .`

**Comment by macbookandrew** [comment]
@TechCtrl Sweet; thanks!

**Comment by adrum** [comment]
I've also seen this error message when we had a `.git-ftp.log` with a commit hash from a branch that had a different starting point than the branch being deployed. 

Just leaving this here in case someone else experiences the same thing.
