### ISSUE TITLE
List scopes?

### ISSUE THREAD

**Issue by paddelboot** [git-ftp/git-ftp#440]
### Question

Sometimes I am unsure what scope I was using within a project, especially if I haven't worked on it for a while. Is there a way to list them all with their properties? 

Thanks.

**Comment by mkllnk** [comment]
You can, but it's not obvious:
```sh
git config --local --get-regexp ^git-ftp\..+\.url$
```

If that's something you do regularly, you can add it to your bashrc:
```sh
echo 'alias git-ftp-scopes="git config --local --get-regexp ^git-ftp\..+\.url$"' >> ~/.bashrc
```

It could be nice to add that as command to Git-ftp.
