### ISSUE TITLE
Sync folders that are not in git

### ISSUE THREAD

**Issue by akarupt** [git-ftp/git-ftp#444]
Every time i run git-ftp all files in .git-ftp-include are sent. Is it possible to create a hash file at root like the SH1 you create Ex: for every entry in .git-ftp-include you create a hash in the server when you sent. if the local hash of the directory/file is diferent or not existent you sent. Ex of remote file:
dir1=aslçkdjçlkhj12lk3
dir2=asdasd
file1=asdasdasd

Only when the comparing keys are diferent you sent the folder/file.

**Comment by mkllnk** [comment]
Interesting idea, but it sounds like we would be implementing our own version tracking system. I think this is outside the scope of Git-ftp. But maybe you can create a Git repository for your include files. Then you can use Git-ftp for that as well.

**Comment by akarupt** [comment]
You already do that.. the only diference is that you send the included folder everytime i run gitupload. The sugestion is only for that.. One example is i do not put wp-includes and wp-admin of wordpress on git. but when i deploy i need to send those folders. ftp-include does that already, only that sends the 2000 files every time i send a commit x)

**Comment by DerTanzschuh** [comment]
It might be a little off topic, but I would suggest thinking about using the WordPress root directory as git root as well. I don't think that makes any sense. 
In WordPress you have a plugin and/or theme. This should be an own project and therefore also an own git repo. And then you don't have the described problem anymore.
What reasons do you have to use the WordPress directory as git root?

**Comment by LukasFritzeDev** [comment]
Git-ftp is designed to use the power of Git to sync the files. Maybe you could use some other tools like [rsync](https://rsync.samba.org) or [LFTP mirror](https://smyl.es/using-lftp-ftp-to-mirrortransfer-files-from-one-server-to-another/) to achieve a sync of files not handled by git.  

A said before, implementing such a feature would be quite complex and is out of scope – others do this already and do this better than we could.
