### ISSUE TITLE
'git ftp catchup' not working, error message with 'Last deployment cahnge.....'

### ISSUE THREAD

**Issue by azizrahaman** [git-ftp/git-ftp#447]
* After complete formatting my local machine I cloned my bitbucket repo to my local machine and configure git-ftp. But when i entering commang

-> 'git ftp catchup'

It return this result

->Last deployment changed from  to d0d5c11971c665c160ea15f1c30ca9afa2cba7d1.

If i try to ftp push , it return this

->Unknown SHA1 object, make sure you are deploying the right branch and it is up-to-date.
Do you want to ignore and upload all files again? [y/N]:

Though my last commit is same to bitbucket and remote server. How can I resolve this?

### Environment

echo "$Shell" = /bin/bash
uname -a = "Linux AZIZ-PC 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"
git-ftp version = git-ftp version 1.4.0

**Comment by TechCtrl** [comment]
in .git/config add:

`{git-ftp}
    syncroot = .`

**Comment by TechCtrl** [comment]
From [https://helpmanual.io/help/git-ftp/](url) 

> syncroot  Specifies a local directory to sync from as if it were the git project root path.

Prior to Git 2.16.0 if this was not set it passed the empty string and it worked.  Since git 2.16.0 it appears syncroot must be set.

**Comment by jonathanpatt** [comment]
This needs to be corrected with some sort of default rather than manually setting it every time if it's going to happen like this all the time and suddenly break default behavior everywhere.

**Comment by mkllnk** [comment]
Thank you all for your contributions. We had a couple of pull requests tackling this problem. First #380 and then #423 should have fixed this. I created a new release 1.5.0 which was long overdue. Please open this issue again if you have this problem with the new release as well.
