### ISSUE TITLE
fatal: Protocol 'ftpes' not supported by curl

### ISSUE THREAD

**Issue by atlantis-media** [git-ftp/git-ftp#448]
### Bug

* Executing the command "git-ftp init --insecure -D -v -v --user <user> --passwd <passwd> ftpes://<domain>/<directory>" leads to the error "fatal: Protocol 'ftpes' not supported by curl, exiting..."

### Environment

```sh
/bin/bash
Linux 3.2.41-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 GNU/Linux
git-ftp version 1.5.0
```

The upload via the ftpes protocol is not working any longer. A check was added where the protocol in the git-ftp command is checked against the available protocols in curl. This causes an error, because the ftpes protocol is not listed in the available curl protocols. ftpes is executed with the ftp protocol plus the option "--ssl". But the function "check_curl_access" is not respecting this.

The function "check_curl_access" was added with the commit https://github.com/git-ftp/git-ftp/commit/8bb8f7ccad3b7c1f6cecb6a5ce6367fb05c3cbab. 

Could you please adjust the function "check_curl_access" that it is working with the ftpes protocol again?

**Comment by CreativeNotice** [comment]
Yep, we're experiencing the same issue today as well. We use git-ftp in our bitbucket pipelines docker images to update production servers using ftpes.

**Comment by mkllnk** [comment]
Thank you for the excellent report. I created pull request https://github.com/git-ftp/git-ftp/pull/449 to fix this. Are you able to test that version?

https://raw.githubusercontent.com/git-ftp/git-ftp/ac6b52709c14c79d84fe4acc6fec3a1425175c68/git-ftp

**Comment by atlantis-media** [comment]
I've just tested your version. The test was succesful. With this version the upload worked again. Looks very goog for me.
