### ISSUE TITLE
New feature: Maintenance mode activation

### ISSUE THREAD

**Issue by dbtek** [git-ftp/git-ftp#45]
It would be very useful if git-ftp touches a ".maintenance" file on remote server before upload and removes after completion. So we can check the .maintenance and activate maintenance mode automatically.

**Comment by DerTanzschuh** [comment]
Just for reference:
You could implement this on your own by using [Hooks](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#hooks-experimental), which were introduced in v1.3.0.
