### ISSUE TITLE
Question how to select a repository

### ISSUE THREAD

**Issue by swissdude** [git-ftp/git-ftp#454]
Maybe a stupid question, sorry for that...

I'm running git-ftp on a server that has multiple repositories.

How do I select the repository that I want to upload to a dedicated ftp-server?

is a «cd» enough?

I actually wanna trigger the upload with a Jenkins job, so I'd have to put the shell-command into the Jenkins job.
The current setup checks out the repo to a local folder and then ftp's it from there. But with that setup, I end up having every repo twice on my server. (Jenkins, git and git-ftp all run on the same machine).

**Comment by mkllnk** [comment]
Yes, you just go into the directory. For example:

```sh
ls
# repoA repoB repoC
cd repoA
git ftp push
cd ../repoB
git ftp push
# ...
```

**Comment by swissdude** [comment]
Well, when I do that, I get the message «fatal: Not a Git project? Exiting...».

To be clear: I want to ftp the files from my git-repo on my git-host. There's only the git-repo present. The actual files are just on my local machine. 

I just tried it with the actual project on my local machine and that works perfectly. So I guess I'm misunderstanding the functionality of git-push.

As I said in my original question, when I checkout the project first on my git-host using Jenkins, then I'd have everything doubled on my git-host - the actual files and the git-repo. That's not what I want but I guess that's not how git-ftp works.

To be further clear: The goal is to setup a workflow for my company where people work on their local machines and then push their work to the git-server. From there, the files should be uploaded to our ftp-server. So again, the actual files are just present on the developer's local machines and not on the git-server.

**Comment by swissdude** [comment]
Thanks mkllnk! I was afraid that this is the case. I'll have a look at the mentioned link, though.
If it's not what I'm looking for, I'll just go with the checked-out files.
