### ISSUE TITLE
Can't see what files failed to delete

### ISSUE THREAD

**Issue by mintymatt** [git-ftp/git-ftp#458]
### Bug / Enhancement

`WARNING: Some files and/or directories could not be deleted.`

No indication of which files successfully deleted and those which didn't.

### Environment

Please copy the output of the following commands.

```sh
echo "$SHELL"
uname -a
git-ftp version
```
Result:
```
/usr/bin/bash
MINGW64_NT-10.0 CWLT07 2.10.0(0.325/5/3) 2018-04-23 03:21 x86_64 Msys
git-ftp version 1.5.1
```

_Note: thanks for this great bit of kit!_

**Comment by DerTanzschuh** [comment]
Have you tried the verbose mode with the option `-v` or `-vv`? This should show you a lot more information.
