### ISSUE TITLE
.git-ftp-ignore

### ISSUE THREAD

**Issue by meandmegh** [git-ftp/git-ftp#459]
Where does the .git-ftp.ignore file go? I cannot get it to work and I think it's because I can't find where it needs to be located in the file structure.

**Comment by mkllnk** [comment]
It is called `.git-ftp-ignore` and goes into your working directory, the root of your repository. It could look like this:

```
> ls -a /home/meg/my-project
.git
.git-ftp-ignore
index.html
README.md
TODO.md

> cat /home/meg/my-project/.git-ftp-ignore
# Ignore my personal notes and temporary files
TODO.md
*.tmp
```

**Comment by meandmegh** [comment]
I had a typo in my original comment, sorry! My file is named `.git-ftp-ignore` and it's in the root of my working directory. I have it in the root in github, in the root locally, and in the root on the ftp. But anytime I do a `git ftp pull` it pulls down extra files I've told it to ignore. 

This is what my file looks like:

    .git
    .sass-cache
    admin
    Branches
    *.com
    node_modules

But it's still pulling down the node_modules folder and everything else I told it to ignore.

**Comment by mkllnk** [comment]
Ah, thank you for the clarification. That sounds like a bug in the pull feature which is still marked as experimental. Does it work for you when pushing?

**Comment by meandmegh** [comment]
It pushes everything of course, but it does push.

**Comment by mkllnk** [comment]
So the ignore file doesn't work for push either? That's odd. Which version are you using? On which operating system?

**Comment by fullheart** [comment]
I have the same problem (my ignored files are deployed).
I use git ftp in a docker image (alpine:latest).

**Comment by meandmegh** [comment]
I was using the most recent version of git-ftp with High Sierra 10.13.6

**Comment by simonas88** [comment]
I'm also having a similar issue. When pulling an existing remote, it would still download the files that I've specified in the `.git-ftp-ignore` file.
