### ISSUE TITLE
New feature: push only a sub-folder?

### ISSUE THREAD

**Issue by kvdmolen** [git-ftp/git-ftp#46]
With a source-folder and a dist-folder in git, I would only like the dist-folder to be pushed to the FTP. Would it be possible to push only a subfolder?

**Comment by j7j7j7** [comment]
nice, thanks!

**Comment by iamkeir** [comment]
Thanks, this helped.

**Comment by maximus1010101** [comment]
It did not help me. I has project with many directory. I build it then got 'dist/' directory.
I try use git-ftp for deploy with bitbacket pipelines (docker)
When I use command:
`git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD sftp://13.95.149.164:22/home/maximus/site/`
It work successfully, but if i add option:
git config git-ftp.syncroot dist/
or run
`git ftp init --syncroot dist/ --user $FTP_USERNAME --passwd $FTP_PASSWORD sftp://13.95.149.164:22/home/maximus/site/`
i got only one log file: .git-ftp.log

**Comment by mkllnk** [comment]
Git-ftp is for uploading files that are tracked by Git. It sounds like your `dist` directory is compiled from your source files and not tracked by Git. It is better to use a normal FTP client in that case.

**Comment by maximus1010101** [comment]
Thanks a lot for your help!

**Comment by SimonEast** [comment]
While `git-ftp` is designed to only deploy your changes, it is actually possible to deploy your entire `dist` folder on every commit, even if these files are untracked.

You first need to create a file called `.git-ftp-include` in the root of your repo, and add a single line with the path to your dist folder, ensuring you add `!` to the start of the line:

```
!.vuepress/dist/
```

Then run the following command:

```bash
git ftp push --all --syncroot .vuepress/dist/
```

The `--all` uploads ALL your files (even unchanged ones), while `--syncroot` only uploads the files within the specified folder.
