### ISSUE TITLE
upload folder

### ISSUE THREAD

**Issue by Douglasfeuser** [git-ftp/git-ftp#463]
Question
Is there a way i can upload only 1 folder in the repo, insted of the full repo?

this is my repo, but i need to get only the dist folder, and it is in the gitignore file, so i use the pipeline to run the creat dist tasks.
![code_2018-07-31_15-41-44](https://user-images.githubusercontent.com/5115540/43479988-4f0c2096-94d8-11e8-842e-3d5fd5a65052.png)

**Comment by mkllnk** [comment]
You can, but if the folder is not under version control with Git, you can't use Git's benefits of uploading only changed files. It will always upload everything and there are better tools for that.
