### ISSUE TITLE
git ftp download brings a Certificate Verification Error

### ISSUE THREAD

**Issue by KumarAbhirup** [git-ftp/git-ftp#466]
### Bug / Enhancement / Question ?

* How to reproduce the issue?
After setting up FTP server, Username, Password and SyncRoot in git-ftp config, I typed these commands...
```
$ git ftp init
$ git ftp catchup
$ git ftp download
```
* Or can you describe the directory structure?
There's nothing in directory right now. All what I want to do is to download all the files from remote server

* What Error do I get?
```
cd: Fatal error: Certificate verification: subjectAltName does not match ‘ftp.iqubex.com’ (certificate_number)
mirror: Fatal error: Certificate verification: subjectAltName does not match ‘ftp.iqubex.com’ (certificate_number)
1 error detected
```
After the occurance of this error, I was suddenly striked with a Forbidden Error on website which I solved due to host's help.

### Environment
```
/bin/bash
Darwin Kumar 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
git-ftp version 1.5.1
```

**Comment by DerTanzschuh** [comment]
I know the answer comes a little late, but maybe it still helps.

* `git ftp init` is meant to be used if the server is clean (no files online) and you want upload your local files for the first time
* `git ftp catchup` should be used if you know (and are sure) that the current files on the server are exactly the same as your local files. Maybe you uploaded your files with another FTP client.
*  `git ftp pull` might be the right choice for your use case. If you really have nothing in your local git repository and want to download everything from the server, this is exactly what it does for you. So it’s enough to use this command in your case.

For more Information please refer to the [manual](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#actions).

The error message you get indicates that the certificate distribution by the server does not mach the server url you configured. This is a server configuration. Maybe you can ask your host to set up a valid certificate for the used subdomain?

**Comment by DerTanzschuh** [comment]
@KumarAbhirup I see you reacted to my comment. Have you been able to solve the problem yet? If so it would be great if you could share your solution here.

**Comment by KumarAbhirup** [comment]
Nopes, I still get the same error. I used those commands at right times, but didn't help.
```
cd: Fatal error: Certificate verification: subjectAltName does not match ‘ftp.iqubex.com’ (certificate_number)
mirror: Fatal error: Certificate verification: subjectAltName does not match ‘ftp.iqubex.com’ (certificate_number)
1 error detected
```

**Comment by DerTanzschuh** [comment]
Yes this actually the problem I guessed above.

> The error message you get indicates the certificate distributed by the server does not mach the server url you configured.

Yo try to connect to `ftp.iqubex.com`but the certificate is issued to `ind-srv1.websiteserverbox.com`.
So you have some different options now:

- try to connect via the domain set up in there certificate. This might work.
- connect your hoster and ask if it is possible to integrate a suitable certificate with your domain for the FTP connection.
- use the option `--insecure` with git-ftp. This will work on `init`, `catchup` and `push`, but at the moment unfortunately not for `pull` and `download`. (see #346 #366) We are currently working on a solution there and it might be included in the next release coming soon. Maybe some of the workarounds from these issues can help you in the meantime.

**Comment by KumarAbhirup** [comment]
Using --insecure, still gives me the same error 😦

**Comment by DerTanzschuh** [comment]
Did you look at the linked issues? if you try to use `download`, I think it’s this bug. As said, we are currently working a fix for this. Just be patient a few more days. 😉 I’ll let you know if it’s merged.

**Comment by DerTanzschuh** [comment]
This should be fixed by #526 

Could yo test if this is fixed in the current version `1.6.0-UNRELEASED`? If so we can close this issue.

**Comment by mboveiri** [comment]
still get Fatal error: Certificate verification in Gitlab CI

the `yml` file :

```
 image: ubuntu:18.04

   deploy:
        script:
        - apt-get update -qq && apt-get install -y -qq lftp
        - apt-get install -y -qq  git-ftp
        - git config git-ftp.url "176.9.."
        - git config git-ftp.password "mypass"
        - git config git-ftp.user "myusername"
        - git ftp download  --insecure

```
Get

```
 cd: Fatal error: Certificate verification: certificate common name doesn't match requested host name '176.9.197.110' (12:A8:A4:52:E7:38:89:64:7C:8B:04:7A:70:62:5B:B3:B5:91:17:60)
 mirror: Fatal error: Certificate verification: certificate common name doesn't match requested host name '176.9.197.110' (12:A8:A4:52:E7:38:89:64:7C:8B:04:7A:70:62:5B:B3:B5:91:17:60)
```
Any chance.?

**Comment by LukasFritzeDev** [comment]
I don’t know if apt already uses the most recent version of git-ftp. Could you run `git ftp --version` to ensure version 1.6 is used? If not you can install it manually as described in the manual.

**Comment by mboveiri** [comment]
> I don’t know if apt already uses the most recent version of git-ftp. Could you run `git ftp --version` to ensure version 1.6 is used? If not you can install it manually as described in the manual.

response `git-ftp version 1.3.1`
how i can install last version.? 
using `apt-get update && apt-get install -y git-ftp` still install 1.3.3

**Comment by LukasFritzeDev** [comment]
https://github.com/git-ftp/git-ftp/blob/master/INSTALL.md#linuxunix-based-systems-using-direct-download

**Comment by mboveiri** [comment]
it seems the error also trows in 1.6.0

![Error](https://user-images.githubusercontent.com/4364319/80026914-240fea00-84f8-11ea-8fa9-0ecdfa6b3a2d.png)
