### ISSUE TITLE
ftp username contains a @ sign

### ISSUE THREAD

**Issue by strukturart** [git-ftp/git-ftp#467]
Hello

### Bug / Enhancement / Question ?

My username contains a @ sign
When I try to init git-ftp I get the following error message:
 curl: (67) Access denied: 530

how to escaping the @ sign ?

[git-ftp]
	user = myusername@mydomain.com
	url = ftp://mydomain.com
	password = ******

### Environment
Linux Ubuntu 17.10
git-ftp 1.3.1

**Comment by felipecwb** [comment]
try to use URL Encoded

@ => %40

**Comment by strukturart** [comment]
The problem was not the @ sign it was a # in the password.

**Comment by TechCtrl** [comment]
Put your entire password in double quotes:

[git-ftp]
user = myusername@mydomain.com
url = ftp://mydomain.com
password = "******"
