### ISSUE TITLE
Upload via git-ftp was interrupted and stopped half way. Any idea on how to continue?

### ISSUE THREAD

**Issue by wisdomugo** [git-ftp/git-ftp#469]
### Bug / Enhancement / Question ?
I was uploading to my remote server using git ftp init. Due to battery drainage the system went off while the upload was half way. Now i have partial file in the remote server. Is there any way I can continue the upload and harmonize the files between the local and remote server? 

Any git ftp command that can handle it automatically or continue from where the upload stopped?

I appreciate in advance any guide / assistance.

### Environment

Please copy the output of the following commands.

```sh
echo "$SHELL"
/usr/bin/bash

uname -a
MINGW64_NT-10.0 DESKTOP-QQVES9R 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys

git-ftp version
git-ftp version 1.5.1

```

**Comment by mkllnk** [comment]
No, sorry, there is no continue option. You have to start uploading again. If you use another tool for uploading, you can use `git ftp catchup` instead of init to avoid the upload.
