### ISSUE TITLE
Bug with option --insecure and git submodules

### ISSUE THREAD

**Issue by DerTanzschuh** [git-ftp/git-ftp#471]
Seems like there is a bug with the option --insecure and the usage of git submodules.

When I try to init, push or catchup a project which uses a git submodule over an TLS connection with an certificate not valid for the domain the process for the main project is working fine but the submodule fails. This seems to be because the --insecure option is not ”piped“ to the process for the submodule.

### Steps to reproduce:
- Try to init, push or catchup a project over insecure connection
- main project runs perfectly
- submodule fails

### Problem:
Option --insecure is not passed on to submodule fetch. 
In the main project option is set: ```Insecure is '1'.```
In the process for submodule the option is not set: ```Insecure is '0'.```

### Here is a sample log:
```
$ git ftp catchup -s develop -v --insecure
  git-ftp version 1.5.1 running on Darwin My-MBP 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
  Using scope develop if available
  Insecure SSL/TLS connection allowed
  Host is 'xyz.com'.
  User is 'web123'.
  Password is set.
  CACert is ''.
  Insecure is '1'.
  Proxy is ''.
  Path is 'html/plugins/plugin-xyz/'.
  Syncroot is './'.
  The remote sha1 is saved in file '.git-ftp.log'.
  Check if curl is functional.
  Uploading commit log to ftpes://web123:***@xyz.com/html/plugins/plugin-xyz/.git-ftp.log.
  -=#=#   #   #                                                                 
  Last deployment changed from  to 53f4ba218a5b0f5488962121f4cbabbf4884cfe4.
  
  Submodules are mpdf
  Catching up submodule mpdf.
  git-ftp version 1.5.1 running on Darwin My-MBP 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
  Forced mode enabled.
  Host is 'xyz.com'.
  User is 'web123'.
  Password is set.
  CACert is ''.
  Insecure is '0'.
  Proxy is ''.
  Path is 'html/plugins/plugin-xyz/mpdf/'.
  Syncroot is './'.
  The remote sha1 is saved in file '.git-ftp.log'.
  Check if curl is functional.
  Uploading commit log to ftpes://web123:***@xyz.com/html/plugins/plugin-xyz/mpdf/.git-ftp.log.
  #=#=#                                                                         
  curl: (60) SSL certificate problem: Invalid certificate chain
  More details here: https://curl.haxx.se/docs/sslcerts.html

  curl failed to verify the legitimacy of the server and therefore could not
  establish a secure connection to it. To learn more about this situation and
  how to fix it, please visit the web page mentioned above.
  fatal: Could not upload file: 'html/wp-content/plugins/zappalott-cd-shop/mpdf/.git-ftp.log'., exiting...
  fatal: Could not upload., exiting...
```

**System Information**

Shell: /bin/bash
Darwin DeviceName 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
git-ftp version 1.5.1

**Comment by madaxel** [comment]
Same problem here, uploading submodule fails on insecure connections.
Maybe add 
`[ $CURL_INSECURE -eq 1 ] && args+=(--insecure)`
in set_submodule_args line 834
will help?

**Comment by Sofianio** [comment]
Any solutions?

**Comment by Sofianio** [comment]
Oops I missed the `--insecure` part 😅 
Is there a way to always use `--insecure` ?
