### ISSUE TITLE
Build process on Bitbucket pipelines dirties git repo

### ISSUE THREAD

**Issue by readeral** [git-ftp/git-ftp#475]
I'm not sure whether what I'm seeking to do will actually be possible with this library given my process.

I'm using Bitbucket Pipelines and Gulp to build my node project before trying to FTP the build folder to my server. At the moment, I can only successfully get git-ftp to run if I use 'git stash' and 'git stash pop' but this of course (I think) basically stashes away my newly built files, and so git-ftp tells me there is nothing to commit. Without stash, I get the warning about having a dirty repo and it exits out.

Can you suggest a proper workflow in order to manage what I'm seeking? Here's what my YML looks like at the moment:
image: node:8.12.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - apt-get update
          - apt-get install git-ftp
          - git config git-ftp.syncroot dist/jetblack-theme
          - git config git-ftp.url sftp://sftp.neto.net.au:2022/httpdocs/assets/themes/jetblack-theme-staging
          - git config git-ftp.user $FTP_USERNAME
          - git config git-ftp.password $FTP_PASSWORD
          - git config --global user.email "cs@jetblackespresso.com.au"
          - git config --global user.name "Jetblack Espresso"
          - npm install -g gulp
          - npm install -g ntheme
          - ntheme compile -u
          - git stash
          - git ftp push -v
          - git stash pop

**Comment by StephanWagner** [comment]
Had the same issue and just like in @kerryj89's case it was due to the fact that the `
package-lock.json` was modified. Running `git reset --hard` just before `git status` in your pipeline solved the problem.
