### ISSUE TITLE
[Question] how do I deploy a specific version or something already pushed into master?

### ISSUE THREAD

**Issue by martinclavell** [git-ftp/git-ftp#483]
I think this is not a bug, I have read the docs and some issues, but no one is talking about how to do `git ftp push` of something already pushed into git, it only push the stuff on my stash. 

I'm working with friends and they commit their changes, after I do a fetch the `git ftp catchup` don't 'catchup' them, is there a possible to force the `git ftp push` to deploy a specific version of my repo?

**Comment by andypillip** [comment]
Hi Martin.

The `catchup` is used for the case where you have already uploaded these commits by other means than git-ftp. Is that what you would like to do?

All it does is take the hash of your latest commit (in the current branch) and write that hash to `.git-ftp-log` on the server.

If you want to upload a version that's not yet on the server, you need to `git ftp push` it. It will figure out the missing commits (based on the hash in `.git-ftp-log`) and upload the corresponding files.

`git ftp push` is entirely independent from `git push` – it doesn't care about your remotes, only about your local repo state.

Hope this helps?

**Comment by a-hulman** [comment]
> Hi Martin.
> 
> The `catchup` is used for the case where you have already uploaded these commits by other means than git-ftp. Is that what you would like to do?
> 
> All it does is take the hash of your latest commit (in the current branch) and write that hash to `.git-ftp-log` on the server.
> 
> If you want to upload a version that's not yet on the server, you need to `git ftp push` it. It will figure out the missing commits (based on the hash in `.git-ftp-log`) and upload the corresponding files.
> 
> `git ftp push` is entirely independent from `git push` – it doesn't care about your remotes, only about your local repo state.
> 
> Hope this helps?

Hello Andy,
I may have the same issue, so let my try to phrase my question - Can I ftp push a specific commit regardless of current ftp state?

thanks
Alexander

**Comment by mkllnk** [comment]
It always pushes the version in your working tree. For example:

```
git checkout master
git ftp push

# Oh no, there is a bad bug!
git checkout last-good-version
git ftp push
# Uploading old versions of files that changed between master and last-good-version.
```

In the case of working in a team with other people, your current git repository needs to know the commit of your friend: `git fetch friends-repo`
