### ISSUE TITLE
Maxdownload = -1 * Failed writing body (0 != 131)

### ISSUE THREAD

**Issue by Nases** [git-ftp/git-ftp#486]
Hey there' I am having problems with git-ftp while trying to 'git ftp init'.

It connects to the server although I am getting error called:

    * Maxdownload = -1
    * Failed writing body (0 != 131)

Here is whole thing I get when I use:

    git ftp init -vv

    Sun, Jan  6, 2019  6:53:19 PM: git-ftp version 1.5.1 running on MINGW64_NT-10.0 LAPTOP-VQH0NQNO 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys
    Sun, Jan  6, 2019  6:53:21 PM: Host is 'ftp.****.site'.
    Sun, Jan  6, 2019  6:53:21 PM: User is '****'.
    Sun, Jan  6, 2019  6:53:22 PM: Password is set.
    Sun, Jan  6, 2019  6:53:22 PM: CACert is ''.
    Sun, Jan  6, 2019  6:53:22 PM: Insecure is '0'.
    Sun, Jan  6, 2019  6:53:22 PM: Proxy is ''.
    Sun, Jan  6, 2019  6:53:23 PM: Path is 'public_html/'.
    Sun, Jan  6, 2019  6:53:23 PM: Syncroot is 'c:/xampp/htdocs/hsositetest/'.
    Sun, Jan  6, 2019  6:53:23 PM: The remote sha1 is saved in file '.git-ftp.log'.
    Sun, Jan  6, 2019  6:53:23 PM: Check if curl is functional.
    Sun, Jan  6, 2019  6:53:23 PM: Check if ftp://****:***@ftp.****.site is accessible.
    *   Trying ****...
    * TCP_NODELAY set
    * Connected to ftp.****.site (****) port 21 (#0)
    < 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
    < 220-You are user number 4 of 50 allowed.
    < 220-Local time is now 18:53. Server port: 21.
    < 220-This is a private system - No anonymous login
    < 220-IPv6 connections are also welcome on this server.
    < 220 You will be disconnected after 15 minutes of inactivity.
    > USER ****
    < 331 User **** OK. Password required
    > PASS ****
    < 230 OK. Current restricted directory is /
    > PWD
    < 257 "/" is your current location
    * Entry path is '/'
    > CWD public_html
    * ftp_perform ends with SECONDARY: 0
    < 250 OK. Current directory is /public_html
    > EPSV
    * Connect data stream passively
    < 229 Extended Passive Mode Entered (|||61618|)
    *   Trying ****...
    * TCP_NODELAY set
    * Connecting to **** (****) port 61618
    * Connected to ftp.****.site (****) port 21 (#0)
    > TYPE A
    < 200 TYPE is now ASCII
    > LIST
    < 150 Accepted data connection
    * Maxdownload = -1
    * Failed writing body (0 != 131)
    * Closing connection 0
    curl: (23) Failed writing body (0 != 131)
    Sun, Jan  6, 2019  6:53:24 PM: fatal: Can't access remote 'ftp://****:***@ftp.****.site', exiting...

I have set git-ftp options as:

    [git-ftp]
    	url = ftp://ftp.****.site
    	user = ****
    	password = ****
    	remote-root = public_html
    	syncroot = c:/xampp/htdocs/hsositetest/

I would appreciate any suggestions, thank you very much

### Environment

Please copy the output of the following commands.

echo "$SHELL"
/usr/bin/bash

uname -a
MINGW64_NT-10.0 LAPTOP-VQH0NQNO 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys

git-ftp version
git-ftp version 1.5.1

**Comment by apxeonTepukc** [comment]
Same thing happened to me... Any luck solving it?

**Comment by erma1000** [comment]
Same thing happened to me.
In my case did not work with Windows 10 + Git-2.20.1-64-bit.
But changed it to Git-2.15.0-64-bit and it worked.
Try it.

**Comment by robbie9485** [comment]
Thank you @erma1000 , you are a lifesaver, reverting to v2.15.0 totally worked, wish I knew why

**Comment by LukasFritzeDev** [comment]
Does this issues still appear with the current version of git and git-ftp?

**Comment by hamirick** [comment]
FYI, as of 10/18/2019, this is still an issue and reverting to Git 2.15.0 resolved.
