### ISSUE TITLE
curl: (2) Failure establishing ssh session, Connction 0 seems to be dead!

### ISSUE THREAD

**Issue by andypillip** [git-ftp/git-ftp#488]
### Bug

After successfully retrieving the hash from the server, my git-ftp is going through 3315 files "Buffered for upload".

But at some point, I get 

```
* Connection 0 seems to be dead!
…
* Failure establishing ssh session
```

Actually, right after buffering everything seems fine, but apparently for some reason the connection cannot be reused (see #65 ?), but neither can re-connect:
```
Mo 28. Jan 10:51:51 EST 2019: Uploading ...
*   Trying ***.***.***.*** ...
* TCP_NODELAY set
* Connected to ***.***.***.*** (***.***.***.*** ) port 22 (#0)
* User: *******
* Authentication using SSH public key file                                     
* Completed public key authentication
* Authentication complete
} [36 bytes data]                                                              
* We are completely uploaded and fine
######################################################################### 100,0%* Connection #0 to host 165.227.41.251 left intact

* Connection 0 seems to be dead!
…
```
### Environment

Linux schoko 4.20.3-200.fc29.x86_64 #1 SMP Thu Jan 17 15:19:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

git-ftp version 1.5.1

Thanks very much!

**Comment by DerTanzschuh** [comment]
Maybe the upload takes to long so the server closed the connection. Can you try running your command with the option `-v` or even `-vv` to get more details from the underlying curl command?
