### ISSUE TITLE
Visual Studio Code Git ftp plugin

### ISSUE THREAD

**Issue by konrad-lapinski** [git-ftp/git-ftp#489]
### Question ?

Are there any plans on releasing Visual Studio Code plugin?

**Comment by LukasFritzeDev** [comment]
No. There are no plans for plugin development for IDEs.

But you can implement some stuff very easily on your one. Git has a Hooks feature you could use to achieve some functionality a plugin could do. I already wrote about this here: https://github.com/git-ftp/git-ftp/issues/461#issuecomment-491028809

Is this the functionality you were looking for? What could such a plugin do?
If you can provide such a plugin, this would be really great and we would be happy to link it in the manual.
