### ISSUE TITLE
Feature Request: Prevent uploads if not pushed to remote origin

### ISSUE THREAD

**Issue by andrewfenn** [git-ftp/git-ftp#490]
Something that has become a constant issue is my team forgetting to push the code to the remote origin after uploading via GIT FTP. I think it might be good to have a feature that you can set to prevent uploading if you haven't pushed the commit to a remote branch first. Maybe something in the config file such as check_in_remote: "origin/master", or something like that.

**Comment by mkllnk** [comment]
You can implement that yourself with a pre-push hook: https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#hooks-experimental

**Comment by rizkysyazuli** [comment]
You can also use shared deployment script that everyone have to use. Either via shell script, npm script, whatever..

Here's an example using an npm script:

```
// an npm script in your package.json
"scripts": {
  "deploy": "git push origin master && git ftp push"
}
```

And have them do `npm run deploy` for all future uploads.

More info on this: https://www.freecodecamp.org/news/introduction-to-npm-scripts-1dbb2ae01633/
