### ISSUE TITLE
553 Can't open that file: Is a directory. With submodule dir

### ISSUE THREAD

**Issue by duffimc** [git-ftp/git-ftp#491]
Hello,
I use git-ftp v1.5.1, git v2.20.1 on archlinux kernel 4.20.6.

I have a git project that contains a submodule in the wp directory (it's a WordPress installation). When I try to perform git ftp push -vv -s production all files are uploaded to the server except for the wp folder and receive the following error message:

```
> STOR wp
<553 Can not open that file: Is a directory
* Failed FTP upload: 553
* Remembering we are in dir ""
* Uploaded unaligned file size (0 out of 13 bytes)
```

Why?
Thank you very much

**Comment by DerTanzschuh** [comment]
We made some fixes for sumbodule handling recently. And there are more improvements for submodules to come with the new release. I think #508 might solve your problem. 

Can you test the recent changes and give feedback if it works?

**Comment by vachzar** [comment]
> 
> 
> We made some fixes for sumbodule handling recently. And there are more improvements for submodules to come with the new release. I think #508 might solve your problem.
> 
> Can you test the recent changes and give feedback if it works?

I still got an error,
```
Sun Jul 28 03:34:09 UTC 2019: [2 of 2] Buffered for upload 'modules/avx'.
Sun Jul 28 03:34:09 UTC 2019: Uploading ...
curl: (25) Failed FTP upload: 553
Sun Jul 28 03:34:13 UTC 2019: fatal: Could not upload files., exiting...
```
When **avx** folder exist, it shown 553 error.
but when I deleted that folder, and run push again, 
I got 0kb **avx** file. it should be a folder.

**Comment by LukasFritzeDev** [comment]
Which version of Git-ftp did you use?

**Comment by duffimc** [comment]
> We made some fixes for sumbodule handling recently. And there are more improvements for submodules to come with the new release. I think #508 might solve your problem.
> 
> Can you test the recent changes and give feedback if it works?

Hello, I had lost this response. In the short run a test with the new version (1.5.2 right?) and I send my feedback. Thank you!

**Comment by duffimc** [comment]
Today I managed to test with version 1.5.2 of git-ftp and git version 2.17.1 on ubuntu 18.04.3 , but the wp submodule is loaded as a size 0 file. I have tried both with and without set syncroot = .

**Comment by LukasFritzeDev** [comment]
Could you test it with the still unreleased version 1.6.0? The changes mentioned above are not included in v1.5.2. The current development version should fix the issue

**Comment by DThought** [comment]
1.6.0 fixed the issue for me.

**Comment by duffimc** [comment]
Yes! 1.6.0 fixed the issue. Sorry for the delay, I could test it only now. Thank you very much.
