### ISSUE TITLE
How to disable PASV mode and use PORT mode?

### ISSUE THREAD

**Issue by cooper1x** [git-ftp/git-ftp#492]
### Question ?
```
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||52179|)
*   Trying 106.14.194.253...
* TCP_NODELAY set
* Connecting to 106.14.194.253 (106.14.194.253) port 52179
* connect to 106.14.194.253 port 21 failed: Timed out
* Failed to connect to 106.14.194.253 port 21: Timed out
* Failed EPSV attempt. Disabling EPSV
```

**Comment by DerTanzschuh** [comment]
Have you tried the option `--disable-epsv`?

> `--disable-epsv`: Tell curl to disable the use of the EPSV command when doing passive FTP transfers. Curl will normally always first attempt to use EPSV before PASV, but with this option, it will not try using EPSV.
