### ISSUE TITLE
after add submodul curl error

### ISSUE THREAD

**Issue by strukturart** [git-ftp/git-ftp#494]
After I add a submodule I can't upload the changments

```
curl: (9) Upload failed: Permission denied (3/-31)
Di Mär 26 14:29:57 CET 2019: fatal: Could not upload files., exiting...
```

Please copy the output of the following commands.

/bin/bash

Linux xxxxxxxxt 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

git-ftp version 1.5.1

greetings john

**Comment by DerTanzschuh** [comment]
We made some fixes recently #504 which might solve your problem. And there are more improvements for submodules to come with the new release. 

Can you test the recent changes and give feedback if it works?
