### ISSUE TITLE
Support config core.hooksPath

### ISSUE THREAD

**Issue by camlafit** [git-ftp/git-ftp#498]
### Enhancement

Since git 2.9 we can set a specific path to use hooks.
* https://git-scm.com/docs/githooks/2.9.0#_synopsis
* https://github.com/git/git/commit/867ad08a2610526edb5723804723d371136fc643

In bash script relative path is hardcoded and target local hooks repository.

Could be nice to check $(git config core.hooksPath)/ value before

### Environment

Any

**Comment by viktormaar** [comment]
Can you make a new release including this feature please?

**Comment by mkllnk** [comment]
Done: https://github.com/git-ftp/git-ftp/releases/tag/1.5.2
