### ISSUE TITLE
How to delete cache file on ftp server while push?

### ISSUE THREAD

**Issue by AliAmjid** [git-ftp/git-ftp#501]
I have to allways delete cache files of my app manualy from ftp client after depoloy on server. Is there anyway to delete it automaticly with git ftp?

**Comment by DerTanzschuh** [comment]
What cache files do you mean? git-ftp does not create cache files. Some of your application?

Maybe the hook ```post-ftp-push``` [(see here)](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#hooks-experimental) is an option.

**Comment by AliAmjid** [comment]
Yep, my app creats an cache that needs to be deleted after any code change.

**Comment by DerTanzschuh** [comment]
@AliAmjid Did you make it work? Would be great if you could share your solution here.

**Comment by LukasFritzeDev** [comment]
I guess you found a solution. I will close this issue for now but please feel free to re-open it if my guess is not correct and you still have this problem with Git-ftp.
