### ISSUE TITLE
Can't delete files

### ISSUE THREAD

**Issue by Regzanate** [git-ftp/git-ftp#505]
### I pushed the "delete the file" commit ,but the file wasn't deleted from the remote repository on FTPS.

**I can not delete files with git-ftp, even though I can update completely.**
And I added the -v option and got the message I wrote below.
In addition, there was no explanation in the -vv option.

`Sun May  5 00:32:13     2019: Having files to sync.`
`Sun May  5 00:32:13     2019: 1 file to sync:`
`Sun May  5 00:32:13     2019: [1 of 1] Buffered for delete 'test.html'.`
`Sun May  5 00:32:13     2019: Deleting ...`
`Sun May  5 00:32:14     2019: WARNING: Some files and/or directories could not be deleted.`
`Sun May  5 00:32:14     2019: Uploading commit log to ftpes://(secret)/.git-ftp.log.`
`#=#=# `                                                                        
`##O#- #`                                                                       
`Sun May  5 00:32:14     2019: Last deployment changed from (previous) to (new).`

**WARNING: Some files and/or directories could not be deleted.**

---

#### Settings
* Protocol : ftpes
* Insecure : '1'

#### Environment

version : latest
local OS : Windows10
server file permission :  664 rw-rw-r--

**Comment by DerTanzschuh** [comment]
Hm. Quite strange behavior. The file permissions seamed to be ok and I assume the file is on the server, isn’t it?

Are you sure there is no helpful output using `-vv`. I know it’s quite lot but somewhere cur should put out something. For my test environment it looks like this:

```
Sun May 19 13:26:15 CEST 2019: Having files to sync.
Sun May 19 13:26:15 CEST 2019: 1 file to sync:
Sun May 19 13:26:15 CEST 2019: [1 of 1] Buffered for delete 'test.html'.
Sun May 19 13:26:15 CEST 2019: Deleting ...
*   Trying 109.237.133.214...
*
*  a lot of stuff because of TLS handshake and things.
*
> DELE html/development/ftp-test/ftp-simple/test.html
< 250 DELE command successful
* Connection #0 to host test.server left intact
> QUIT
< 221 Goodbye.
```

I would expect to something different in your case, especially where it says `< 250 DELE command successful`. Maybe it gives a reason there.

**Comment by Regzanate** [comment]
Oh, I'm sorry.
I found something in the -vv option. 
But I don't know what's wrong.
I wrote the message below.
```
・
・
・
* Trying ***.***.***.*** ...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer ********)
* Connecting to ***.***.***.*** (***.***.***.***) port 52008
* Connected to www.***.***.***.*** (***.***.***.***) port 21 (# 0)
} [5 bytes data]
> TYPE I

{[5 bytes data]
<200 Transfer type set to I

} [5 bytes data]
> SIZE .git-ftp.log

{[5 bytes data]
<213 41

} [5 bytes data]
> RETR .git-ftp.log

{[5 bytes data]
<150 Opening BINARY mode data connection for .git-ftp.log (41 bytes)

* Maxdownload = -1
* Getting file with size: 41
* Doing the SSL / TLS handshake on the data stream
* successfully set certificate verify locations:
* CAfile: C: / Program Files / Git / mingw64 / ssl / certs / ca-bundle.crt
  CA path: none
* SSL re-using session ID
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{[89 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{[16 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* subject: C = **; L = ***; O = ***; OU = ***; CN = www.***.***.***.***
* start date: Aug 10 10:52:10 2018 GMT
* expire date: Sep 10 10:52:10 2020 GMT
* issuer: C = **; O = ***; CN = NII Open Domain CA-G5
* SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
{[5 bytes data]

######################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
####### Not applicable, can be used either as a standard or as they are used to #################### 100.0% * Remembering we are in dir "**** /"
} [5 bytes data]
* TLSv1.2 (OUT), TLS alert, close notify (256):
} [2 bytes data]
<226 Transfer complete

* Connection # 0 to host www.***.***.***.*** left intact

Tue May 21 00:03:08 2019: Last deployed SHA1 for www.***.***.***.***/****/ is *******************************.
Tue May 21 00:03:08 2019: No changed files, but different commit ID. Changed files ignored or commit amended.
Tue May 21 00:03:08 2019: No files to sync. All changed files ignored.
Tue May 21 00:03:08 2019: There are no files to sync.
Tue May 21 00:03:08 2019: Uploading commit log to ftpes: // ***: ***@www.***.***.***.***/****/.git-ftp.log.
* Expire in 0 ms for 6 (transfer ********)
* Expire in 1 ms for 1 (transfer ********)
* Expire in 0 ms for 1 (transfer ********)
・
・
・
```

**Comment by DerTanzschuh** [comment]
What command did you send? And how are your options set?

The TLS looks quite common. The only useful thing I can get from the log is:

> `There are no files to sync.`

So git-ftp is doing nothing but uploading the commit log. There is no request to delete a file, so the error won’t occur. Or am I missing something?

**Comment by Regzanate** [comment]
I sent these:
```
git config git-ftp.web.url ftpes://www.***.***.***.***/****/
git config git-ftp.web.user ********
git config git-ftp.web.password ********************
git config git-ftp.web.insecure 1
git ftp push -s web -v
```

The commits is `delete "test.html"`. Even if I type these commands, the file remains on the server.
If there are other special things, I don’t know if it’s relevant, but I have used VPN to connect to the server.

**Comment by DerTanzschuh** [comment]
I don't know for sure, but VPN should not be the cause of the problem. 

If you already tried to push this and the commit log was successfully updated on the server (your original post indicates this), git-ftp will think everything is fine and there is nothing to do.

If your last commit is the deletion of the file you could try the following:

```sh
# reset your repo the a prior state (the commit before the most recent one)
# (changes will be kept)
git reset HEAD^
# stash the changes done in the commit just reseted
git stash --include-untracked

# say git-ftp the current state on the server is the one we have local now
# This will upload the current hash to the server
git-ftp catchup

# apply the changes from stash
git stash pop
# commit them
git add .
git commit -m "delete test.html"

# try to push the changes again
git ftp push -s web -vv
```
For the push now there is another commit on the server than local (because of `catchup`) and git-ftp will push the changes from the commit to the server, including the deletion of test.html. In the log we should see if it worked or at least some useful output (hopefully).

**Comment by Regzanate** [comment]
It went well. 
Thank you so much!

**Comment by DerTanzschuh** [comment]
I’m glad I could help.
Maybe the file was locked for some reason when you tried it the first time or there were some other random circumstances.
