### ISSUE TITLE
Question: Auto detect scope, from Nested branch?

### ISSUE THREAD

**Issue by iAdesanyaDaniel** [git-ftp/git-ftp#511]
Good day Team,

Kudos for your work on this project. 

To me, git-ftp is the _sane_ way of uploading your changes as a web-developer. 
The traditional way of uploading changed files manually, really bugled my mind till I was able to make your solution work for me.

My question is this: How can I name a scope, such that it will be auto detected considering the fact that my branch are nested.

For example, I have a "release/staging" branch.

**Comment by mkllnk** [comment]
I think the manual answers your question:

       Hint:  If  your scope name is identical with your branch name.  You can
       skip the scope argument, e.g.  if your current branch is "production":

              $ git ftp push -s

https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#scopes

**Comment by DerTanzschuh** [comment]
@mkllnk you are right, this is working with simple scope names, but if I set up a nested scope like `release/staging` git-ftp returns `fatal: Invalid scope name.`

 But I think this could be fixed quite easily by adding `/` to the allowed characters for scope names in the regex. In my tests that didn’t cause any issues. Or is there any reason why this character should not be allowed?

**Comment by iAdesanyaDaniel** [comment]
@mkllnk I do use that for simple branch name, but to create a git-ftp scope with a nested branch name raises error as @DerTanzschuh as pointed out

**Comment by iAdesanyaDaniel** [comment]
>  by adding / to the allowed characters for scope names in the regex. In my tests that didn’t cause any issues

@DerTanzschuh  how can I temporarily implement this? I use a Windows 10 PC. Thanks.

**Comment by DerTanzschuh** [comment]
> @DerTanzschuh how can I temporarily implement this? I use a Windows 10 PC. Thanks.

I don’t have a Windows 10 machine so I can’t say it for sure.
You might have the executable at `C:\Program Files (x86)\Git\usr\bin`. You can change this as I did in the commit above. Does this work for you?

**Comment by iAdesanyaDaniel** [comment]
Thank you @DerTanzschuh 

After such a long while, I can now stop typing "-s release-production".
It now works perfectly with my "release/production" branch name.

Thank you once again.

**Comment by DerTanzschuh** [comment]
Thank you for your feedback. Good to know it‘s working on Windows 🙂
I‘ll reopen this so we can track it for the next release.

**Comment by mkllnk** [comment]
@DerTanzschuh 
> is there any reason why this character should not be allowed?

No, that should be fine. Scopes are stored as subsections in the git config and the manual says:

       Subsection names are case sensitive and can contain any characters except newline (doublequote " and backslash can be included by
       escaping them as \" and \\, respectively). Section headers cannot span multiple lines.

A `/` is completely fine and used by Git if you name a branch `feature/bla`.

**Comment by DerTanzschuh** [comment]
Ok. Great. I didn't know if there is any other reason why the check was implemented exactly like this.
