### ISSUE TITLE
Travis CI: lftp tests on macOS

### ISSUE THREAD

**Issue by DerTanzschuh** [git-ftp/git-ftp#513]
As you can see in all of the recent pull requests, the tests have troubles with lftp on macOS. 
For example: https://travis-ci.org/git-ftp/git-ftp/jobs/528417096

This might be, because lftp is not included in macOS by default.
Maybe it’s a solution to install lftp “on the fly” with brew. Travis CI even has a addon for this:
https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos

I’ll try that approach.

**Comment by DerTanzschuh** [comment]
Okay – it wasn’t that easy …

**Comment by DerTanzschuh** [comment]
It was actually that simple. I was just too stupid and overlooked that lftp was installed manually by a package. I’ve removed this line call and the build runs through without any failures.

The lftp package was added in https://github.com/git-ftp/git-ftp/commit/3e10a0db4c04ea9bfcbd448125e9ee4efbb5031a in December 2015. The commit message says:

> Installing lftp via homebrew became brittle as well. And it took time.
The tests directory now comes with an lftp pkg file.

@mkllnk What do you think? Maybe something has changed since then? ;) 
My [current build](https://travis-ci.org/DerTanzschuh/git-ftp/builds/528916302) was just 20 seconds slower in testing than the recent ones. Is that a good solution to the issue? I know, it’s not perfect because the homebrew addon also runs in the environment with `$LFTP_SUPPORT=0`, but it's working. Or should i try not to use the official addon and install a recent version of lftp as before?

**Comment by mkllnk** [comment]
That's great to know. You already noticed that we don't test OSX without lftp any more. I'm not sure what to suggest. Our current options are:

- Always run with lftp on OSX leaving part of the code untested. We should skip one of the OSX builds with conditionals: https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
- Always run without lftp on OSX leaving part of the code untested. This means fewer tests but it's the more common environment (making sure that it doesn't break for most people).
- Install lftp manually which is brittle and needs fixing from time to time.
- Uninstall lftp manually which is less brittle but still requires sudo rights.

Do you have other ideas? The uninstall solution seems weird but could actually be the most efficient way. Dependencies can be cached by Travis and uninstalling is much quicker than installing. What do you think?

**Comment by DerTanzschuh** [comment]
leaving part of the code untested EVEN tough we know about it. I don’t think that's a real option ;)

What exactly do you mean by _“which is brittle and needs fixing from time to time”_? I made a test commit (install lftp with but manually after checking the env variable as before) and it runs through without any troubles. It’s even faster than the travis builtin addon. Maybe this “brittle” was caused by the [older macOS images](https://docs.travis-ci.com/user/installing-dependencies/#using-homebrew-without-addon-on-older-macos-images) and is fixed these days?

In my test I disabled AUTO_UPDATE for homebrew so it doe’s not waste time with this task.

**Comment by DerTanzschuh** [comment]
Because of the first problem I contacted the support of travis. After I found the solution I recommended the feature to the support staff to allow – let’s call it – “conditional packages“, to make it possible to load packages depending of the environment variables set up. He was really kind and said they would discuss it on their product team.

And he suggested using the [build matrix feature](https://docs.travis-ci.com/user/build-matrix/) in the meantime to achieve a similar behavior. This could look like this:
```
os:
  - linux
  - osx

env:
  - LFTP_SUPPORT=0

jobs:
  include:
    - os: linux
      env: LFTP_SUPPORT=1
      addons:
        apt:
          packages:
            - lftp
    - os: osx
      env: LFTP_SUPPORT=1
      addons:
        homebrew:
          packages:
            - lftp
```
The only downside would be that we would need to list each job separately. But it’s working – as you can see in the commit above.

---

So we have three different options now:
1. **The previous approach: installing lftp from a custom package**
Downside: A custom package with no other updates than manual ones (doing them by adding a new package version).
2. **Install lftp with brew (manually)**
Downside: Manual call to `brew install`. Can’t benefit from optimizations in the travis build environment. Was “brittle” in the past as @mkllnk noted.
3. **Install lftp with brew addon**
Downside: have to list each job separately. Takes slightly longer than option 2.

What do you think? What’s the way to go?

Based on my testings the last days I’d prefer 2 or 3. Creating a new installer package isn’t that straight forward and seems like a hack for me. Why not use the given infrastructure?

As soon as I get an OK for one of these options I can create a pull request so every upcoming commits can benefit of this.

**Comment by mkllnk** [comment]
Great investigation! I also tend to option 2 or 3. I see these upsides of option 2:

- Faster.
- A working example of how to install lftp.

The upsides of option 3:

- Less OS specific code in the Travis configuration.
- Installing lftp is out of scope of Git-ftp and leaving it up to Travis is probably the most stable way.

I would vote for option 3. It would be really awesome to have this fixed.

**Comment by DerTanzschuh** [comment]
Oh. I think we can now delete the branch [deactivate-lftp-on-osx](https://github.com/git-ftp/git-ftp/tree/deactivate-lftp-on-osx), can’t we?

**Comment by mkllnk** [comment]
Done.
