### ISSUE TITLE
A stupid question about using git-ftp on LAN (Local area network)?

### ISSUE THREAD

**Issue by bwnjnOEI** [git-ftp/git-ftp#518]
I don't have network knowledge, so I have a stupid Q.
I want to use git-ftp between MacOS and LinuxMint.
Two computer access LAN.
Each IP like this: 192.168.3.2, 192.168.3.4.
How do I set a URL (like "ftp://host.example.com:2121/mypath") with my LAN IP?
I know my Q is stupid, but I don't have much time to understand basic network knowledge about ftp.
Please give me a brief but complete operation step.
Thank you so much.

**Comment by DerTanzschuh** [comment]
Which computer is you host/server and which one is the client? Have you already installed a FTP-Server on the host system? Or do you want to use ssh?
