### ISSUE TITLE
The file on the FTP is not deleted

### ISSUE THREAD

**Issue by biguowl** [git-ftp/git-ftp#521]
Hello, thank you very much for the git-ftp.But in use, found that the "git ftp push" does not delete the file on the FTP, found behind plus "- vv" to delete.
I'm a change under test again tomorrow.

**Comment by DerTanzschuh** [comment]
Can you provide some more in depth information?

- Which system do you use?
- What is the output of `$ git ftp --version`?

And more problem specific:
- Which command do you call exactly?
- Do you have configurations that cannot be obtained from the command? 
(defaults set with `git config`, …) 
- What is the output of the command?

**Comment by LuisVR91** [comment]
tengo en mismo problema en windows 10
git-ftp version 1.6.0-UNRELEASED

**Comment by DerTanzschuh** [comment]
I’m sorry, but we need more detail on this. Can you answer the specific questions above as well?
@LuisVR91 Have you tried the option `-v` or `-vv`? This will give you much more information that should help to solve the problem.
