### ISSUE TITLE
`--no-commit` is not respected during pull

### ISSUE THREAD

**Issue by DerTanzschuh** [git-ftp/git-ftp#528]
Although […] `--no-commit` aren't respected. 

(my 2 cents, I would never want an automatic merge, i'd like to see the changes first)

_Originally posted by @laurenskling in https://github.com/git-ftp/git-ftp/issues/346#issuecomment-291577775_

**Comment by DerTanzschuh** [comment]
I was wondering because it was working for me as expected. But I must admit that the behaviour of this command isn’t really intuitive. At the moment a commit is made in every case. The current way is just adding `--no-commit` to the merge arguments. This way the merge is interrupted before a commit is added to the current branch.

**But**
it is not working if git can do a fast forward merge and you did not disable this by default.

Since I have disabled fast forward by default using git config (`git config merge.ff false`) it always worked fine for me. But if fast forward is allowed, which is the default, there are two cases:

1. **local and remote changes**
There is a local commit that has not been pushed to the remote before and some other things we want to pull. 
→ `--no-commit` is doing it’s job and interrupting the merge.
2. **only remote changes**
There are only changes on the remote and the local commit is the one that was pushed to the remote the last time, so merge can do a fast forward and does it.
→ `--no-commit` has no effect at all.

---

So what could a solution look like?

**Solution 1: Don't commit, indeed.**

https://github.com/git-ftp/git-ftp/blob/742269439c1fc5af9faa85b2639de3a2501dd606/git-ftp#L1230-L1231

We could change this and really do no commit if the option is set (and skip the merge command completely). I think that would be the intuitive behavior. But I would be quite a huge change and has potential to break things.

**Solution 2: Force non fast forward**

To force the interruption we could force non fast forward merge if the option is set. This can be done easily by adding `--no-ff` to the merge arguments as well. It wouldn’t change that much but is not that intuitive.

In this case we should at least add a more detailed description in the manual so that it becomes clear how this works.

---

> I would never want an automatic merge

Sounds like a candidate for a default value. Is it worth to add this?

**Comment by mkllnk** [comment]
Great analysis. I tried to copy Git's `pull` behaviour when implementing this. Git does download commits, change the HEAD reference and merges if needed. That's the big difference between fetch and pull. Maybe we need to promote `git ftp download` more? Is that what most people want?

**Comment by mkllnk** [comment]
I'm all for changing default values via the config. Can't hurt.

**Comment by DerTanzschuh** [comment]
> I tried to copy Git's pull behaviour

I see what you did there. If you got it once I think the behaviour is ok. But we should describe it a litte better in the documentation. 

> Maybe we need to promote `git ftp download` more? Is that what most people want?

I don’t know what most people want. I don’t use this features at all, normally. Why do you have a git repo if you change things on the server then? But I’d agree. I think it’s a good idea to add node to the documentation, or what do you mean, “promoting”?

But with all that said it’s definitely solution 2. 
Solution 1 is already implemented with `git ftp download`. I didn't think of that.

**Comment by mkllnk** [comment]
I did this initially because I started using Git for a project where I didn't know if someone else was changing things online as well. Poor communication within the organisation. Another use case is Wordpress or other software that can be updated online. You may want to copy those updates to your local server and debug the code or just keep an exact backup in case an upgrade fails.

**Comment by mkllnk** [comment]
But I have been wondering a few times if that feature is actually out of scope. It could be a separate program.

**Comment by DerTanzschuh** [comment]
Yes you’re right, there are some use cases this can be very useful.
