### ISSUE TITLE
git ftp pull have some bug

### ISSUE THREAD

**Issue by liuyuliang1108** [git-ftp/git-ftp#536]
Frist,I had been git ftp init ,when I transport another git  depository and can git ftp push but git ftp pull can't function ,can down from ftp anythink ,my issue is under.
$ git ftp pull -vv
2019年06月25日 17:09:26: git-ftp version 1.6.0-UNRELEASED running on MINGW64_NT-10.0 WIN10-901251449 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys
2019年06月25日 17:09:27: Syncroot is 'C:/wamp/www/ceshi3/'.
2019年06月25日 17:09:28: currently on branch master
2019年06月25日 17:09:29: Host is '132.232.50.25:21'.
2019年06月25日 17:09:29: User is 'myhisi'.
2019年06月25日 17:09:29: Password is set.
2019年06月25日 17:09:29: CACert is ''.
2019年06月25日 17:09:30: Insecure is '0'.
2019年06月25日 17:09:30: Proxy is ''.
2019年06月25日 17:09:31: Path is ''.
2019年06月25日 17:09:31: The remote sha1 is saved in file 'mySHA1File'.
2019年06月25日 17:09:31: Check if curl is functional.
2019年06月25日 17:09:31: Retrieving last commit from ftp://myhisi:***@132.232.50.25:21/.
* Expire in 0 ms for 6 (transfer 0x6548d0)
*   Trying 132.232.50.25...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x6548d0)
* Connected to 132.232.50.25 (132.232.50.25) port 21 (#0)
< 220 (vsFTPd 2.2.2)
> USER myhisi
< 331 Please specify the password.
> PASS fvvf39449247
< 230 Login successful.
> PWD
< 257 "/home/wwwroot/myhisi"
* Entry path is '/home/wwwroot/myhisi'
> EPSV   #
* Connect data stream passively
* ftp_perform ends with SECONDARY: 0
< 229 Entering Extended Passive Mode (|||33083|).
*   Trying 132.232.50.25...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x6548d0)
* Connecting to 132.232.50.25 (132.232.50.25) port 33083
* Connected to 132.232.50.25 (132.232.50.25) port 21 (#0)
> TYPE I
< 200 Switching to Binary mode.
> SIZE mySHA1File
< 213 41
> RETR mySHA1File
< 150 Opening BINARY mode data connection for mySHA1File (41 bytes).
* Maxdownload = -1
* Getting file with size: 41
{ [41 bytes data]
################################################################################################################ 100.0%* Remembering we are in dir ""
< 226 Transfer complete.
* Connection #0 to host 132.232.50.25 left intact

2019年06月25日 17:09:32: Last deployed SHA1 for 132.232.50.25:21/ is 2265f326a2fb6974ef37381ba9a74442d70a5c2a.
2019年06月25日 17:09:32: Mirroring 132.232.50.25:21/
2019年06月25日 17:09:32:
On branch master
nothing to commit, working tree clean
2019年06月25日 17:09:33: Uploading commit log to ftp://myhisi:***@132.232.50.253:21/mySHA1File.
* Expire in 0 ms for 6 (transfer 0x25948d0)
*   Trying 132.232.50.25...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x25948d0)
* Connected to 132.232.50.25 (132.232.50.25) port 21 (#0)
< 220 (vsFTPd 2.2.2)
> USER myhisi
< 331 Please specify the password.
> PASS fvvf39449247
< 230 Login successful.
> PWD
< 257 "/home/wwwroot/myhisi"
* Entry path is '/home/wwwroot/myhisi'
> EPSV   #
* Connect data stream passively
* ftp_perform ends with SECONDARY: 0
< 229 Entering Extended Passive Mode (|||54612|).
*   Trying 132.232.50.253...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x25948d0)
* Connecting to 132.232.50.25(132.232.50.2) port 54612
* Connected to 132.232.50.25 (132.232.50.25) port 21 (#0)
> TYPE I
< 200 Switching to Binary mode.
> STOR mySHA1File
< 150 Ok to send data.
} [41 bytes data]
* Remembering we are in dir ""
< 226 Transfer complete.
* Connection #0 to host 132.232.50.25 left intact

2019年06月25日 17:09:34: Last deployment changed from 2265f326a2fb6974ef37381ba9a74442d70a5c2a to 08dabd4c03a820b6099a0f25fa46fb0995bfd87a.
2019年06月25日 17:09:34: From 132.232.50.25:21/
2019年06月25日 17:09:34:    2265f326a2fb6974ef37381ba9a74442d70a5c2a..08dabd4c03a820b6099a0f25fa46fb0995bfd87a
Already up to date.

**Comment by LukasFritzeDev** [comment]
I’ll close this one. Its exactly the same as #535
