### ISSUE TITLE
Sync root but ignore folder, and that folder separately

### ISSUE THREAD

**Issue by StefanoV1989** [git-ftp/git-ftp#546]
Hi,
i've a folder with a project, and directories like:
- ajax
- model
- template
etc...

In this folder i've a directory called "newproject" that is routed on 3rd level domain newproject.domain.com

When i'll sync my root local project with the FTP root, what will happen to my "newproject" folder inside it? Can i just ignore it in the root git project because i've another repository specifically for that folder?

Actual folder tree in FTP:
- ajax
- model
- template
- newproject (this is in another repository, so there isn't in local folder, and there isn't in root git project)

Thank you.

**Comment by mkllnk** [comment]
Hi!

If I understand your case correctly, you want to ignore a folder in your project when uploading. Have a look at [ignoring files](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#ignoring-files-to-be-synced) in the manual. That should do exactly what you want.
