### ISSUE TITLE
One config git-ftp by branch

### ISSUE THREAD

**Issue by ArmandArthur** [git-ftp/git-ftp#551]
Hello,

Thanks you for the solftware. I have succes to install. I can push to my FTP the files which have been modified.

My question is the next one : 

Can have some branch on my repository GIT and have one config GIT-FTP for each branch? (develop-recette-production, the FTP is not the same...)

Thanks

**Comment by ArmandArthur** [comment]
Using the scope?

**Comment by mkllnk** [comment]
Exactly, using scopes.

**Comment by LukasFritzeDev** [comment]
Yes, and have a look at the [section in the manual](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#scopes). There is a hint about branch / scope names that might be handy.
