### ISSUE TITLE
[QUESTION] Can I return if a push operation failed or not?

### ISSUE THREAD

**Issue by martapetrella** [git-ftp/git-ftp#553]
### QUESTION 

I wrote a bash script to automize my git-ftp pushes.
I need to do some operations only if my push fails. I imagine that I need to use post-ftp-push and --enable-post-errors.. is it right? If it is right, what is the way to use them?

**Comment by LukasFritzeDev** [comment]
The mentioned `post-ftp-push` is a Hook you can use. 

But I think it could be easier for you to use the exit status of the git-ftp command. Yo can check the exit status and do some stuff depending on it. 

The exit codes are these:
https://github.com/git-ftp/git-ftp/blob/76904712c1cc1c3893fe997ce75b266ec51d8261/git-ftp#L88-L99

If you need a short introduction on how to use exit status you can see [here](http://tldp.org/LDP/abs/html/exit-status.html) or use your favourite search engine ;)

**Comment by martapetrella** [comment]
Wow, thanks!!!! It's a perfect solution, works very well for me!!! Thanks!

**Comment by LukasFritzeDev** [comment]
You’re welcome. 

Since you found a solution, I’ll close this issue. Feel free to reopen it if you have further questions.
