### ISSUE TITLE
Upload of git submodule changes not working

### ISSUE THREAD

**Issue by holzs** [git-ftp/git-ftp#555]
When a submodule is updated with a new commit, the upload of the changes is not working. 

**Steps to reproduce:**

- add submodule to your project
- initially upload the project with the submodule
- make a change in the submodule and merge it to the project
- use git-ftp push to upload the changes
- the upload of the changes from the submodule fails

**Problem:**
The variable $SYNCROOT is not set, when the function "cache_git_submodules" is executed. Because of that the function "is_submodule" does not recognize that the submodule has changed. git-ftp tries to upload the changes without the submodule handling. This causes the error "curl: (25) Failed FTP upload: 550" - with option -vv "550 <submodule folder>: Not a regular file".

**Example Log:**
```
git-ftp push --insecure -v --user <user> --passwd <pwd> ftpes://<server>/<remote_root>
Thu 21 Nov 2019 09:59:40 AM CET: git-ftp version 1.5.1 running on Linux 4.19.0-6-amd64  SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
Thu 21 Nov 2019 09:59:40 AM CET: Insecure SSL/TLS connection allowed
Thu 21 Nov 2019 09:59:40 AM CET: Host is '<server>'.
Thu 21 Nov 2019 09:59:40 AM CET: User is '<user>'.
Thu 21 Nov 2019 09:59:40 AM CET: Password is set.
Thu 21 Nov 2019 09:59:40 AM CET: CACert is ''.
Thu 21 Nov 2019 09:59:40 AM CET: Insecure is '1'.
Thu 21 Nov 2019 09:59:40 AM CET: Proxy is ''.
Thu 21 Nov 2019 09:59:40 AM CET: Path is '<remote_root>'.
Thu 21 Nov 2019 09:59:40 AM CET: Syncroot is './'.
Thu 21 Nov 2019 09:59:40 AM CET: The remote sha1 is saved in file '.git-ftp.log'.
Thu 21 Nov 2019 09:59:40 AM CET: Check if curl is functional.
Thu 21 Nov 2019 09:59:40 AM CET: Retrieving last commit from ftpes://<user>:***/.
######################################################################## 100.0%
Thu 21 Nov 2019 09:59:40 AM CET: Last deployed SHA1 for xxx is xxx.
Thu 21 Nov 2019 09:59:40 AM CET: Having files to sync.
Thu 21 Nov 2019 09:59:40 AM CET: 3 files to sync:
Thu 21 Nov 2019 09:59:40 AM CET: [1 of 3] Buffered for upload '<directory>/submodule1'.
Thu 21 Nov 2019 09:59:40 AM CET: [2 of 3] Buffered for upload '<directory>/submodule2'.
Thu 21 Nov 2019 09:59:40 AM CET: [3 of 3] Buffered for upload '<directory>/submodule3'.
Thu 21 Nov 2019 09:59:40 AM CET: Uploading ...
curl: (25) Failed FTP upload: 550
curl: (25) Failed FTP upload: 550
curl: (25) Failed FTP upload: 550
```

**System information:**
/bin/bash
Linux 4.19.0-6-amd64  SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
git-ftp version 1.5.1

**Possible solution:**
Add the function call of "set_syncroot" to the function "cache_git_submodules". This initializes the variable "$SYNCROOT".
```bash
cache_git_submodules() {
    set_syncroot
    GIT_SUBMODULES="$(git submodule status -- "$SYNCROOT" 2>/dev/null | grep -v '^-' | awk '{print $2}')"
}
```

**Comment by LukasFritzeDev** [comment]
Can you please test the most recent development version (current state of master). We fixed a lot of issues with submodules recently. 

If the problem still exists, please leave a not here. Than I can have a closer look.

**Comment by holzs** [comment]
I've tried it with the master. It works now. The problem is solved with the master. Thank you for your fast reply.

The issue is solved for me.

**Comment by LukasFritzeDev** [comment]
Thank’s for testing this 🙂
