### ISSUE TITLE
Failed to init 

### ISSUE THREAD

**Issue by skd1102** [git-ftp/git-ftp#556]
### Question ?

I try to connect FTP using CMD. All is ok.
but  git-ftp dosen't work
`$ git ftp init`
fatal:  Can't access remote 'ftp://***:***@118.**.**.226'. Network down? Wrong URL? exiting...

I tried everything I could find and think of

### Environment

git-ftp version 1.6.0-UNRELEASED

**Comment by skd1102** [comment]
I found that if the path added after the FTP address does not exist, remote FTP will create the corresponding path. But the above error message is returned.

**Comment by LukasFritzeDev** [comment]
Sorry, I don't understand exactly what you mean by the second comment.

The path does not exists. Ok. 

Are the directories created by git-ftp on the remote server but the execution is still aborted? Does the correct path fixes your issue? What error message would you expect?

**Comment by skd1102** [comment]
Thank you reply 

When i use `$ git ftp init`....
the message is “ Can't access remote.......”
but the server will make the dir if the path does not exists

Other than that, nothing work. And return the same error message

**Comment by skd1102** [comment]
![TIM图片20191126161227](https://user-images.githubusercontent.com/29241509/69610976-d174f380-1067-11ea-979d-eafa57bcd94a.png)

**Comment by skd1102** [comment]
![TIM图片20191126163026](https://user-images.githubusercontent.com/29241509/69612168-23b71400-106a-11ea-82d6-7940071beb91.png)

**Comment by LukasFritzeDev** [comment]
In your command

```
$git ftp init -u blog -p ... ftp://118.xxx.xxx.26
```
you do not specify a path, so Git-ftp will try to access the default dir of the ftp user `blog`.

I was not able to reproduce the issue on my local machine. Even if the directory `remote-dir` does not exists everything is uploaded as expected:

```
$ git ftp init -u ftp -p secret ftp://127.0.0.1:2121/remote-dir
3 files to sync:
[1 of 3] Buffered for upload 'test.html'.
[2 of 3] Buffered for upload 'test.txt'.
[3 of 3] Buffered for upload 'test/test.txt'.
Uploading ...
Last deployment changed from  to 8efdf16a88ba387f62b0f3b2fa7f7a7b9e30faf4.
```

So maybe it’s because of your FTP user `blog`? Maybe it will help to specify a absolute path on the remote server like this:
```
$ git ftp init -u ... -p ... ftp://127.0.0.1:2121//var/www/html/remote-dir
```
Note the two `//` after the ip:port. This not a mistake here, its the way to set an absolute path. And of course you have to adjust the path so it matches the default dir of your ftp user.

**Comment by skd1102** [comment]
@LukasFritzeDev 
thank you again

I use the command
`$ git ftp init -vv -u blog -p *** ftp://118.***.***.***:21 `
and
`$ git ftp init -vv -u blog -p *** ftp://118.***.***.***:21//blog`

I received the message following
![image](https://user-images.githubusercontent.com/29241509/69722539-618f6780-1152-11ea-813c-b5a21fe23378.png)

I do not know what happend...

by the way , I used windows terminal open the git-bash... I like it...hahahaha

**Comment by skd1102** [comment]
maybe some wrong in servers
` > EPSV ` invalid

**Comment by LukasFritzeDev** [comment]
If it’s something with EPSV you could try `--disable-epsv`

**Comment by skd1102** [comment]
@LukasFritzeDev 

Thank you very much, all is ok using `git ftp init --disable-epsv -vv`

thank you!!!

**Comment by LukasFritzeDev** [comment]
You’re welcome. I’m glad I could help.
