### ISSUE TITLE
Add inteligence on when call init or push to decide if init its ok, just do push

### ISSUE THREAD

**Issue by jandrei** [git-ftp/git-ftp#561]
It is a call for a new feature:

Add the possibility of calling git-tfp -something and it decides whether to call an init or just call push.

**Comment by LukasFritzeDev** [comment]
We have a flag for this. 

> `--auto-init` :	Automatically run init action when running push action

So you can call `git ftp push --auto-init`

Is this what you meant?

**Comment by jandrei** [comment]
I will test this today, I look into documentation and dont see it, sorry for create a task.
