### ISSUE TITLE
How to use encrypted password ?

### ISSUE THREAD

**Issue by Maca00** [git-ftp/git-ftp#562]
Hello,

When I add a password with **git config git-ftp.password "my_password"**, everyone can read the password. I want to use encrypted password, 

I have search in Google and I don't find a solution to do that.

Can you help me please ?

Thank you.

**Comment by mkllnk** [comment]
Encrypting your password within the Git configuration is not supported. There are several things you can do though.

It is not true that your password can be read by everyone. Your local Git configuration is usually not shared with anyone. Only people with access to your computer could read the password. Encrypting your filesystem can give you more security on many levels and does not impact the working of Git-ftp.

You may also be able to store your password in your local keychain or keyring which is encrypted with your user account's password. Check out the `-k` option.

**Comment by Maca00** [comment]
Thanks for your replie.

We use Windows and not macOS, so the -k option is not available.

**Comment by LukasFritzeDev** [comment]
Hm. Then there is currently no built in option.

But do you have sftp/ssh access ton the server. If so, you could use a ssh-key to authenticate.

**Comment by fannyhasbi** [comment]
Can anyone see the git-ftp config when it is pushed and pulled by anyone? If so, everyone can see the password inside `.git/config`

**Comment by LukasFritzeDev** [comment]
Your local `.git` folder folder for the repository is neither pushed to a ftp server by git-ftp or to a remote repo . It stays local and can be accessed only by gaining access to your machine. So no one can see your password unless he gains access to the machine somehow.
