### ISSUE TITLE
git ftp init/push can't upload submodules. uploads an empty file instead of whole submodule #198

### ISSUE THREAD

**Issue by reyo** [git-ftp/git-ftp#563]
Clone and remider of: https://github.com/git-ftp/git-ftp/issues/198

This is the same issue. Dockerized latest Debian with version 1.5.1 git-ftp. Upload empty 0 byte files with submodule name instead of uploading the thing.

What ever you did in 1.6.0 UNRELEASED works because I swapped out the /usr/bin version and 1.6.0 uploads the whole thing like it's supposed to.

Pics or didn't happen
1.5.1:
![image](https://user-images.githubusercontent.com/53329/72625789-20495600-3952-11ea-9990-f3c489f83199.png)

1.6.0-UNRELEASED
![image](https://user-images.githubusercontent.com/53329/72625872-48d15000-3952-11ea-9e29-3917ff7596ad.png)

**Comment by mkllnk** [comment]
I now released version 1.6.0. Does that solve your issue?

**Comment by dduenker** [comment]
I had the same issue, 1.6.0 resolves it for me.
