### ISSUE TITLE
How to handle the files that are updated directly on FTP

### ISSUE THREAD

**Issue by sajidmanzoor10p** [git-ftp/git-ftp#564]
This question is a support/help related question rather than an issue. I am planning to git-ftp. Issue is that in my team, some people don't like to use git. They want to update the files on their local and then directly the changed files to FTP

Is there any way that we can track the files that are changed directly via FTP. Is there any way that we check if file is updated on FTP then automatically create a commit and push it to Git.

**Comment by LukasFritzeDev** [comment]
You could have a look at the `pull` command:

> `pull` (EXPERIMENTAL) : Downloads changes from the remote host into a separate commit and merges that into your current branch. If you just want to download the files without a merge, consider download. This feature needs lftp to be installed.

This creates a commit for the remote changes and merges them. I’d recommend two always do this on a clean state in your repo. But as far as I know we do a `git stash` before downloading stuff. But it’s good to give as few potential for issues as possible.

If you want to do this automatically you can also have a look at git hooks. Maybe you could try to pull remote changes after each of your own commits ([post-commit](https://www.git-scm.com/docs/githooks#_post_commit). Here is a good page with a lot of sources about git hooks: https://githooks.com
Or you can use a hook provided by git-ftp that fits your needs. Please refer to the [manual](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#hooks-experimental) for details.
