### ISSUE TITLE
Uninitialized submodules repush the entire project

### ISSUE THREAD

**Issue by arteymix** [git-ftp/git-ftp#57]
When pushing a submodule that is not initialized, git-ftp just repush the entire project.

This is probably due to the fact that there is no .git file in the submodule and git resolve the tree with the root .git folder.

There should be an error output when you try to push an uninitialized submodule.

**Comment by mkllnk** [comment]
I think it's a common use case that you have uninitialised submodules and don't want to push their content. To make this possible, git ftp is now ignoring uninitialised submodules.
