### ISSUE TITLE
Directory vendor is always pushed, and not only when composer.lock is changed

### ISSUE THREAD

**Issue by ghusse** [git-ftp/git-ftp#571]
### Question

I created a github action that uses git-ftp to push the result of a build to my server. It uses `Run SamKirkland/FTP-Deploy-Action@3.0.0` that is launching git-ftp.

The launched command is: `git ftp push --force --auto-init --verbose --syncroot ./ --user *** --passwd *** --insecure --silent sftp://somewhere`

My directory structure:
- `app/`
- `vendor/` (which is created with composer install)
- `.env` generated file
- a bunch of other stuff

My `composer.lock` file is committed.

Before running the push, my github action generates the `.env` file, which is ignored by git, and launches `composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --no-dev` to install dependencies in the vendor directory.

My `git-ftp-include` file has been created to only push the `vendor` directory when the file `composer.lock` changes, as stated in the documentation:

```
!.env
vendor/:composer.lock
````

My `git-ftp-exclude` file:

```
.gitignore
git
.git-ftp-ignore
.git-ftp-include
.github
.editorconfig
.env.j2
.env.example
.gitattributes
```

### Environment

For now, I only have this info:

`git-ftp version 1.5.1 running on Linux 19704ae78e49 5.0.0-1035-azure #37-Ubuntu SMP Wed Mar 18 11:21:35 UTC 2020 x86_64 GNU/Linux`

Do you have any idea why I have this issue? Every deployment takes about 20min because it re-uploads the whole dependency tree each time I change anything.

**Comment by LukasFritzeDev** [comment]
Is your `composer.lock` file listed in `.gitignore` (not ftp)? (Should not be the case)

If it is ignored git-ftp can't register the changes for this file.

**Comment by ghusse** [comment]
As I mentioned  in my post, `composer.lock` is committed. Just to be sure I checked that it was not in the `.gitignore` file.

Here is my `.gitignore file`:

```
/node_modules
/public/hot
/public/storage
/storage/*.key
/vendor
.env
.env.backup
.phpunit.result.cache
Homestead.json
Homestead.yaml
npm-debug.log
yarn-error.log
/migrate.please
```

**Comment by jorovipe97** [comment]
I have the same issue, generating activity to re-open the issue.
