### ISSUE TITLE
My uploaded files' text get additional line breaks

### ISSUE THREAD

**Issue by vribeiro48** [git-ftp/git-ftp#576]
Does this happen to anyone else? Every single file I upload gets line breaks before and after every single line of the file. This is a deal breaker for me. I look through the issues list and it looks like no one is having this issue.

Example:
Original file

```
<html>
<head>
</head>
</html>
```

Uploaded file through Git-FTP

```
<html>

<head>

</head>

</html>
```

**Comment by LukasFritzeDev** [comment]
Hey, sorry but I can not reproduce this behaviour. Just tried it with a file using utf8 and Unix-Linebreaks (LF).

Can you give us some more information?
- Whats your file encoding?
- What kind of line breaks do you use? (LF, CR, CRLF)
- Whats your local system and what is the remote?
- How do you know there are additional line breaks?
