### ISSUE TITLE
--changed-only not working

### ISSUE THREAD

**Issue by partha7278** [git-ftp/git-ftp#577]
### --changed-only not working 

It will upload all files

Unknown SHA1 object, could not determine changed files, taking all files.

**Comment by LukasFritzeDev** [comment]
Could you please provide some more information?

- What command did you call?
- Hv you pushed (or init) before?

**Comment by partha7278** [comment]
> Could you please provide some more information?
> 
> * What command did you call?
> * Hv you pushed (or init) before?

1) Try  **git-ftp-args:  --changed-only**  
2) Yes, already pushed 

It's try to determine the changed files but  unable and print 
'Unknown SHA1 object, could not determine changed files, taking all files.'

**Comment by LukasFritzeDev** [comment]
Can you please drive the complete command (with censored credentials)?

Is there a File call `.git-ftp-log` on the remote server? What is its content? Should be a commit hash. Is the commit available in the repo you run the command from? You can check this by running `git checkout` with the commit hash from the file. In my case this looks like:
```
$ git checkout 1e47b0e535428828db505647b4d0ecedb91ac871
Note: switching to '1e47b0e535428828db505647b4d0ecedb91ac871'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
```
If this all is fine we have to dig deeper.

If there is no `.git-ftp-log` on the remote, maybe the config is wrong. (Please note that some FTP-Clients just don’t show hidden files.) If the file exists and has a commit hash as content but `git checkout` does not work, it might be you have only a partial commit history in your local repo and therefore the commit can not be found. This might happen in CI environments.

**Comment by partha7278** [comment]
yes there is a `.git-ftp.log` file present and 
in this file one commit hash present
this commit hash available in my repo

**Comment by LukasFritzeDev** [comment]
Sorry for not coming back to this in a while.

Once again, to be able to help you we need the command you called:
>Can you please give the complete command (with censored credentials)?

Since you said in your original post “It will upload all files” I’ll assume you do a `push` or `init` command. The flag `--changed-only` is only needed for a pull aka download command. When using push you do not need this option at all.
