### ISSUE TITLE
cannot delete folders via on git-ftp  push+sync method

### ISSUE THREAD

**Issue by webbyus** [git-ftp/git-ftp#584]
I cannot delete folders via on git-ftp  push method

#Production 
a
`- git-ftp push -u $FTP_PROD_USERNAME $FTP_PROD_HOST -p $FTP_PROD_PASSWORD --syncroot .`

Could you please help me to resolve this

**Comment by LukasFritzeDev** [comment]
Which protocol do you use?

Can you please add the verbose option `-vv` and give us a detailed log. Maybe there is a hint.

**Comment by webbyus** [comment]
Thanks for your fastest reply . Lukas .

I m using `sftp` protocol

Here is steps. You can replicate it 


Step 01
I added this code to my .gitlab-ci.yml file

- git-ftp push -u $FTP_PROD_USERNAME $FTP_PROD_HOST -p $FTP_PROD_PASSWORD --syncroot .

Step 02
Eg : abc /a.txt , abc/ b.txt

Then i remove abc folder . but git-ftp removed only a.txt and b.txt, NOT "abc" folder 

Similar thing - https://github.com/git-ftp/git-ftp/issues/505

**Comment by webbyus** [comment]
![screen-1](https://user-images.githubusercontent.com/43690533/88484049-6cbcc080-cf89-11ea-9e52-bf49d18e9903.PNG)
![screen-2](https://user-images.githubusercontent.com/43690533/88484052-721a0b00-cf89-11ea-92a9-739eb5747f7d.PNG)
![screen-3](https://user-images.githubusercontent.com/43690533/88484053-72b2a180-cf89-11ea-9395-a86e9d720a8e.PNG)

**Comment by LukasFritzeDev** [comment]
The log lists 3 files to delete. Are these files in the directory deleted? 

If so please have look at #345. This is a similar or even the same issue 🙂

**Comment by webbyus** [comment]
I don't know lukas . i can't understand that . Please advise me.

**Comment by LukasFritzeDev** [comment]
Oh. Sorry. My question was already answered by your posts. 

As you can read in issue #345 we already know about this problem. Your problem is the sane as described there, isn't it? But Unfortunately we currently do not have time to implement this.

**Comment by webbyus** [comment]
Yes Luckas. Same isssue happened me . Kindly request you to fix this incident. Otherwise its not be helpful for us.
