### ISSUE TITLE
git: 'ftp' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by MineLone** [git-ftp/git-ftp#585]
``
$ git ftp init
git: 'ftp' is not a git command. See 'git --help'.

The most similar command is
        fetch
```

**Comment by LukasFritzeDev** [comment]
What OS do you use? Which shell / command line do you use? How have you installed git-ftp? Is git-ftp in your path?

Just posting an error message isn’t that helpful 😉

**Comment by MineLone** [comment]
very sorry
Let me describe the problem
I am using windows10 and I copied git-ftp directly to the git/bin directory.
Then executed the ‘chmod 755 /bin/git-ftp’ command

**Comment by MineLone** [comment]
Thank you very much.
I found the cause of the problem
You need to click in the location of '/ git / usr / bin / git FTP'
