### ISSUE TITLE
Issues when using git ftp download

### ISSUE THREAD

**Issue by JayKandari** [git-ftp/git-ftp#589]
### Bug / Enhancement / Question ?

* How to reproduce the issue?
```
> git ftp download
cd: Fatal error: Certificate verification: subjectAltName does not match "example.com" (CD:C4:04:C0:FA:0D:7F:0E:E4: ...)
```

### Environment

Please copy the output of the following commands.

```sh
echo "$SHELL"
/bin/zsh

uname -a
Darwin ABC-MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

git-ftp version
git-ftp version 1.6.0
```

**Comment by JayKandari** [comment]
Adding `--insecure` flag makes it work. 
```
git ftp download --insecure
```
Closing this.

**Comment by LukasFritzeDev** [comment]
The underlying problem could be the lack of SFTP / TLS support in your curl version or a invalid certificate. You should check this since the flag `--insecure` allows man in the middle attacks.
