### ISSUE TITLE
Sync fails on Git Bash for Windows

### ISSUE THREAD

**Issue by 0xCAB** [git-ftp/git-ftp#590]
### Bug / Question

Although there are committed changes there is always the message "No changed files, but different commit ID. Changed files ignored or commit amended."

I'm new to Git-ftp, `git ftp catchup` worked fine and it placed the .git-ftp.log onto the FTP server.

Looked at the code in the function `list_changed_files`. Seems that TMP_GITFTP_UPLOAD and TMP_GITFTP_DELETE are always empty after the calls to git diff.

Anything I can test to help narrowing down?

### Environment

Running on Git for Windows v2.28.0 using Git Bash.

echo "$SHELL"
/usr/bin/bash

uname -a
MINGW64_NT-10.0-18362 DESKTOP-IJQT7BI 3.1.6-340.x86_64 2020-07-09 14:33 UTC x86_64 Msys

git-ftp version
git-ftp version 1.6.0

**Comment by LukasFritzeDev** [comment]
Are you sure the changed filse are not ignored by `.gitignore` or `.git-ftp-ignore`?

Have you tried calling the `git diff` command by yourself with the commit hash stored in `.git-ftp.log` on the server? Whats the output of this command?

Maybe there is useful output if you use the verbose flag `-vv` to get debug info?

**Comment by 0xCAB** [comment]
Thanks a lot for you feedback and sorry for the delay on my side, live got in the way.

It works now! :)
But I have no idea what the initial problem was. Spent some time trying to repoduce it.
I had installed a more recent version of curl in the mean time. (But using the old one works as well.)
Played with the `core.autocrlf` settings but realized you are using the `-z` option with `git diff`.
Also tried some other stuff but till now didn't manage to find out what my initial mistake was.
Hm seems it's fine and we can close the issue.
