### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by nise** [git-ftp/git-ftp#596]
It would be wounderful if you could mention that there is separate .gitignore fle, namely .git-php-ignore, needed. I was expecting that the standard .gitignore would considered and sent sensitive data to an SFTP server. 

Not mentioning this issues in the readme.md is a potential security issue!

**Comment by nise** [comment]
Even in the manual this information appears after scrolling have the page.

**Comment by LukasFritzeDev** [comment]
Git-ftp ignores all the files listed in `.gitignore` and `.git-ftp-ignore`. If you want to upload files ignored by git (listed in `.gitignore`) you have to list the explicitly in the `.git-ftp-include` file.

Are you sure your sensitive files are not committed to your repo and are not listet in the `.git-ftp-include` file?
