### ISSUE TITLE
error: pathspec 'index.txt' did not match any file(s) known to git

### ISSUE THREAD

**Issue by AlftheElf** [git-ftp/git-ftp#600]
I'm following these instructions: https://git-ftp.github.io/

But when I ```git commit index.txt -m "Add new content"```, I get ```error: pathspec 'index.txt' did not match any file(s) known to git```

On MacOS.

**Comment by LukasFritzeDev** [comment]
I think this is a gut issue and not specific to Git-ftp.

There error message says git is not managing the file `index.txt`. I’d assume you never added it to git. The command you try to execute works for files already tracked by git, but not for new files.

In this case you have to run two commands:
```
# adding the file so git knows it should track the file
git add index.txt
# creating a commit
git commit -m "Add new content"
```
