### ISSUE TITLE
https://github.com/git-ftp/git-ftp/issues/603#issue-818944069

### ISSUE THREAD

**Issue by Kroshboy** [git-ftp/git-ftp#603]
### Bug / Enhancement / Question ?

* How to reproduce the issue?
* Can you point to a Git repository to reproduce it?
* Or can you describe the directory structure?

### Environment

Please copy the output of the following commands.

```sh
echo "$SHELL"
uname -a
git-ftp version
```

**Comment by Kroshboy** [comment]
https://github.com/git-ftp/git-ftp/issues/603#issue-818944069

**Comment by Kroshboy** [comment]
Oohh

**Comment by LukasFritzeDev** [comment]
Sorry. If we don't get an useful error description, we can't provide any help nor fix a possible bug.
