### ISSUE TITLE
Conflict with .gitignore

### ISSUE THREAD

**Issue by ve3** [git-ftp/git-ftp#606]
### Bug

* How to reproduce the issue?
  * Create .gitignore with `System/vendor` directory to ignore. This **System/vendor** will be ignore on Git commit & push.
  * On running command `git ftp push` the directory **System/vendor** will not be uploaded. It should only be ignored on comit and push NOT upload.
* Can you point to a Git repository to reproduce it?
  * https://github.com/RundizBones/framework
* Or can you describe the directory structure?
  * System
    * ...
    * Libraries
    * Middleware
    * vendor
    * ...
  * config
  * ...

If I add these to .git-ftp-include, it will be very bad idea because it will be upload ALL of vendor folders and files which is very large amount of files.
```
!System/vendor
!System/vendor/*
```

### Environment

Windows 10 64 bit
git-ftp version 1.6.0

**Comment by mkllnk** [comment]
Yes, that's a known limitation of the git-ftp-include file. If you want to upload only some of the files, they need to be under version control. Otherwise we don't know which files are up-to-date and which ones need uploading.
