### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Baldonak** [git-ftp/git-ftp#622]
Hi, I'm trying to transfer the files by ftp to the server but I'm getting the following problem. In my case, the curl command works.

I First, i want clarify I have very limited knowledge. I saw that there is another topic on the same subject but it is closed and unresolved.

Any idea how i can fix this problem? Attached result of "git ftp init -vv"

`$ git ftp init -vv
Wed Nov 10 15:04:26 2021: git-ftp version 1.6.0 running on MINGW64_NT-10.0-19043 LAPTOP-L309IPRJ 3.1.7-340.x86_64 2021-03-26 22:17 UTC x86_64 Msys
Wed Nov 10 15:04:26 2021: Syncroot is './'.
Wed Nov 10 15:04:28 2021: Host is '*********.com:21'.
Wed Nov 10 15:04:28 2021: User is '*******'.
Wed Nov 10 15:04:28 2021: Password is set.
Wed Nov 10 15:04:29 2021: CACert is ''.
Wed Nov 10 15:04:29 2021: Insecure is '0'.
Wed Nov 10 15:04:29 2021: Proxy is ''.
Wed Nov 10 15:04:29 2021: Added missing trailing / in path.
Wed Nov 10 15:04:29 2021: Path is 'htdocs/public_html/'.
Wed Nov 10 15:04:29 2021: The remote sha1 is saved in file '.git-ftp.log'.
Wed Nov 10 15:04:30 2021: Check if curl is functional.
Wed Nov 10 15:04:30 2021: Check if ftp://***********:21 is accessible.

Trying 145.14.144.97:21...
connect to 145.14.144.97 port 21 failed: Connection refused
Failed to connect to **********.com port 21: Connection refused
Closing connection 0
curl: (7) Failed to connect to **********.com port 21: Connection refused
Wed Nov 10 15:04:33 2021: fatal: Can't access remote 'ftp://*****:***@l*********:21'. Network down? Wrong URL? exiting...`

**Comment by Ruitjes** [comment]
@Programisto1011 I'm facing the same exact issue, did you find a way to solve it?
