### ISSUE TITLE
New action git ftp dirty-upload

### ISSUE THREAD

**Issue by jgauchel** [git-ftp/git-ftp#624]
### Enhancement

Upload dirty files, only.

```sh
git ftp dirty-upload
```

**Comment by ecxod** [comment]
> dirty
What are dirty files?

**Comment by jgauchel** [comment]
@ecxod Sorry for the bad description!

The goal is, to avoid unnecessary commits. We are working with vsc. And from time to time we need to upload our files to the server, before we commit our code - so for testing purposes, only

Without this feature, we would produce a lot of unnecessary commits.

"dirty" means - in this context - all unstashed or uncommited files in the current git directory. 

I selected this label, because this feature is not part of the "Git Spirit" and so feels kind of dirty... 

Of course, you can rename it, if you have a better idea!
