### ISSUE TITLE
Using git ftp in VS code bash terminal?

### ISSUE THREAD

**Issue by vip4rk** [git-ftp/git-ftp#629]
Hey,

I just installed git ftp and it's working perfectly except my "git ftp push" command is working only on git bash terminal (opened with admin rights) and not in the git bash terminal used directly in my VisualStudio code programm.

Can somebody understand why?
Would be even easier to do it in the VS bash terminal and not in another cmd window :)

Thank you in advance for your help!

Vip4rk

**Comment by zunnur-persys** [comment]
Do you open vscode with admin right?
