### ISSUE TITLE
Files with whitespace are not handled correctly

### ISSUE THREAD

**Issue by lucaheft** [git-ftp/git-ftp#633]
### Bug

* How to reproduce the issue?
Add a file which contrains a whitespace in it's filename. Push the repository to a ftp server. The file with the whitespace in it's name will not be transmitted.

### Environment

gitlab docker runner with latest alpine docker image
```
Linux runner-dvmb8sb1-project-94-concurrent-0 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 Linux
git-ftp version 1.6.0
```

When using -vv flag, this error pops up:
``curl: (3) URL using bad/illegal format or missing URL``

**Comment by Eliastik** [comment]
Same issue on Ubuntu 22.04 with Git-ftp version 1.6.0

**Comment by mark20044** [comment]
Same issue here: git-ftp 1.6.0, mingw64, curl 7.85.0
File with whitespace in the name shows
`curl: (3) URL using bad/illegal format or missing URL`

**Comment by rtharston** [comment]
Same issue on macOS with git-ftp 1.6.0 and curl 7.85.0.

If I upgrade to 7.87.0 then curl erroneously reports this as an `Out of memory` error and ends prematurely (see issue #648 in this repo, and the curl issue linked from there).

**Comment by danieltowers** [comment]
Same here, filename with spaces does not upload. I have tried to use `--data-urlencode` in the git-ftp script but I can't get it to work
