### ISSUE TITLE
git-ftp push -v shows curl out of memory

### ISSUE THREAD

**Issue by kitsguru** [git-ftp/git-ftp#648]
### Bug 
I recently updated brew which included the update to curl

doing a git-ftp push is showing several errors

```
[1370 of 1846] Buffered for upload
# uploads file then:
curl: (28) FTP response timeout
# continues uploading then
curl: (27) Out of memorycurl: (28) FTP response timeout
# finally
curl: (27) Out of memory
Wed 21 Dec 2022 11:10:08 PST: fatal: Could not upload files., exiting...
```

It appears the upload may have completed, but the delete files never executed
not sure how you can reproduce other than to have a large number of files to upload and to delete

### Environment

```sh
echo "$SHELL" => sh-3.2
uname -a => Darwin madhu.local 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64
git-ftp version => git-ftp version 1.6.0
curl --version => curl 7.87.0
```

**Comment by kitsguru** [comment]
I have opened an issue with curl
[https://github.com/curl/curl/issues/10130](https://github.com/curl/curl/issues/10130)

**Comment by rtharston** [comment]
I was getting a similar issue and added what I was seeing to that curl issue. Here is a quick summary of what was happening for me.

The out of memory issue is curl reporting the wrong error. Going back to curl 7.85.0 (@kitsguru's idea, thanks!!) gives the proper error. In my case I had files with a space in the file name, which means the real issue I am seeing is #633 and an issue in curl is making it seem like a memory issue.

**Comment by rtharston** [comment]
@kitsguru, did switching back to curl 7.85.0 complete resolve your issue, or do you just get different errors? With that many files it is very possible that you are getting errors but not seeing them because your terminal history fills out. Maybe you could try this massive upload with the output redirected to a file so you can see the whole thing again.

Even better, if you redirect the errors to a separate file you don't have to pick them out of the whole output.
`command > output.txt 2>error.txt`

**Comment by kitsguru** [comment]
With 7.85 everything worked as expected as far as I know, but that was an assumptiom. I will retry when I get a moment log the resutls as suggested. command > output.txt 2>error.txt

I have never verified the end result and since no errors were reported assumed all was good. I think I will create an alias to always log the results.

**Comment by rtharston** [comment]
Context I forgot to add before suggesting logging the errors:

When I used 7.86.0 or above the 'Out of memory' error causes the process to end immediately, making the error more obvious. When I tried 7.85.0 I got a `(3) URL using bad/illegal format or missing URL` error for every one of my bad urls, but the rest of the files uploaded correctly, making it seem like it completed okay.

**Comment by kitsguru** [comment]
The fix in https://github.com/git-ftp/git-ftp/pull/638 solves the issue reported here, although the curl out of memory error was misleading.
