### ISSUE TITLE
.git-ftp-include wildcards

### ISSUE THREAD

**Issue by iamale** [git-ftp/git-ftp#72]
That's something we need on big websites (for example, I don't want to add every blog post to my `.git-ftp-include` file).

**Comment by mkllnk** [comment]
@iamale We have wildcards in form of whole directories now. Does that help in your setup?

If not:
- Would a hook like `ftp-post-push` help?
- Or describe in more detail how the wildcards should work.
- Or open a pull request.

**Comment by iboinas** [comment]
I think i can give some input here, i think im on the same boat :)

when using composer in a project, e.g. Laravel php framework

there is a folder vendor, that is ignored by .gitignore by default
this happens because its managed by composer, with a composer.json and composer.lock for setup... it means git never tracks this folder...

without further detail, what would be a nice wildcard would be such as:

.git-ftp-include-also :)
vendor

and vendor, even if not tracked by git, would be also uploaded...

right now testing making a git repo on vendor folder...
when would change the composer, would also take care of vendor as a separate repo...

so the  .git-ftp-include-also   wildcards would be very nice to have also!! ;)

**Comment by mkllnk** [comment]
@iboinas We added support for including whole directories in the newest version. You can try that if you like. Just put the following line into `.git-ftp-include`:
```
vendor/:composer.lock
```
But it will upload all files in that folder.

**Comment by iboinas** [comment]
even if vendor folder is in .gitignore?

**Comment by mkllnk** [comment]
@iboinas Yes, that's what .git-ftp-include is for. But composer.lock has to be tracked by Git. If you would like to upload vendor **every time**, you write:
```
!vendor/
```

Internal git-ftp procedure:

- Create lists of changed files.
- Filter against .git-ftp-ignore.
- Include from .git-ftp-include.

**Comment by iboinas** [comment]
hmm sorry i messed that!

perfect! congrats! is this project donation-ware?

**Comment by MozMorris** [comment]
@mkllnk uploading an entire folder fails here. Perhaps my syntax is incorrect:

    › git ftp push -s stage                                    
    There are 2 files to sync:                                 
    [1 of 2] Buffered for upload 'app/webroot/css/screen.css'. 
    [2 of 2] Buffered for upload 'app/webroot/css/critical/'.  
    Uploading ...                                              
    fatal: Could not upload files., exiting...                 

.git-ftp-include

    !app/webroot/css/screen.css
    !app/webroot/css/critical/

git-ftp version

    › git-ftp --version         
    git-ftp version 1.0.1

**Comment by MozMorris** [comment]
Just to add, that...

    vendor/:composer.lock

...does work.

**Comment by mkllnk** [comment]
@iboinas Regarding donation ware. We don't have any financial setup for the project itself. But you can donate to @resmo privately. You can pay him via paypal, flattr or bitcoin. Thanks for bringing the topic up.

**Comment by MozMorris** [comment]
@mkllnk how should an entire folder be included without a reference file?

**Comment by mkllnk** [comment]
Good point. Including files from lines starting with `!` was broken. I just uploaded a newer version. Now it should work as you tried it:
```
!app/webroot/css/critical/
```

**Comment by MozMorris** [comment]
Hello @mkllnk 

Sorry for taking ages to reply to this. I'm still not sure this is working, in fact there may have been a regression.

This is my .git-ftp-include

    !css/screen.css
    !css/critical/

But now neither the file nor the directory is listed when performing a push. 

When I step through the code https://github.com/git-ftp/git-ftp/blob/71834260629f911960cceb4f1bdfe02233ab9745/git-ftp#L607-L612 the files are added to the `"$tmp_include_upload"` file. It looks like:

    css/screen.css
    css/critical//campaigns.css
    css/critical//contact.css
    css/critical//destinations.css
    css/critical//faqs.css

So I'm not sure what's happening. Just to note that these files are not in the git repos, they're ignored.

```shell
$ git-ftp --version
git-ftp version 1.1.0-UNRELEASED
````
